/*
 * iux_msg.h
 * 	- iux messages
 *
 * Written by Sekeun Shin. <etazeus@itxsecurity.com>
 * Copyright (c) ITX security, Dec 26, 2010
 *
 */

#ifndef __IUX_MSG_H
#define __IUX_MSG_H


#define MKRPL(m) ((m & 0xFFF) | 0x4000)

/*
 * MESSAGE CLASS

	----------------------------------------------------------------------------
	|	Types		|	Usage
	----------------+-----------------------------------------------------------
	|	NFY			|	VW, SCM, UXM notification (need not to reply) mainly (SCM-->VW)
	----------------+-----------------------------------------------------------
	|	REQ			|	SCM-->VW request (need to reply as RPL)
	----------------+-----------------------------------------------------------
	|	RPL			|	reply message against to the REQ
	----------------+-----------------------------------------------------------
	|	RET			|	VW-->SCM request (used with Non-blocking APIs)
	|				|	SCM will send it when the request is processed.
	----------------+-----------------------------------------------------------


 */

/*
 * NOTATION
 *
 * 	- lower case 'i' prefix	: used in the module level except VW
 * 	- upper case 'I' prefix : used over the all around
 *
 * 	- 'p' : means param of the message
 * 	- 'd' : means data of the message
 */



#define VWMSG_MASK		0xF000
#define INFY_NFNOTIFY_MIN	0x11A0
#define INFY_NFNOTIFY_MAX	0x11FF

//temp for webra
#define INFY_MAX_GROUP  INFY_NFNOTIFY_GROUP_END
#define IREQ_MAX_GROUP  IREQ_GROUP_END
#define IRPL_MAX_GROUP  IRPL_GROUP_END

#define DO_ENUM(e) e,
#define DO_DESC(e) #e,


#define INFY_GROUP(msg) \
    msg(INFY_IPCAM_CHANGE_NOTIFY) \
    msg(INFY_DISPLAY_NOTIFY) \
    msg(INFY_ALRDB_CHANGE_NOTIFY) \
    msg(INFY_FACTORY_DEFAULT_NOTIFY) \
    msg(INFY_SYSTEM_DATA_LOAD_NOTIFY) \
    msg(INFY_FORMAT_CMPL) \
    msg(INFY_RECOVERY_CMPL) \
    msg(INFY_QUERY_ERROR) \
    msg(INFY_QUERY_SUCCESS) \
    msg(INFY_BURN_QUERYING) \
    msg(INFY_BURN_ERASING) \
    msg(INFY_BURN_EXTRACTING) \
    msg(INFY_BURN_PROG) \
    msg(INFY_BURN_ERROR) \
    msg(INFY_BURN_CANCEL) \
    msg(INFY_BOOT_DISK_ADDED) \
    msg(INFY_BOOT_DISK_REMOVED) \
    msg(INFY_BOOT_DISK_CHANGED) \
    msg(INFY_BOOT_DISK_CONFLICT) \
    msg(INFY_BOOT_DISK_NEED_FORMAT) \
    msg(INFY_FORMAT_RATE) \
    msg(INFY_RECOVERY_RATE) \
    msg(INFY_BOOT_FORMAT_ERROR) \
    msg(INFY_BOOT_RECOVERY_ERROR) \
    msg(INFY_DATA_DELETE_RATE) \
    msg(INFY_RTL_SET_RATE) \
    msg(INFY_FWUP_RATE) \
    msg(INFY_MEDIA_STATUS_CHANGED) \
    msg(INFY_DISP_IP_CAMERA_INFO) \
    msg(INFY_DISP_INT_DISK_INFO) \
    msg(INFY_DISP_ODD_INFO) \
    msg(INFY_DISP_EXT_STORAGE_INFO) \
    msg(INFY_PREV_RUNNING_UNC_ERROR) \
    msg(INFY_CFRM_UNC_ERROR_DETECTED) \
    msg(INFY_DISP_WAN_IP) \
    msg(INFY_TML_DATE_CHANGED) \
    msg(INFY_TML_PLAY_CHANGED) \
    msg(INFY_TML_START_CHANGED) \
    msg(INFY_TML_END_CHANGED) \
    msg(INFY_TML_DOUBLE_CLICKED) \
    msg(INFY_VERIFY_RATE) \
    msg(INFY_CALENDAR_CLOSED) \
    msg(INFY_IPCAM_RESET_BEGIN) \
    msg(INFY_IPCAM_RESET_END) \
    msg(INFY_IPCAM_RESET_PENDING) \
    msg(INFY_IPCAM_RESET_REQ_FAIL) \
    msg(INFY_IPCAM_RESET_TIMEOUT) \
    msg(INFY_TML_UNSET_SECTION) \
    msg(INFY_THUMBNAIL_CMPL_OBJ) \
	msg(INFY_THUMBNAIL_CMPL_OBJ2) \
    msg(INFY_QUERY_OVER) \
    msg(INFY_THUMBNAIL_TOTALLY_CMPL) \
    msg(INFY_TML_SCROLL_UP) \
    msg(INFY_TML_SCROLL_DOWN) \
    msg(INFY_RTL_SET_CMPL) \
    msg(INFY_RESERVED) \
    msg(INFY_QUERY_NO_VIDEODATA) \
    msg(INFY_INIT_LIVEVIEW) \
    msg(INFY_DIV_CHANGE) \
    msg(INFY_USER_LOGON) \
    msg(INFY_ALT_EXPIRED) \
    msg(INFY_RECOVERY_EXPIRED) \
    msg(INFY_LANG_CHANGED) \
    msg(INFY_IPCAM_CALIBRATION_BEGIN) \
    msg(INFY_IPCAM_CALIBRATION_END) \
    msg(INFY_IPCAM_CALIBRATION_PENDING) \
    msg(INFY_IPCAM_CALIBRATION_REQ_FAIL) \
    msg(INFY_IPCAM_CALIBRATION_TIMEOUT) \
    msg(INFY_IPCAM_CALIBRATION_FAIL)\
    msg(INFY_IPCAM_CALIBRATION_SUCCESS)\
    msg(INFY_VWND_RUN_ALL_EVENT) \
    msg(INFY_VWND_STOP_ALL_EVENT) \
    msg(INFY_VWND_RUN_RIGHT_PRESS) \
    msg(INFY_VWND_STOP_RIGHT_PRESS) \
    msg(INFY_VWND_CHANGE_BORDER) \
    msg(INFY_VWND_DRAW_FOCUS) \
    msg(INFY_VWND_ERASE_FOCUS) \
    msg(INFY_IPCAM_ONEPUSH_BEGIN) \
    msg(INFY_IPCAM_ONEPUSH_END) \
    msg(INFY_IPCAM_ONEPUSH_PENDING) \
    msg(INFY_IPCAM_ONEPUSH_REQ_FAIL) \
    msg(INFY_IPCAM_ONEPUSH_TIMEOUT) \
    msg(INFY_CAPTURE_IMAGE) \
    msg(INFY_PB_IMAGE_STATUS) \
    msg(INFY_BURN_SUCCESS) \
    msg(INFY_PLAYBACK_STARTED) \
    msg(INFY_LIVE_OPEN) \
    msg(INFY_CAM_TITLE_CHANGED) \
    msg(INFY_PANIC_REC_STATUS) \
    msg(INFY_GET_DDNS_STATUS) \
    msg(INFY_PB_PLAY_STATUS) \
    msg(INFY_ERASE_CH_RATE) \
    msg(INFY_CHECK_REMOTE_NEWFW) \
    msg(INFY_QC_TEST_SET_BUTTON) \
    msg(INFY_QC_TEST_INFO_ADD) \
    msg(INFY_QC_TEST_INFO_CLEAR) \
    msg(INFY_VWND_IPCAM_ZIG_INFO) \
    msg(INFY_PASSWD_INIT_BY_WEB) \
    msg(INFY_VKEY_SIZE_INCREASE) \
    msg(INFY_VKEY_SIZE_DECREASE) \
    msg(INFY_FORMAT_API_BEGIN) \
    msg(INFY_FACDEF_API_BEGIN) \
    msg(INFY_TIMECHANGE_API_BEGIN) \
    msg(INFY_NETCHANGE_API_BEGIN) \
    msg(INFY_SVCRESTART_API_BEGIN) \
    msg(INFY_FORMAT_API_CMPL) \
    msg(INFY_FACDEF_API_CMPL) \
    msg(INFY_TIMECHANGE_API_CMPL) \
    msg(INFY_NETCHANGE_API_CMPL) \
    msg(INFY_SVCRESTART_API_CMPL) \
    msg(INFY_DBIMPORT_API_BEGIN) \
    msg(INFY_DBIMPORT_API_CMPL) \
    msg(INFY_OPENMODE_ENTER_INSTALL) \
    msg(INFY_OPENMODE_LEAVE_INSTALL) \
    msg(INFY_REBOOT_SYSTEM) \
    msg(INFY_VAA_SELECT_RULE_ID) \
    msg(INFY_SMS_TEST_RESULT) \
    msg(INFY_VCA_SELECT_MODIFY_POINT) \
    msg(INFY_STREAM_DATA_RELOAD) \
    msg(INFY_IPCAM_FWUP_RATE) \
    msg(INFY_IPCAM_FWUP_CMPL) \
    msg(INFY_VWND_DRAW_NEW_VCA) \
    msg(INFY_NOT_SUPPORT_PLAYRATE) \
    msg(INFY_TML_SECTION_CHANGED) \
    msg(INFY_TIMECHANGE) \
    msg(INFY_CHECK_REMOTE_S1_NEWFW) \
    msg(INFY_EMAIL_VERIFICATION_RESULT) \
    msg(INFY_VAA_ITX_PRESS_ZONE_ID) \
    msg(INFY_VAA_ITX_2PRESS_ZONE_ID) \
    msg(INFY_VAA_ITX_PRESS_CNTR_ID) \
    msg(INFY_VAA_ITX_2PRESS_CNTR_ID) \
    msg(INFY_VAA_ITX_PRESS_CALB_ID) \
    msg(INFY_VAA_ITX_2PRESS_CALB_ID) \
    msg(INFY_VAA_ITX_PRESS_NONE_ID) \
    msg(INFY_ONETIME_ID) \
    msg(INFY_ONETIME_PASSWORD) \
    msg(INFY_IPCAM_FWUP_ERROR) \
    msg(INFY_IPCAM_FWUP_ERROR_VERSION) \
    msg(INFY_REMOTE_SUPPORT_REMAIN) \
    msg(INFY_REMOTE_SUPPORT_START) \
    msg(INFY_REMOTE_SUPPORT_END) \
    msg(INFY_ARCHIVE_API_BEGIN) \
    msg(INFY_ARCHIVE_API_CMPL) \
    msg(INFY_TEXTBOX_ADD_LINE) \
    msg(INFY_TEXTBOX_MODIFY_LINE) \
    msg(INFY_TEXTBOX_CLEAR) \
    msg(INFY_SHOW_LIVEOSD_CAMINFO) \
    msg(INFY_HIDE_LIVEOSD_CAMINFO) \
    msg(INFY_RETURN_LIVE) \
    msg(INFY_QC_TEST_INFO_UPDATE) \
    msg(INFY_USER_ACTION_BROKEN_RAID) \
    msg(INFY_BROKEN_RAID_START) \
    msg(INFY_BROKEN_RAID_CMPL) \
    msg(INFY_LEAVE_LIVE) \
    msg(INFY_DETECTED_CLON_DEVICE) \
    msg(INFY_VWND_SWITCH_PRESS) \
    msg(INFY_VWND_SWITCH_MOVE) \
    msg(INFY_VWND_SWITCH_RELEASE) \
    msg(INFY_VWND_DRAW_PTZ_ARROW) \
    msg(INFY_VWND_REDRAW_RECT) \
    msg(INFY_MAIL_TEST_RESULT) \
    msg(INFY_CHECK_CABLE_TEST) \
    msg(INFY_RAID_CHANGE_STATUS_RECOVER) \
    msg(INFY_RAID_CHANGE_STATUS_DEGRADE) \
    msg(INFY_RAID_CHANGE_STATUS_REBUILD) \
    msg(INFY_RAID_CHANGE_STATUS_BROKEN) \
    msg(INFY_VWND_DRAW_PTZARROW) \
    msg(INFY_VWND_ERASE_PTZARROW) \
    msg(INFY_VWND_DRAW_VIDEO_IMAGE) \
    msg(INFY_VWND_ERASE_VIDEO_IMAGE) \
    msg(INFY_SHORTCUT_PIP_CAPTURE_IMAGE) \
    msg(INFY_RETRY_SHORTCUT_PIP_CAPTURE_IMAGE) \
    msg(INFY_CAMSWITCH_CAPTURE_IMAGE) \
    msg(INFY_PACKET_DUMP_INSERT_MEDIA) \
    msg(INFY_PACKET_DUMP_REMOVE_MEDIA) \
    msg(INFY_HID_KPAD_NOTI) \
    msg(INFY_HID_CURSOR_CHANGE) \
    msg(INFY_SNAP_QUERY_SUCCESS) \
    msg(INFY_SCREEN_LIVE_DIV_CHANGE) \
    msg(INFY_SCREEN_LIVE_FULL_TOGGLE) \
    msg(INFY_SCREEN_LIVE_OSD_TOGGLE) \
    msg(INFY_SCREEN_LIVE_SEQ_TOGGLE) \
    msg(INFY_ARCH_BURN_API_BEGIN) \
    msg(INFY_ARCH_BURN_API_CMPL) \
	msg(INFY_DEFAULT_LOAD_CSTLAYOUT) \
    msg(INFY_APPQC_AUTO_TEST_ALL) \
    msg(INFY_APPQC_AUTO_TEST_AUDIO) \
    msg(INFY_APPQC_AUTO_TEST_ALARM) \
    msg(INFY_APPQC_AUTO_TEST_NETWORK) \
    msg(INFY_APPQC_RTC_SYNC) \
    msg(INFY_APPQC_FACTORY_DEFAULT) \
    msg(INFY_APPQC_AUTO_TEST_RS485) \
    msg(INFY_APPQC_AUTO_TEST_FAN) \
    msg(INFY_APPQC_AUTO_TEST_TEMPER) \
    msg(INFY_APPQC_AUTO_TEST_RS232) \
    msg(INFY_APPQC_AUTO_TEST_POE) \
    msg(INFY_APPQC_DHCP_RENEW) \
    msg(INFY_SCM_PREPARE_FWUP_OPEN) \
    msg(INFY_DETECTED_NEWFW) \
    msg(INFY_VWND_SWITCH_CANCEL) \
	msg(INFY_NODISK_BY_WEB)  \
	msg(INFY_FORMAT_BY_WEB)  \
    msg(INFY_USERINFO_INIT_BY_WEB)  \
	msg(INFY_FLUSH_FISHEYE_PARAM)  \
	msg(INFY_SWITCH_UX_GPU_MODE)  \
    msg(INFY_DVAA_ITX_PRESS_ZONE_ID) \
    msg(INFY_DVAA_ITX_2PRESS_ZONE_ID) \
    msg(INFY_DVAA_ITX_PRESS_CNTR_ID) \
    msg(INFY_DVAA_ITX_2PRESS_CNTR_ID) \
    msg(INFY_DVAA_ITX_PRESS_CALB_ID) \
    msg(INFY_DVAA_ITX_2PRESS_CALB_ID) \
    msg(INFY_DVAA_ITX_PRESS_NONE_ID) \
	msg(INFY_VWND_DRAW_NEW_DVABX) \
	msg(INFY_WAIT_DRAW_EXPOSE) \
	msg(INFY_DELAY_DEEPLEARNING_EVENT) \
	msg(INFY_DELAY_AI_EVENT) \
	msg(INFY_DELAY_AI_FACE_EVENT) \
	msg(INFY_DELAY_AI_PLATENO_EVENT) \
	msg(INFY_DELAY_AI_GENERIC_EVENT) \
	msg(INFY_DEEPLEARNING_GROUP_THUMBNAIL) \
	msg(INFY_DEEPLEARNING_ANIMATE_THUMBNAIL) \
	msg(INFY_SET_WEB_FWUP_MOUNT_PATH) \
	msg(INFY_FACE_BULK_UPLOAD_RESULT) \
	msg(INFY_CAPTURE_NETWORK_MAP_SCREEN) \
	msg(INFY_EXTERNAL_ANALYTICS_RULES) \
    msg(INFY_AIBOX_ANALYTICS_ADDITIONAL_EVENT) \
	msg(INFY_AI_QUICK_REGIST_CAPTURE) \
    msg(INFY_NVM_DATA_IS_CHANGED) \
    msg(INFY_OPENMODE_ENTER_INSTALL_BY_NVM) \
    msg(INFY_OPENMODE_LEAVE_INSTALL_BY_NVM) \
    msg(INFY_OPENMODE_READY_INSTALL_BY_NVM) \
    msg(INFY_OPENMODE_FAIL_INSTALL_BY_NVM) \
    msg(INFY_GET_IPCAM_THUMBNAIL)   \
    msg(INFY_SHOW_OLD_VER_CAM_INSTALL)   \
    msg(INFY_GROUP_END)

#define INFY_NFNOTIFY_GROUP(msg) \
	msg(INFY_CAM_TITLE_NOTIFY) \
	msg(INFY_NOVIDEO_NOTIFY) \
	msg(INFY_NET_NOTIFY) \
	msg(INFY_ENC_NOTIFY) \
	msg(INFY_DISK_USAGE_NOTIFY) \
	msg(INFY_DISK_FULL_NOTIFY) \
	msg(INFY_DISK_OW_NOTIFY) \
	msg(INFY_SYSDB_CHANGE_NOTIFY) \
	msg(INFY_NETDB_CHANGE_NOTIFY) \
	msg(INFY_AUDDB_CHANGE_NOTIFY) \
	msg(INFY_DSKDB_CHANGE_NOTIFY) \
	msg(INFY_CAMDB_CHANGE_NOTIFY) \
	msg(INFY_USRDB_CHANGE_NOTIFY) \
	msg(INFY_ALMDB_CHANGE_NOTIFY) \
	msg(INFY_ACTDB_CHANGE_NOTIFY) \
	msg(INFY_DSPDB_CHANGE_NOTIFY) \
	msg(INFY_RECDB_CHANGE_NOTIFY) \
	msg(INFY_COVERT_NOTIFY) \
	msg(INFY_SMART_ERROR_NOTIFY) \
	msg(INFY_ANALOG_REC_NOTIFY) \
	msg(INFY_IPCAM_REC_NOTIFY) \
	msg(INFY_VLOSS_NOTIFY) \
	msg(INFY_SENSOR_NOTIFY) \
	msg(INFY_MOTION_NOTIFY) \
	msg(INFY_ALARM_NOTIFY) \
	msg(INFY_PND_NOTIFY) \
	msg(INFY_PND_RATE_NOTIFY) \
	msg(INFY_PND_HUB_NOTIFY) \
	msg(INFY_WAN_NOTIFY) \
	msg(INFY_DDNS_NOTIFY) \
	msg(INFY_WRITEFAIL_NOTIFY) \
	msg(INFY_EXHAUST_NOTIFY) \
	msg(INFY_NODISK_NOTIFY) \
	msg(INFY_SMART_WARN_NOTIFY) \
	msg(INFY_SYSFAN_NOTIFY) \
	msg(INFY_TEMPERATURE_NOTIFY) \
	msg(INFY_POE_NOTIFY) \
	msg(INFY_POE_HUB_NOTIFY) \
	msg(INFY_POE_PORT_NOTIFY) \
	msg(INFY_DVRLOGINFAIL_NOTIFY) \
	msg(INFY_NETLOGINFAIL_NOTIFY) \
	msg(INFY_NET_RXTX) \
	msg(INFY_AUDIOCH_NOTIFY) \
	msg(INFY_MICOUT_NOTIFY) \
	msg(INFY_BUZZER_NOTIFY) \
	msg(INFY_IP_CHANGED_NOTIFY) \
	msg(INFY_IPCAM_INSTALL_NOTIFY) \
	msg(INFY_VCA_EVENT_NOTIFY) \
	msg(INFY_VCA_TRACKINFO_NOTIFY) \
	msg(INFY_VCA_COUNTER_NOTIFY) \
	msg(INFY_VCA_META_DATA_NOTIFY) \
	msg(INFY_VCA_MODULAR_EVENT) \
	msg(INFY_REMOTE_S1_FWUP_NOTIFY) \
	msg(INFY_VCA_ANALYZE_NOTIFY) \
	msg(INFY_DETECT_POSDEV_NOTIFY) \
	msg(INFY_POS_STATUS_NOTIFY) \
    msg(INFY_DISK_RAID_CHANGE_STATUS_NOTIFY) \
    msg(INFY_POS_EVENT_NOTIFY) \
    msg(INFY_SET_IP_CONFLICT_NOTIFY) \
    msg(INFY_CAM_IP_CONFLICT_NOTIFY) \
	msg(INFY_DEEPLEARNING_OBJECT_NOTIFY) \
	msg(INFY_DEEPLEARNING_EVENT_NOTIFY) \
	msg(INFY_DEEPLEARNING_COUNTER_NOTIFY) \
	msg(INFY_DEEPLEARNING_MODULAR_EVENT) \
	msg(INFY_AI_EVENT_NOTIFY) \
	msg(INFY_AI_TRACKINFO_NOTIFY) \
	msg(INFY_AI_COUNTER_NOTIFY) \
	msg(INFY_AI_META_DATA_NOTIFY) \
	msg(INFY_AI_MODULAR_EVENT) \
	msg(INFY_AI_ANALYZE_NOTIFY) \
	msg(INFY_AI_FACE_EVENT_NOTIFY) \
	msg(INFY_AI_FACE_TRACKINFO_NOTIFY) \
	msg(INFY_AI_FACE_MODULAR_EVENT) \
	msg(INFY_AI_PLATENO_EVENT_NOTIFY) \
	msg(INFY_AI_PLATENO_TRACKINFO_NOTIFY) \
	msg(INFY_AI_PLATENO_MODULAR_EVENT) \
	msg(INFY_AI_GENERIC_EVENT_NOTIFY) \
	msg(INFY_AI_KEEP_ALIVE_NOTIFY) \
	msg(INFY_AIBOX_SETUP_CHANGE_NOTIFY) \
	msg(INFY_LONG_DISTANCE_NOTIFY) \
    msg(INFY_NFNOTIFY_GROUP_END)

#define IREQ_GROUP(msg) \
	msg(IREQ_CFRM_DATA_DELETE_FAIL) \
	msg(IREQ_CFRM_NODISK_DETECTED) \
	msg(IREQ_FORMAT_RATE) \
	msg(IREQ_FORMAT_ERROR) \
	msg(IREQ_BOOT_ERROR) \
	msg(IREQ_BOOT_NODISK) \
	msg(IREQ_BOOT_DISK_CONFLICT) \
	msg(IREQ_BOOT_DISK_ADDED) \
	msg(IREQ_BOOT_DISK_REMOVED) \
	msg(IREQ_BOOT_DISK_CHANGED) \
	msg(IREQ_BOOT_DISK_NEED_FORMAT) \
	msg(IREQ_BOOT_FORMAT_RCVR) \
	msg(IREQ_BOOT_ENFORCE_FORMAT) \
	msg(IREQ_BOOT_SMART_ERROR) \
    msg(IREQ_BOOT_SYSTEM_DISK_REMOVED) \
	msg(IREQ_FACTORY_DEFAULT) \
	msg(IREQ_UI_LOCK) \
	msg(IREQ_UI_UNLOCK) \
	msg(IREQ_CHANGE_LANG) \
	msg(IREQ_BOARD_CONFIRM) \
	msg(IREQ_CHANGE_ENHANCED_PASSWORD) \
	msg(IREQ_NET_FWUP) \
	msg(IREQ_DETECTED_NEWFW) \
	msg(IREQ_CHEAT_AUTO_FWUP) \
	msg(IREQ_OPENMODE_IPSETUP) \
	msg(IREQ_OPENMODE_PORTSETUP) \
	msg(IREQ_OPENMODE_CHANGE_PW) \
	msg(IREQ_S1_DETECTED_NEWFW) \
	msg(IREQ_S1_DETECTED_NEWCAMFW) \
	msg(IREQ_BOOT_BROKEN_RAID) \
	msg(IREQ_SCM_PREPARE_FWUP_IMAGESAVE) \
	msg(IREQ_SCM_128MB_FWUP_RESULT) \
	msg(IREQ_SCM_128MB_FWUP_RESULT_BY_WEB) \
	msg(IREQ_SCM_CONFIRM_FWUP_BY_WEB) \
	msg(IREQ_SCM_128MB_REMOTE_UPDATE_ALLINONE) \
	msg(IREQ_SCM_128MB_FWUP_RAMDISK_RESULT) \
	msg(IREQ_WIZARD_INIT)   \
	msg(IREQ_GROUP_END)

#define IRPL_GROUP(msg) \
	msg(IRPL_CFRM_DATA_DELETE_FAIL) \
	msg(IRPL_CFRM_UNC_ERROR_DETECTED) \
	msg(IRPL_CFRM_NODISK_DETECTED) \
	msg(IRPL_FORMAT_RATE) \
	msg(IRPL_FORMAT_ERROR) \
	msg(IRPL_BOOT_ERROR) \
	msg(IRPL_BOOT_NODISK) \
	msg(IRPL_BOOT_DISK_CONFLICT) \
	msg(IRPL_BOOT_DISK_ADDED) \
	msg(IRPL_BOOT_DISK_REMOVED) \
	msg(IRPL_BOOT_DISK_CHANGED) \
	msg(IRPL_BOOT_DISK_NEED_FORMAT) \
	msg(IRPL_BOOT_FORMAT_RCVR) \
	msg(IRPL_BOOT_ENFORCE_FORMAT) \
	msg(IRPL_BOOT_SMART_ERROR) \
	msg(IRPL_BOOT_SYSTEM_DISK_REMOVED) \
	msg(IRPL_TML_GET_DATA) \
	msg(IRPL_UI_LOCK) \
	msg(IRPL_UI_UNLOCK) \
	msg(IRPL_BOARD_CONFIRM) \
	msg(IRPL_CHANGE_ENHANCED_PASSWORD) \
	msg(IRPL_NET_FWUP) \
	msg(IRPL_DETECTED_NEWFW) \
	msg(IRPL_OPENMODE_IPSETUP) \
	msg(IRPL_OPENMODE_PORTSETUP) \
	msg(IRPL_OPENMODE_CHANGE_PW) \
	msg(IRPL_S1_DETECTED_NEWFW) \
	msg(IRPL_S1_DETECTED_NEWCAMFW) \
	msg(IRPL_BOOT_BROKEN_RAID) \
	msg(IRPL_SCM_PREPARE_FWUP_IMAGESAVE) \
	msg(IRPL_SCM_128MB_FWUP_RESULT) \
	msg(IRPL_SCM_128MB_FWUP_RESULT_BY_WEB) \
	msg(IRPL_SCM_CONFIRM_FWUP_BY_WEB) \
	msg(IRPL_SCM_128MB_REMOTE_UPDATE_ALLINONE) \
	msg(IRPL_SCM_128MB_FWUP_RAMDISK_RESULT) \
	msg(IRPL_WIZARD_INIT)   \
	msg(IRPL_GROUP_END)

#define IRET_GROUP(msg) \
	msg(IRET_SCM_UPGRADE_FW) \
	msg(IRET_SCM_CHANGE_SYSTEM_TIME) \
	msg(IRET_SCM_CHANGE_SYSTEM_TIME2) \
	msg(IRET_SCM_FORMAT_STORAGE) \
	msg(IRET_SCM_BOOTUP_SYSTEM) \
	msg(IRET_SCM_APPLY_NETINFO) \
	msg(IRET_SCM_APPLY_NETINFO2) \
	msg(IRET_FACTORY_DEFAULT_NOTIFY) \
	msg(IRET_SYSTEM_DATA_LOAD_NOTIFY) \
	msg(IRET_FWUP_CMPL) \
	msg(IRET_BOOTWND_OPENED) \
	msg(IRET_BOOTWND_CLOSED) \
	msg(IRET_ARCH_VERIFY) \
	msg(IRET_OPEN_ARCH_MANAGER) \
	msg(IRET_RESTART_SERVICE) \
	msg(IRET_SCM_GET_WANIP) \
	msg(IRET_SCM_REG_RTSP) \
	msg(IRET_SCM_RMV_RTSP) \
	msg(IRET_SCM_TST_RTSP) \
	msg(IRET_SCM_REG_WEB) \
	msg(IRET_SCM_RMV_WEB) \
	msg(IRET_SCM_TST_WEB) \
	msg(IRET_SCM_REG_DDNS) \
	msg(IRET_SCM_TST_DDNS) \
	msg(IRET_SCM_REG_UNIMO) \
	msg(IRET_SCM_SHUTDOWN) \
	msg(IRET_SCM_SHUTDOWN2) \
	msg(IRET_SCM_SHUTDOWN_CAM_CHANGE) \
	msg(IRET_SCM_SHUTDOWN_SIGNAL_CHANGE) \
	msg(IRET_SCM_ENTER_CAMUP_MODE) \
	msg(IRET_SCM_UPDATE_DESIGN) \
	msg(IRET_SCM_SHUTDOWN_SPOT_CHANGE)  \
	msg(IRET_SCM_SHUTDOWN_HD_SPOT_CHANGE) \
    msg(IRET_SCM_DUAL_MONITOR_CHANGE) \
	msg(IRET_SCM_DCONFIG_MODE) \
	msg(IRET_SCM_ERASE_CH) \
    msg(IRET_SCM_DHCP_RENEW) \
	msg(IRET_SCM_TST_FTP) \
	msg(IRET_SCM_UPGRADE_IPCAM_FW) \
	msg(IRET_DIAGNOSIS_POWER) \
	msg(IRET_DIAGNOSIS_NET) \
	msg(IRET_DIAGNOSIS_HDD) \
	msg(IRET_DIAGNOSIS_PORT) \
    msg(IRET_SCM_DISK_CREATE_RAID) \
	msg(IRET_SCM_DISK_DELETE_RAID) \
	msg(IRET_SCM_JMFW_UPDATE) \
	msg(IRET_SCM_GET_DISK_INFO) \
	msg(IRET_SCM_PREPARE_FWUP_VALIDATE) \
	msg(IRET_SCM_PREPARE_FWUP_DATABACKUP) \
	msg(IRET_SCM_PREPARE_FWUP_CMPL) \
	msg(IRET_SCM_SHUTDOWN_AUTHCODE) \
	msg(IRET_COMPLETED_GETTING_LICENSE) \
	msg(IRET_CAPTURE_NETWORK_MAP_SCREEN) \
    msg(IRET_NVM_UPDATE_CONN_STATUS) \
    msg(IRET_NVM_START_CAMERA_INSTALL) \
    msg(IRET_NVM_APPLY_CAMERA_SETTING) \
    msg(IRET_NVM_APPLY_AND_FINALIZE) \
    msg(IRET_SSL_INSTALL) \
    msg(IRET_SSL_DELETE) \
    msg(IRET_EXPORT_DEBUG_DATA) \
	msg(IRET_GROUP_END)

#define iRET_GROUP(msg) \
	msg(iRET_VFS_START_FS) \
	msg(iRET_VFS_STOP_FS) \
	msg(iRET_VFS_SET_RTL) \
	msg(iRET_VFS_DELETE_DATA) \
	msg(iRET_VFS_FORMAT_STORAGE) \
	msg(iRET_VFS_STOP_NET) \
	msg(iRET_VFS_START_NET) \
	msg(iRET_VFS_STOP_REC) \
	msg(iRET_VFS_START_REC) \
	msg(iRET_WRK_GET_WANIP) \
	msg(iRET_WRK_CHECK_UNC) \
	msg(iRET_WRK_REG_RTSP) \
	msg(iRET_WRK_RMV_RTSP) \
	msg(iRET_WRK_TST_RTSP) \
	msg(iRET_WRK_REG_WEB) \
	msg(iRET_WRK_RMV_WEB) \
	msg(iRET_WRK_TST_WEB) \
	msg(iRET_WRK_REG_DDNS) \
	msg(iRET_WRK_TST_DDNS) \
	msg(iRET_WRK_REG_UNIMO) \
	msg(iRET_WRK_GET_DDNS_STATUS) \
	msg(iRET_WRK_ENTER_DMODE) \
	msg(iRET_WRK_LEAVE_DMODE) \
	msg(iRET_NF_ARCH_DEV_SET_NOTIFY) \
	msg(iRET_NF_ARCH_DEV_GET_SIZE) \
	msg(iRET_FU_RUN_FW_UPGRADE) \
	msg(iRET_ACP_VERIFY_FILE) \
	msg(iRET_SMART_CHECK) \
	msg(iRET_SCM_CHANGE_SYSTEM_TIME) \
	msg(iRET_WRK_CAPTURE_IMAGE) \
	msg(iRET_VFS_ERASE_CH) \
	msg(iRET_WRK_TST_FTP) \
	msg(iRET_WRK_DIAGNOSIS) \
	msg(iRET_WRK_CAMFW_UPGD) \
    msg(iRET_VFS_BROKEN_RAID) \
	msg(iRET_WRK_CHECK_CABLE) \
	msg(iRET_WRK_GET_DISK_INFO) \
	msg(iRET_WRK_APPQC_TEST) \
	msg(iRET_WRK_PREPARE_FWUP) \
	msg(iRET_WRK_GET_LICENSE) \
    msg(iRET_WRK_EXPORT_DEBUG_DATA) \
	msg(iRET_GROUP_END)

#define iNFY_GROUP(msg) \
	msg(iNFY_FS_START_BEGIN) \
	msg(iNFY_FS_RECOVERY_BEGIN) \
	msg(iNFY_FS_RECOVERY_CMPL) \
	msg(iNFY_FS_STOP_BEGIN) \
	msg(iNFY_DATA_DELETE_BEGIN) \
	msg(iNFY_RTL_SET_BEGIN) \
	msg(iNFY_FORMAT_BEGIN) \
	msg(iNFY_EMAIL_SEND) \
	msg(iNFY_BOOTING_START) \
	msg(iNFY_VERIFY_RATE) \
	msg(iNFY_BOOKMARK_UNIT_QUERY) \
	msg(iNFY_BOOKMARK_WHOLE_QUERY) \
	msg(iNFY_REQUEST_QUERY) \
	msg(iNFY_BOOKMARK_MANUAL) \
	msg(iNFY_NF_FILESYSTEM_START) \
	msg(iNFY_NF_FILESYSTEM_SET_RTLIMIT) \
	msg(iNFY_NF_FILESYSTEM_DELETE_DATA) \
	msg(iNFY_NF_FILESYSTEM_STOP) \
	msg(iNFY_NF_DISK_FORMAT) \
	msg(iNFY_NFEVT) \
	msg(iNFY_RCVR_EXPIRED) \
	msg(iNFY_DISKINIT_START) \
	msg(iNFY_PRIVACY_BEGIN) \
	msg(iNFY_PRIVACY_CMPL) \
	msg(iNFY_NET_FWUP) \
	msg(iNFY_OPENMODE_IPSETUP) \
	msg(iNFY_OPENMODE_PORTSETUP) \
	msg(iNFY_OPENMODE_CHANGE_PW) \
	msg(iNFY_CAM_FWUP) \
    msg(iNFY_DISKRAID_CHECK) \
    msg(iNFY_ENHANCED_PASSWORD_CHECK) \
    msg(iNFY_128MB_FWUPGRADE_RESULT_CHECK) \
    msg(iNFY_WIZARD_CHECK)  \
	msg(iNFY_GROUP_END)

#define iREQ_GROUP(msg) \
	msg(iREQ_TML_GET_DATA) \
	msg(iREQ_WRK_WORK) \
	msg(iREQ_SPOT_CMD) \
	msg(iREQ_GROUP_END)

typedef enum _IMSG {
    IMSG_NONE = 0,

    INFY_GROUP_INIT = 0x1000,
    INFY_GROUP(DO_ENUM)

    INFY_NFNOTIFY_GROUP_INIT = INFY_NFNOTIFY_MIN,
    INFY_NFNOTIFY_GROUP(DO_ENUM)

    IREQ_GROUP_INIT = 0x2000,
    IREQ_GROUP(DO_ENUM)

    IRPL_GROUP_INIT = 0x4000,
    IRPL_GROUP(DO_ENUM)

    IRET_GROUP_INIT = 0x8000,
    IRET_GROUP(DO_ENUM)

    iRET_GROUP_INIT = 0x9000,
    iRET_GROUP(DO_ENUM)

    iNFY_GROUP_INIT = 0x10000,
    iNFY_GROUP(DO_ENUM)

    iREQ_GROUP_INIT = 0x20000,
    iREQ_GROUP(DO_ENUM)

} IMSG;

#endif
