#ifndef _NF_DAL_CONFIG_H_
#define _NF_DAL_CONFIG_H_

#define	STRING_SIZE_8		8
#define	STRING_SIZE_16		16
#define	STRING_SIZE_32		32
#define	STRING_SIZE_64		64
#define	STRING_SIZE_128		128
#define	STRING_SIZE_256		256

#define	STRING_SIZE_CAMTITLE	    (STRING_SIZE_64)
#define	STRING_SIZE_PRESETNAME	    (STRING_SIZE_64)
#define	STRING_SIZE_ALARMIN	        (STRING_SIZE_64)
#define	STRING_SIZE_ALARMOUT	    (STRING_SIZE_64)

#endif


