################################################################################
## do not modify if u don't have 'dvsdk' 'kernel' in ur local root fs.
################################################################################
TARGET_ROOT ?= /home/$(USER)/filesys_ipx
NFDVR ?= $(TARGET_ROOT)/NFDVR
KERNEL_PATH = /home/choissi/ipx/ipx_kernel_ea13

################################################################################
## SYSTEM CFG.
################################################################################
RULES_MACRO += -DENABLE_WATCHDOG
RULES_MACRO += -DENABLE_WATCHDOG_HW_ON
RULES_MACRO += -DENABLE_WATCHDOG_SOFT_RESET

RULES_MACRO += -DENABLE_RTSP_ENCRYPTION

################################################################################
## MODEL CFG.
################################################################################
RULES_MACRO += -D$(TARGET_MODEL)
RULES_MACRO += -D$(TARGET_VENDOR)
# refactoring
RULES_MACRO += -D_NVR_MODEL
RULES_MACRO += -D_SNF_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DSUPPORT_VCA_CAMERA
#RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
RULES_MACRO += -DSUPPORT_UBIFS

ifeq ($(TARGET_MODEL),_SNF_1648)
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_16CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF 
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
#RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
endif

ifeq ($(TARGET_MODEL),_SNF_0824)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
#RULES_MACRO += -DGUI_4CH_SUPPORT
RULES_MACRO += -DGUI_8CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF 
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -D_IPCAM_COMP_MOTION
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -D_IPX_0824L
RULES_MACRO += -D_ADMIN_IPX_0824
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
endif

ifeq ($(TARGET_MODEL),_SNF_0424)
RULES_MACRO += -D_NVR_MODEL
RULES_MACRO += -D__NOT_READY_BS8418__
RULES_MACRO += -DGUI_4CH_SUPPORT
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF 
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -D_ADMIN_IPX_0412
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
endif

ifeq ($(TARGET_MODEL),_IPX_1648P)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_16CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SNF_1648
RULES_MACRO += -DENABLE_PRO_MODEL
RULES_MACRO += -D_SUPPORT_HUB
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -D_ADMIN_IPX_1648P
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
endif

ifeq ($(TARGET_MODEL),_IPX_0824P)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
#RULES_MACRO += -DGUI_4CH_SUPPORT
RULES_MACRO += -DGUI_8CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SNF_0824
RULES_MACRO += -DENABLE_PRO_MODEL
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -D_ADMIN_IPX_0824P
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
endif

ifeq ($(TARGET_MODEL),_HDI_0412)
RULES_MACRO += -D__NOT_READY_BS8418__
RULES_MACRO += -DGUI_4CH_SUPPORT
RULES_MACRO += -D_HDI_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF 
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_HDI
endif

ifeq ($(TARGET_MODEL),_IPX_0412VE)
RULES_MACRO += -D_NVR_MODEL
RULES_MACRO += -D__NOT_READY_BS8418__
RULES_MACRO += -DGUI_4CH_SUPPORT
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF 
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
RULES_MACRO += -D_IPXVE_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -D_ADMIN_IPX_0412VE
RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
endif

ifeq ($(TARGET_MODEL),_IPX_0824VE)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
#RULES_MACRO += -DGUI_4CH_SUPPORT
RULES_MACRO += -DGUI_8CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF 
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
RULES_MACRO += -D_IPXVE_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -D_IPCAM_COMP_MOTION
RULES_MACRO += -D_ADMIN_IPX_0824VE
RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
endif

ifeq ($(TARGET_MODEL),_IPX_0412VE3)
RULES_MACRO += -D_NVR_MODEL
RULES_MACRO += -D__NOT_READY_BS8418__
RULES_MACRO += -DGUI_4CH_SUPPORT
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF 
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_0412VE
RULES_MACRO += -D_NOT_SUPPORT_VCT_WAN_LAN
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -D_KERNEL_HI3535
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
endif

ifeq ($(TARGET_MODEL),_IPX_0824VE3)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
#RULES_MACRO += -DGUI_4CH_SUPPORT
RULES_MACRO += -DGUI_8CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF 
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -D_IPCAM_COMP_MOTION
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -D_IPX_0824L
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_0824VE
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_WIN_SWITCH
RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -D_KERNEL_HI3535
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
RULES_MACRO += -D_NOT_SUPPORT_VCT_WAN_LAN
endif

ifeq ($(TARGET_MODEL),_IPX_1648VE3)
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_16CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF 
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
#RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_HUB
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_1648VE
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -D_KERNEL_HI3535
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
RULES_MACRO += -D_NOT_SUPPORT_VCT_WAN_LAN
endif

ifeq ($(TARGET_MODEL),_IPX_0824P3)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
#RULES_MACRO += -DGUI_4CH_SUPPORT
RULES_MACRO += -DGUI_8CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -DENABLE_PRO_MODEL
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_0824P3
#RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -D_KERNEL_HI3535
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
RULES_MACRO += -D_IPX_MULTI_SWITCH
RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
RULES_MACRO += -DENABLE_SW_FAN_CTRL
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
endif

ifeq ($(TARGET_MODEL),_IPX_1648P3)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_16CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -DENABLE_PRO_MODEL
RULES_MACRO += -D_SUPPORT_HUB
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_1648P3
#RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -D_KERNEL_HI3535
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
RULES_MACRO += -D_IPX_MULTI_SWITCH
RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
RULES_MACRO += -DENABLE_SW_FAN_CTRL
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
endif

ifeq ($(TARGET_MODEL),_IPX_0824P3ECO)
RULES_MACRO += -DGUI_8CH_SUPPORT
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_0824P3ECO
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
#RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -D_KERNEL_HI3535
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
RULES_MACRO += -D_DEFAULT_UX_OPENMODE
RULES_MACRO += -DENABLE_SW_FAN_CTRL
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
RULES_MACRO += -D_NOT_SUPPORT_POECHECK
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
endif

ifeq ($(TARGET_MODEL),_IPX_1648P3ECO)
RULES_MACRO += -DGUI_16CH_SUPPORT
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_1648P3ECO
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
#RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -D_KERNEL_HI3535
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
RULES_MACRO += -D_DEFAULT_UX_OPENMODE
RULES_MACRO += -DENABLE_SW_FAN_CTRL
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
RULES_MACRO += -D_NOT_SUPPORT_POECHECK
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
endif

ifeq ($(TARGET_MODEL),_IPX_0412ECO)
RULES_MACRO += -D_NVR_MODEL
RULES_MACRO += -D__NOT_READY_BS8418__
RULES_MACRO += -DGUI_4CH_SUPPORT
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF 
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
RULES_MACRO += -D_IPXVE_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -D_ADMIN_IPX_0412ECO
RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -D_DEFAULT_UX_OPENMODE
RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -D_NOT_SUPPORT_POECHECK
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
endif

ifeq ($(TARGET_MODEL),_IPX_0824ECO)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
#RULES_MACRO += -DGUI_4CH_SUPPORT
RULES_MACRO += -DGUI_8CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF 
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
RULES_MACRO += -D_IPXVE_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -D_IPCAM_COMP_MOTION
RULES_MACRO += -D_ADMIN_IPX_0824ECO
RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -D_DEFAULT_UX_OPENMODE
RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -D_NOT_SUPPORT_POECHECK
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
endif

ifeq ($(TARGET_MODEL),_IPX_0824P4)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
#RULES_MACRO += -DGUI_4CH_SUPPORT
RULES_MACRO += -DGUI_8CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -DENABLE_PRO_MODEL
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_0824P4
#RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -D_KERNEL_HI3536
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
RULES_MACRO += -D_IPX_MULTI_SWITCH
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
RULES_MACRO += -DENABLE_SW_FAN_CTRL
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
endif

ifeq ($(TARGET_MODEL),_IPX_1648P4)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_16CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -DENABLE_PRO_MODEL
RULES_MACRO += -D_SUPPORT_HUB
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_1648P4
#RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -D_KERNEL_HI3536
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
RULES_MACRO += -D_IPX_MULTI_SWITCH
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
RULES_MACRO += -DENABLE_SW_FAN_CTRL
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
endif

ifeq ($(TARGET_MODEL),_IPX_1648L4)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_16CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPX
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_HUB
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_1648VE
#RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -D_KERNEL_HI3536
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
RULES_MACRO += -DENABLE_SW_FAN_CTRL
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
endif

ifeq ($(TARGET_MODEL),_IPX_0824L4)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_8CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_HUB
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_0824VE
#RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -D_KERNEL_HI3536
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
RULES_MACRO += -DENABLE_SW_FAN_CTRL
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
endif

ifeq ($(TARGET_MODEL),_IPX_0412L4)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_4CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_HUB
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_0412VE
#RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -D_KERNEL_HI3536
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
RULES_MACRO += -DENABLE_SW_FAN_CTRL
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
endif

ifeq ($(TARGET_MODEL),_IPX_1648M4E)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_16CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_1648M4E
RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
#RULES_MACRO += -DENABLE_REC_LIVE_AUDIO
RULES_MACRO += -DENABLE_AI_ALARM_AUDIO_HICHIP
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
RULES_MACRO += -D_NOT_SUPPORT_TEMPERCHECK
RULES_MACRO += -DSUPPORT_FS_UBIFS
RULES_MACRO += -DSUPPORT_NAND_256M
RULES_MACRO += -DSUPPORT_NAND_SINGLE_PARTITION
RULES_MACRO += -DENABLE_CLASSIFY_BOARD_TYPE
RULES_MACRO += -DSCHIP_COPY_PROTECTION
RULES_MACRO += -D_NO_EXT_DISK
RULES_MACRO += -DDUAL_LAN_NETWORK
RULES_MACRO += -D_SUPPORT_FORGOT_PASSWORD
RULES_MACRO += -D_SUPPORT_HUB
#RULES_MACRO += -D_SUPPORT_POE_TR_MODE
endif

ifeq ($(TARGET_MODEL),_IPX_0824M4E)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_8CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_0824M4E
RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
#RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
#RULES_MACRO += -DENABLE_REC_LIVE_AUDIO
RULES_MACRO += -DENABLE_AI_ALARM_AUDIO_DSP
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
RULES_MACRO += -D_NOT_SUPPORT_TEMPERCHECK
RULES_MACRO += -DSUPPORT_FS_UBIFS
RULES_MACRO += -DSUPPORT_NAND_256M
RULES_MACRO += -DSUPPORT_NAND_SINGLE_PARTITION
RULES_MACRO += -DENABLE_CLASSIFY_BOARD_TYPE
RULES_MACRO += -DSCHIP_COPY_PROTECTION
RULES_MACRO += -D_NO_EXT_DISK
RULES_MACRO += -D_SUPPORT_FORGOT_PASSWORD
#RULES_MACRO += -D_SUPPORT_POE_TR_MODE
endif

ifeq ($(TARGET_MODEL),_IPX_0412M4E)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_4CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_0412M4E
RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
#RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
#RULES_MACRO += -DENABLE_REC_LIVE_AUDIO
RULES_MACRO += -DENABLE_AI_ALARM_AUDIO_DSP
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
RULES_MACRO += -D_NOT_SUPPORT_TEMPERCHECK
RULES_MACRO += -DSUPPORT_FS_UBIFS
RULES_MACRO += -DSUPPORT_NAND_256M
RULES_MACRO += -DSUPPORT_NAND_SINGLE_PARTITION
RULES_MACRO += -DENABLE_CLASSIFY_BOARD_TYPE
RULES_MACRO += -DSCHIP_COPY_PROTECTION
RULES_MACRO += -D_NOT_SUPPORT_SPC_DIV
RULES_MACRO += -D_NO_EXT_DISK
RULES_MACRO += -D_SUPPORT_FORGOT_PASSWORD
#RULES_MACRO += -D_SUPPORT_POE_TR_MODE
endif

ifeq ($(TARGET_MODEL),_IPX_1648M4)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_16CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_1648M4
RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
#RULES_MACRO += -DENABLE_REC_LIVE_AUDIO
RULES_MACRO += -DENABLE_AI_ALARM_AUDIO_HICHIP
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
RULES_MACRO += -D_NOT_SUPPORT_TEMPERCHECK
RULES_MACRO += -DSUPPORT_FS_UBIFS
RULES_MACRO += -DSUPPORT_NAND_256M
RULES_MACRO += -DSUPPORT_NAND_SINGLE_PARTITION
RULES_MACRO += -DENABLE_CLASSIFY_BOARD_TYPE
RULES_MACRO += -DSCHIP_COPY_PROTECTION
RULES_MACRO += -D_NO_EXT_DISK
RULES_MACRO += -DDUAL_LAN_NETWORK
RULES_MACRO += -D_SUPPORT_FORGOT_PASSWORD
RULES_MACRO += -D_SUPPORT_HUB
endif

ifeq ($(TARGET_MODEL),_IPX_0824M4)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_8CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_0824M4
RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
#RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
#RULES_MACRO += -DENABLE_REC_LIVE_AUDIO
RULES_MACRO += -DENABLE_AI_ALARM_AUDIO_DSP
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
RULES_MACRO += -D_NOT_SUPPORT_TEMPERCHECK
RULES_MACRO += -DSUPPORT_FS_UBIFS
RULES_MACRO += -DSUPPORT_NAND_256M
RULES_MACRO += -DSUPPORT_NAND_SINGLE_PARTITION
RULES_MACRO += -DENABLE_CLASSIFY_BOARD_TYPE
RULES_MACRO += -DSCHIP_COPY_PROTECTION
RULES_MACRO += -D_NO_EXT_DISK
RULES_MACRO += -D_SUPPORT_FORGOT_PASSWORD
endif

ifeq ($(TARGET_MODEL),_IPX_0412M4)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_4CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_0412M4
RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
#RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
#RULES_MACRO += -DENABLE_REC_LIVE_AUDIO
RULES_MACRO += -DENABLE_AI_ALARM_AUDIO_DSP
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
RULES_MACRO += -D_NOT_SUPPORT_TEMPERCHECK
RULES_MACRO += -DSUPPORT_FS_UBIFS
RULES_MACRO += -DSUPPORT_NAND_256M
RULES_MACRO += -DSUPPORT_NAND_SINGLE_PARTITION
RULES_MACRO += -DENABLE_CLASSIFY_BOARD_TYPE
RULES_MACRO += -DSCHIP_COPY_PROTECTION
RULES_MACRO += -D_NOT_SUPPORT_SPC_DIV
RULES_MACRO += -D_NO_EXT_DISK
RULES_MACRO += -D_SUPPORT_FORGOT_PASSWORD
endif

ifeq ($(TARGET_MODEL),_IPX_0824P4E)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_16CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_0824P4E
#RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
#RULES_MACRO += -DENABLE_REC_LIVE_AUDIO
#RULES_MACRO += -DENABLE_SW_FAN_CTRL
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
RULES_MACRO += -DENABLE_AI_ALARM_AUDIO_HICHIP
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
#RULES_MACRO += -D_NOT_SUPPORT_TEMPERCHECK
RULES_MACRO += -DSUPPORT_FS_UBIFS
RULES_MACRO += -DSUPPORT_NAND_256M
RULES_MACRO += -DSUPPORT_NAND_SINGLE_PARTITION
#RULES_MACRO += -DENABLE_CLASSIFY_BOARD_TYPE
#RULES_MACRO += -DSCHIP_COPY_PROTECTION
#RULES_MACRO += -D_NO_EXT_DISK
RULES_MACRO += -DDUAL_LAN_NETWORK
RULES_MACRO += -D_SUPPORT_FORGOT_PASSWORD
RULES_MACRO += -D_SUPPORT_HUB
#RULES_MACRO += -D_SUPPORT_POE_TR_MODE
endif

ifeq ($(TARGET_MODEL),_IPX_1648P4E)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_16CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_1648P4E
#RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
#RULES_MACRO += -DENABLE_REC_LIVE_AUDIO
#RULES_MACRO += -DENABLE_SW_FAN_CTRL
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
RULES_MACRO += -DENABLE_AI_ALARM_AUDIO_HICHIP
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
#RULES_MACRO += -D_NOT_SUPPORT_TEMPERCHECK
RULES_MACRO += -DSUPPORT_FS_UBIFS
RULES_MACRO += -DSUPPORT_NAND_256M
RULES_MACRO += -DSUPPORT_NAND_SINGLE_PARTITION
#RULES_MACRO += -DENABLE_CLASSIFY_BOARD_TYPE
#RULES_MACRO += -DSCHIP_COPY_PROTECTION
#RULES_MACRO += -D_NO_EXT_DISK
RULES_MACRO += -DDUAL_LAN_NETWORK
RULES_MACRO += -D_SUPPORT_FORGOT_PASSWORD
RULES_MACRO += -D_SUPPORT_HUB
#RULES_MACRO += -D_SUPPORT_POE_TR_MODE
endif

ifeq ($(TARGET_MODEL),_IPX_32P4E)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_32CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_32P4E
#RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
#RULES_MACRO += -DENABLE_REC_LIVE_AUDIO
#RULES_MACRO += -DENABLE_SW_FAN_CTRL
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
RULES_MACRO += -DENABLE_AI_ALARM_AUDIO_HICHIP
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
#RULES_MACRO += -D_NOT_SUPPORT_TEMPERCHECK
RULES_MACRO += -DSUPPORT_FS_UBIFS
RULES_MACRO += -DSUPPORT_NAND_256M
RULES_MACRO += -DSUPPORT_NAND_SINGLE_PARTITION
#RULES_MACRO += -DENABLE_CLASSIFY_BOARD_TYPE
#RULES_MACRO += -DSCHIP_COPY_PROTECTION
#RULES_MACRO += -D_NO_EXT_DISK
RULES_MACRO += -DDUAL_LAN_NETWORK
RULES_MACRO += -D_SUPPORT_FORGOT_PASSWORD
RULES_MACRO += -D_IPX_3296P4
#RULES_MACRO += -D_SUPPORT_POE_TR_MODE
endif

ifeq ($(TARGET_MODEL),_IPX_32M4E)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_32CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_32M4E
RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
#RULES_MACRO += -DENABLE_REC_LIVE_AUDIO
#RULES_MACRO += -DENABLE_SW_FAN_CTRL
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
RULES_MACRO += -DENABLE_AI_ALARM_AUDIO_HICHIP
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
RULES_MACRO += -D_NOT_SUPPORT_TEMPERCHECK
RULES_MACRO += -DSUPPORT_FS_UBIFS
RULES_MACRO += -DSUPPORT_NAND_256M
RULES_MACRO += -DSUPPORT_NAND_SINGLE_PARTITION
#RULES_MACRO += -DENABLE_CLASSIFY_BOARD_TYPE
#RULES_MACRO += -DSCHIP_COPY_PROTECTION
#RULES_MACRO += -D_NO_EXT_DISK
RULES_MACRO += -DDUAL_LAN_NETWORK
RULES_MACRO += -D_SUPPORT_FORGOT_PASSWORD
RULES_MACRO += -D_IPX_3296P4
#RULES_MACRO += -D_SUPPORT_POE_TR_MODE
endif

# NOVATEK NT98336
ifeq ($(TARGET_MODEL),_IPX_32P5)
RULES_MACRO += -D_NVR_MODEL
RULES_MACRO += -DCHIP_NVT
RULES_MACRO += -DCHIP_NVT_NT9833x
#RULES_MACRO += -DENABLE_AUDIO_HANDOFF_VLC
RULES_MACRO += -DENABLE_ARCH_A64
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_32CH_SUPPORT
RULES_MACRO += -D__ITXGUI64
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_FAN_FAIL_CHECK
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
#RULES_MACRO += -DENABLE_MICOM_UPGRADE
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_32M4E
#RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
#RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
#RULES_MACRO += -DENABLE_REC_LIVE_AUDIO
#RULES_MACRO += -DENABLE_SW_FAN_CTRL
#RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
#RULES_MACRO += -DENABLE_AI_ALARM_AUDIO_HICHIP
RULES_MACRO += -DENABLE_AI_ALARM_AUDIO
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
#RULES_MACRO += -D_SUPPORT_DISP_HISILICON
#RULES_MACRO += -D_NOT_SUPPORT_TEMPERCHECK
RULES_MACRO += -DSUPPORT_UBIFS
#RULES_MACRO += -DSUPPORT_NAND_512M
RULES_MACRO += -DSUPPORT_NAND_256M
#RULES_MACRO += -DSUPPORT_NAND_128M
RULES_MACRO += -DSUPPORT_STORAGE_NAND
RULES_MACRO += -DCONFIG_FWUPGRADE_SINGLE
#RULES_MACRO += -DENABLE_CLASSIFY_BOARD_TYPE
RULES_MACRO += -DSCHIP_COPY_PROTECTION
RULES_MACRO += -D_NO_EXT_DISK
RULES_MACRO += -DDUAL_LAN_NETWORK
RULES_MACRO += -D_SUPPORT_FORGOT_PASSWORD
RULES_MACRO += -DENABLE_DISPLAY_2160P
RULES_MACRO += -D_IPX_3296P5
#RULES_MACRO += -D_SUPPORT_POE_TR_MODE
endif

ifeq ($(TARGET_MODEL),_IPX_16P5)
RULES_MACRO += -D_NVR_MODEL
#RULES_MACRO += -D_RIP_FORCE_ASSIGN
#RULES_MACRO += -D__SUPPORT_BS8418__
RULES_MACRO += -D__NOT_READY_BS8418__
#RULES_MACRO += -D_UPNP_SUPPORT_
#RULES_MACRO += -D_DDNS2_GUI_SUPPORT_
RULES_MACRO += -DGUI_32CH_SUPPORT
#RULES_MACRO += -D_SUPPORT_CAPTURE_FB
RULES_MACRO += -D_SNF_MODEL
RULES_MACRO += -D_CURSOR_DISPLAY_ONOFF
RULES_MACRO += -D__USE_PNG_IMAGE_
#RULES_MACRO += -D__SUPPORT_POS__
RULES_MACRO += -DUSE_RTSP_AUTH
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_CFLAGS += -DENABLE_SENSOR_IPCAM
RULES_MACRO += -D_IPX_MODEL_UX
#RULES_MACRO += -DUSE_RTSP4VLC
#RULES_MACRO += -D__I_FRAME_RESEND__
#RULES_MACRO += -DUSE_MCAST
#RULES_MACRO += -DUSE_SENDTO
#RULES_MACRO += -DUSE_RTSP_AUTH_VLC
RULES_MACRO += -D_SUPPORT_SNAPSHOT
RULES_MACRO += -D_SUPPORT_LOGIN_AUTOHIDE
RULES_MACRO += -D_SUPPORT_ABNORMAL_LOGIN
RULES_MACRO += -D_FIXED_POE_POWER_LIMIT
RULES_MACRO += -D_SUPPORT_GUI_MDRAW
RULES_MACRO += -D_SUPPORT_EVENT_PRESET
RULES_MACRO += -D_PTZ_2STREAM_FPS_LIMIT
RULES_MACRO += -DENABLE_ACTION_PTZ_PRESET
RULES_MACRO += -DENABLE_ACTION_MOBILE
RULES_MACRO += -DENABLE_ACTION_PUSH
RULES_MACRO += -DSUPPORT_VCA_CAMERA
RULES_MACRO += -D_SUPPORT_IPCAM_FWUP
#RULES_MACRO += -D_SUPPORT_DUALMONITOR
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -DSUPPORT_DISK_RAID
RULES_CFLAGS += -DNMF_MODEL_IPXVE
RULES_MACRO += -D_IPXVE_MODEL_UX
RULES_MACRO += -D_ADMIN_IPX_32P4E
#RULES_MACRO += -D_NOT_SUPPORT_FANCHECK
RULES_MACRO += -DENABLE_AUD_HI_CHIP
RULES_MACRO += -D_IPCAM_BITRATE_STEP1
#RULES_MACRO += -DENABLE_REC_LIVE_AUDIO
#RULES_MACRO += -DENABLE_SW_FAN_CTRL
RULES_MACRO += -DENABLE_REC_LIVE_AUDIO_HI
RULES_MACRO += -DENABLE_AI_ALARM_AUDIO_HICHIP
#RULES_MACRO += -D_SUPPORT_ARCH_POS_LOG
#RULES_MACRO += -D_SCREEN_CAPTURE_
RULES_MACRO += -D_NOT_SUPPORT_NO_NC
RULES_MACRO += -D_SUPPORT_DISP_HISILICON
#RULES_MACRO += -D_NOT_SUPPORT_TEMPERCHECK
RULES_MACRO += -DSUPPORT_FS_UBIFS
RULES_MACRO += -DSUPPORT_NAND_256M
RULES_MACRO += -DSUPPORT_NAND_SINGLE_PARTITION
#RULES_MACRO += -DENABLE_CLASSIFY_BOARD_TYPE
#RULES_MACRO += -DSCHIP_COPY_PROTECTION
#RULES_MACRO += -D_NO_EXT_DISK
RULES_MACRO += -DDUAL_LAN_NETWORK
RULES_MACRO += -D_SUPPORT_FORGOT_PASSWORD
RULES_MACRO += -D_IPX_3296P4
#RULES_MACRO += -D_SUPPORT_POE_TR_MODE
endif

RULES_MACRO += -DENABLE_ONVIF_DEVICE
#RULES_MACRO += -D_ONVIF_STAND_ALONE

################################################################################
## UI type, Vendor specific option.
################################################################################

ifeq ($(TARGET_VENDOR),ITX)
RULES_MACRO += -D_ZICOM_STRING_FIX
endif

ifeq ($(TARGET_VENDOR),ZICOM)
RULES_MACRO += -D_ZICOM_STRING_FIX
RULES_MACRO += -D_SEQURINET_STRING_FIX
endif

ifeq ($(TARGET_VENDOR),ITX_A)
endif

ifeq ($(TARGET_VENDOR),ITX_B)
endif

ifeq ($(TARGET_VENDOR),CBC)
RULES_MACRO += -D_ADMIN_CBC
endif

ifeq ($(TARGET_VENDOR),VICON)
RULES_MACRO += -D_ADMIN_VICON
endif

ifeq ($(TARGET_VENDOR),XRPLUS)
endif

ifeq ($(TARGET_VENDOR),SAMSUNG)
endif

ifeq ($(TARGET_VENDOR),I3DVR)
endif

ifeq ($(TARGET_VENDOR),ITX)
endif

ifeq ($(TARGET_VENDOR),ITX_C)
endif

ifeq ($(TARGET_VENDOR),MACE)
endif

ifeq ($(TARGET_VENDOR),HONEYWELL)
endif

ifeq ($(TARGET_VENDOR),ITX_D)
endif

ifeq ($(TARGET_VENDOR),ORION)
endif

ifeq ($(TARGET_VENDOR),LOREX)
endif

ifeq ($(TARGET_VENDOR),SEATLE)
endif

ifeq ($(TARGET_VENDOR),DIGIMERGE)
endif

ifeq ($(TARGET_VENDOR),STL)
endif

ifeq ($(TARGET_VENDOR),ABUS)
endif

ifeq ($(TARGET_VENDOR),KODO)
endif

ifeq ($(TARGET_VENDOR),NOVUS)
endif

ifeq ($(TARGET_VENDOR),OTM)
endif

ifeq ($(TARGET_VENDOR),KMW)
#RULES_MACRO += -DENABLE_PROJECT_KMW
endif

ifeq ($(TARGET_VENDOR),S1)
ifeq ($(TARGET_MODEL),_IPX_1648P)
RULES_MACRO += -D_IPX_MULTI_SWITCH
RULES_MACRO += -DIPX_1648P_S1
endif
RULES_MACRO += -D_SUPPORT_FORGOT_PASSWORD
RULES_MACRO += -D_SUPPORT_USER_PHONE
RULES_MACRO += -D_SUPPORT_PRESERVE_SET_TIME
RULES_MACRO += -D_SUPPORT_PB_SYMBOL_DISPLAY
RULES_MACRO += -D_SUPPORT_SELF_DIAGNOSIS
RULES_MACRO += -D_SUPPORT_NETWORK_WIZARD
RULES_MACRO += -D_SUPPORT_REMOTE_UPGRADE
RULES_MACRO += -DENABLE_NET_FW_S1_SCENARIO
RULES_MACRO += -DENABLE_S1_DDNS_SCENARIO
RULES_MACRO += -DENABLE_S1_UPNP_SCENARIO
endif

ifeq ($(TARGET_VENDOR),S1)
ifeq ($(TARGET_MODEL),_IPX_0824P)
RULES_MACRO += -DIPX_0824P_S1
endif
endif

ifeq ($(TARGET_VENDOR),S1_JAPAN)
ifeq ($(TARGET_MODEL),_IPX_1648P)
RULES_MACRO += -D_IPX_MULTI_SWITCH
RULES_MACRO += -DIPX_1648P_S1
endif
RULES_MACRO += -D_SUPPORT_FORGOT_PASSWORD
RULES_MACRO += -D_SUPPORT_USER_PHONE
RULES_MACRO += -D_SUPPORT_PRESERVE_SET_TIME
endif

ifeq ($(TARGET_VENDOR),IPCAM_ZIG)
RULES_MACRO += -DENABLE_IPCAM_ZIG
RULES_MACRO += -DDBG_TEXT_ENABLE
endif

ifeq ($(TARGET_VENDOR),VIDECON)
RULES_MACRO += -DVIDECON
RULES_MACRO += -D_SUPPORT_DUAL_SMTPSERVER
RULES_MACRO += -DENABLE_EMAIL_DUAL_SERVER
endif

ifeq ($(TARGET_VENDOR),VIDECON_US)
RULES_MACRO += -DVIDECON_US
RULES_MACRO += -D_SUPPORT_DUAL_SMTPSERVER
RULES_MACRO += -DENABLE_EMAIL_DUAL_SERVER
endif

ifeq ($(TARGET_VENDOR),DAYOU)
RULES_MACRO += -DDAYOU
endif

################################################################################
## OPTION CFG. (UI OPTION) dependency vw_desc.c
################################################################################
ifeq ($(TARGET_OPTION),VA)
#VA
RULES_MACRO += -D_SUPPORT_DMVA
#DEEPLEARNING
RULES_MACRO += -D_SUPPORT_DLVA
RULES_MACRO += -D_SUPPORT_AICAM
RULES_MACRO += -D_SUPPORT_AIBOX
endif

ifeq ($(TARGET_NABTO),NABTO)
#NABTO
RULES_MACRO += -DENABLE_NABTO
endif

################################################################################
## OPTION CFG (HW TEST FW & SWG TEST FW)
################################################################################
#RULES_MACRO += -DDEBUG_ENABLE_JBSHELL
#RULES_MACRO += -DDEBUG_ENABLE_ZABBIX_TELNET


################################################################################
## build option. modify as u wish...
################################################################################
#RULES_MACRO += -DDEBUG_RAND_ALARM
#RULES_MACRO += -DDEBUG_SIMPLE_NF               # no init fs,live,play
#RULES_MACRO += -DDEBUG_SIMPLE_PASSWD
#RULES_MACRO += -DDEBUG_NETIF_STAT
#RULES_MACRO += -DDEBUG_REC_GOP_STAT
#RULES_MACRO += -DDEBUG_MONITOR_STAT

#RULES_MACRO += -DENABLE_HNF_IPCAM
#RULES_MACRO += -DENABLE_HNF_IPCAM_RECORD

#RULES_MACRO += -DDEBUG_DUMMY_GMAINLOOP
#RULES_MACRO += -DDEBUG_UI_POPUP_DISABLE
#RULES_MACRO += -DDEBUG_SYSDB_ALWAYS_DEFAULT

RULES_CFLAGS += 
RULES_INCDIR += 

RULES_LDFLAGS +=   
RULES_LIBS += 
RULES_LIBDIR +=
