/* set tabspace4 */
/**
 * @file nf_api_ipcam.h
 * @brief IP카메라 관련 API header.
 * @author Jae-young Kim
 * @date 03/03/2011
 * @copyright (c) COPYRIGHT 2010 ITXSecurity\n
 * ALL RIGHT RESERVED
 */

#ifndef __NF_API_IPCAM_H__
#define __NF_API_IPCAM_H__

#include <glib.h>
// #include <gst/gst.h>

#include "nf_common.h"
#include <inttypes.h>

/** @def SUPPORT_3RD_STREAM
 *  @brief 카메라의 3rd stream 지원 여부.(미구현)
 */
#define SUPPORT_3RD_STREAM (0)

/** @def MAX_ROI_AREA
 *  @brief 카메라에서 설정가능한 ROI 영역 최대 갯수.
 */
#define MAX_ROI_AREA (10)

/** @def MAX_MOTION_AREA
 *  @brief 카메라에서 설정가능한 motion영역 최대 갯수.
 */
#define MAX_MOTION_AREA (10)
#define MAX_AI_MOTION (15)

#define CAM_ZIG_MODE	(1)

/**
 * @def  MAX_AUXILIARY_COMMANDS
 * @brief ONVIF 카메라에서지원하는 AUXILIARY 최대 명령 수.
 */
#define MAX_AUXILIARY_COMMANDS	(16)

#define D_SECS(a) ((a).tv_sec),(((a).tv_nsec)/1000/1000)
#define IPCAM_DBG_ERROR(fmt, ...) \
do { \
	struct timespec a; \
	clock_gettime(CLOCK_REALTIME, &a); \
	printf("CAMGR [%lu.%03lu] %s:%d [%s] \033[0;1;40;31mERROR \033[0m| " fmt, \
			D_SECS(a), __FILE__, __LINE__, __FUNCTION__, ##__VA_ARGS__); \
} while (0)
#define IPCAM_DBG_WARN(fmt, ...) \
do { \
	struct timespec a; \
	clock_gettime(CLOCK_REALTIME, &a); \
	printf("CAMGR [%lu.%03lu] %s:%d [%s] \033[0;1;40;33mWARN \033[0m| " fmt, \
			D_SECS(a), __FILE__, __LINE__, __FUNCTION__, ##__VA_ARGS__); \
} while (0)
#define IPCAM_DBG_MAJOR(fmt, ...) \
do { \
	struct timespec a; \
	clock_gettime(CLOCK_REALTIME, &a); \
	printf("CAMGR [%lu.%03lu] [%s] " fmt, \
			D_SECS(a), __FUNCTION__, ##__VA_ARGS__); \
} while (0)
#define IPCAM_DBG_MINOR(fmt, ...) \
do { \
	struct timespec a; \
	clock_gettime(CLOCK_REALTIME, &a); \
	printf("CAMGR [%lu.%03lu] [%s] " fmt, \
			D_SECS(a), __FUNCTION__, ##__VA_ARGS__); \
} while (0)

#define IPCAM_DBG(level, fmt, ...) if (0) \
do { \
	IPCAM_DBG_##level(fmt, ##__VA_ARGS__); \
} while (0)

/**  uint64_t 
 * @brief 64bit Shift Data
 */

#define SHIFT_64_00	0x0000000000000001LL
#define SHIFT_64_01	0x0000000000000002LL
#define SHIFT_64_02	0x0000000000000004LL
#define SHIFT_64_03	0x0000000000000008LL
#define SHIFT_64_04	0x0000000000000010LL
#define SHIFT_64_05	0x0000000000000020LL
#define SHIFT_64_06	0x0000000000000040LL
#define SHIFT_64_07	0x0000000000000080LL
#define SHIFT_64_08	0x0000000000000100LL
#define SHIFT_64_09	0x0000000000000200LL
#define SHIFT_64_10	0x0000000000000400LL
#define SHIFT_64_11	0x0000000000000800LL
#define SHIFT_64_12	0x0000000000001000LL
#define SHIFT_64_13	0x0000000000002000LL
#define SHIFT_64_14	0x0000000000004000LL
#define SHIFT_64_15	0x0000000000008000LL
#define SHIFT_64_16	0x0000000000010000LL
#define SHIFT_64_17	0x0000000000020000LL
#define SHIFT_64_18	0x0000000000040000LL
#define SHIFT_64_19	0x0000000000080000LL
#define SHIFT_64_20	0x0000000000100000LL
#define SHIFT_64_21	0x0000000000200000LL
#define SHIFT_64_22	0x0000000000400000LL
#define SHIFT_64_23	0x0000000000800000LL
#define SHIFT_64_24	0x0000000001000000LL
#define SHIFT_64_25	0x0000000002000000LL
#define SHIFT_64_26	0x0000000004000000LL
#define SHIFT_64_27	0x0000000008000000LL
#define SHIFT_64_28	0x0000000010000000LL
#define SHIFT_64_29	0x0000000020000000LL
#define SHIFT_64_30	0x0000000040000000LL
#define SHIFT_64_31	0x0000000080000000LL
#define SHIFT_64_32	0x0000000100000000LL
#define SHIFT_64_33	0x0000000200000000LL
#define SHIFT_64_34	0x0000000400000000LL
#define SHIFT_64_35	0x0000000800000000LL
#define SHIFT_64_36	0x0000001000000000LL
#define SHIFT_64_37	0x0000002000000000LL
#define SHIFT_64_38	0x0000004000000000LL
#define SHIFT_64_39	0x0000008000000000LL
#define SHIFT_64_40	0x0000010000000000LL
#define SHIFT_64_41	0x0000020000000000LL
#define SHIFT_64_42	0x0000040000000000LL
#define SHIFT_64_43	0x0000080000000000LL
#define SHIFT_64_44	0x0000100000000000LL
#define SHIFT_64_45	0x0000200000000000LL
#define SHIFT_64_46	0x0000400000000000LL
#define SHIFT_64_47	0x0000800000000000LL
#define SHIFT_64_48	0x0001000000000000LL
#define SHIFT_64_49	0x0002000000000000LL
#define SHIFT_64_50	0x0004000000000000LL
#define SHIFT_64_51	0x0008000000000000LL
#define SHIFT_64_52	0x0010000000000000LL
#define SHIFT_64_53	0x0020000000000000LL
#define SHIFT_64_54	0x0040000000000000LL
#define SHIFT_64_55	0x0080000000000000LL
#define SHIFT_64_56	0x0100000000000000LL
#define SHIFT_64_57	0x0200000000000000LL
#define SHIFT_64_58	0x0400000000000000LL
#define SHIFT_64_59	0x0800000000000000LL
#define SHIFT_64_60	0x1000000000000000LL
#define SHIFT_64_61	0x2000000000000000LL
#define SHIFT_64_62	0x4000000000000000LL
#define SHIFT_64_63	0x8000000000000000LL

/** @enum __NF_IPCAM_CATE_E
 *  @brief 카메라쪽 notify 카테고리. 현재 VCA만 사용함.
 */
typedef enum __NF_IPCAM_CATE_E_ {
	NF_IPCAM_CATE_STREAM = 0,//!< Stream setup
	NF_IPCAM_CATE_IMAGE,     //!< Image
	NF_IPCAM_CATE_PTZ,       //!< PTZ
	NF_IPCAM_CATE_MOTION,    //!< Motion
	NF_IPCAM_CATE_PMASK,     //!< Privacy Mask
	NF_IPCAM_CATE_VCA,       //!< VCA

	NF_IPCAM_CATE_MAX        //!<
} NF_IPCAM_CATE_E;

/** @enum __NF_IPCAM_MODEL_CLASS_E_
 *  @brief 카메라 모델 코드.
 *  @deprecated __NF_IPCAM_MODEL_CODE_E_ 참조.
 */
typedef enum __NF_IPCAM_MODEL_CLASS_E_ {
	NF_IPCAM_MODEL_368_ITX_2M = 0,//!< NF_IPCAM_MODEL_368_ITX_2M
	NF_IPCAM_MODEL_PROBE_ITX_2M,  //!< NF_IPCAM_MODEL_PROBE_ITX_2M
	NF_IPCAM_MODEL_A2_ITX_1M2M,   //!< NF_IPCAM_MODEL_A2_ITX_1M2M
	NF_IPCAM_MODEL_A2_VICON_1M2M, //!< NF_IPCAM_MODEL_A2_VICON_1M2M
	NF_IPCAM_MODEL_A2_SPS_1M2M,   //!< NF_IPCAM_MODEL_A2_SPS_1M2M
	NF_IPCAM_MODEL_A2_CBC_IR_1M2M,//!< NF_IPCAM_MODEL_A2_CBC_IR_1M2M
	NF_IPCAM_MODEL_A2_CBC_1M2M,   //!< NF_IPCAM_MODEL_A2_CBC_1M2M
	NF_IPCAM_MODEL_A2_ITX_D1,     //!< NF_IPCAM_MODEL_A2_ITX_D1
	NF_IPCAM_MODEL_A2_VICON_D1,   //!< NF_IPCAM_MODEL_A2_VICON_D1
	NF_IPCAM_MODEL_A2_CBC_D1,     //!< NF_IPCAM_MODEL_A2_CBC_D1
	NF_IPCAM_MODEL_368_ITX_TEST,  //!< NF_IPCAM_MODEL_368_ITX_TEST
	NF_IPCAM_MODEL_NR             //!< NF_IPCAM_MODEL_NR
} NF_IPCAM_MODEL_CLASS_E;

/** @enum __NF_IPCAM_MODEL_CODE_E_
 *  @brief 카메라 모델 코드.
 *  모델 추가시 nmf등에도 반드시 추가해야 한다.
 */
typedef enum __NF_IPCAM_MODEL_CODE_E_ {
	NF_IPCAM_MODEL_AMB_A2= 0,    //!< A2 카메라
	NF_IPCAM_MODEL_TI_368,       //!< TI 카메라 (INx, NPT등 포함)
	NF_IPCAM_MODEL_AMB_D1,       //!< A2 카메라(D1급)
	NF_IPCAM_MODEL_ONVIF,        //!< ONVIF 카메라
	NF_IPCAM_MODEL_ONVIF_L1,     //!< ONVIF 카메라(Sysdb 존재)
	NF_IPCAM_MODEL_ONVIF_GRUNDIG,//!< ONVIF grundig 카메라(Audio out등으로 별도 분류)

	NF_NVS_MODEL_ITX,            //!< NVS

	NF_IPCAM_MODEL_MAX           //!<
} NF_IPCAM_MODEL_CODE_E;

typedef enum __NF_IPCAM_HISILICON_CHIPSET_CODE_E_ {
	NF_IPCAM_HISILICON_CHIPSET_3516A = 0,
	NF_IPCAM_HISILICON_CHIPSET_3516C,
	NF_IPCAM_HISILICON_CHIPSET_3516D
} NF_IPCAM_HISILICON_CHIPSET_CODE_E;

/** @enum __NF_IPCAM_STREAM_E_
 *  @brief 카메라에서 재생가능한 stream 종류.
 */
typedef enum __NF_IPCAM_STREAM_E_ {
	NF_IPCAM_STREAM_1ST,  //!< 1st stream
	NF_IPCAM_STREAM_2ND,  //!< 2nd stream
#if SUPPORT_3RD_STREAM
	NF_IPCAM_STREAM_3RD,
#endif
	NF_IPCAM_STREAM_AUDIO,//!< audio stream
	NF_IPCAM_STREAM_MAX   //!<
} NF_IPCAM_STREAM_E;

/** @enum __NF_IPCAM_RES_E_
 *  @brief 카메라에서 재생가능한 해상도 분류.
 *  	   테이블 갯수 부족으로 인해 data type 변경해야함.
  
typedef enum __NF_IPCAM_RES_E_ {
	NF_IPCAM_RES_320x240              = 1<< 0,  //!< 320x240
	NF_IPCAM_RES_352x240              = 1<< 1,	//!< NTSC_CIF
	NF_IPCAM_RES_352x288              = 1<< 2,	//!< PAL CIF
	NF_IPCAM_RES_640x352              = 1<< 3,  //!< 640x352
	NF_IPCAM_RES_640x480              = 1<< 4,  //!< 640x480
	NF_IPCAM_RES_704x480              = 1<< 5,	//!< NTSC 4CIF
	NF_IPCAM_RES_704x576              = 1<< 6,	//!< PAL 4CIF
	NF_IPCAM_RES_720x480              = 1<< 7,  //!< 720x480
	NF_IPCAM_RES_720x576              = 1<< 8,  //!< 720x576
	NF_IPCAM_RES_1280x720I            = 1<< 9,  //!< 1280x720I
	NF_IPCAM_RES_1280x720             = 1<< 10, //!< 1280x720
	NF_IPCAM_RES_1024x768             = 1<< 11, //!< 1024x768
	NF_IPCAM_RES_1280x1024            = 1<< 12, //!< 1280x1024
	NF_IPCAM_RES_1920x1080I           = 1<< 13, //!< 1920x1080I
	NF_IPCAM_RES_1920x1080            = 1<< 14, //!< 1920x1080
	NF_IPCAM_RES_640x360              = 1<< 15, //!< 640x360
	NF_IPCAM_RES_320x180              = 1<< 16, //!< 320x180
	NF_IPCAM_RES_640x360I             = 1<< 17, //!< 640x360I
	NF_IPCAM_RES_640x400              = 1<< 18, //!< 640x400
	NF_IPCAM_RES_800x450              = 1<< 19, //!< 800x450
	NF_IPCAM_RES_1440x900             = 1<< 20, //!< 1440x900
	NF_IPCAM_RES_800x600              = 1<< 21, //!< 800x600
	NF_IPCAM_RES_1600x1200            = 1<< 22, //!< 1600x1200
	NF_IPCAM_RES_2304x1296			  = 1<< 23, //!< 3M 16:9
	NF_IPCAM_RES_2048x1536			  = 1<< 24, //!< 3M 4:3
	NF_IPCAM_RES_2560x1440			  = 1<< 25, //!< 3,6M 16:9
	NF_IPCAM_RES_2688x1520			  = 1<< 26, //!< 4M 16:9i
	NF_IPCAM_RES_2560x1600			  = 1<< 27, //!< (4.1M) 16:10 WQXGA
	NF_IPCAM_RES_2560x1920			  = 1<< 28, //!< 5M 4:3 5M IPCAM AvtiveX
	NF_IPCAM_RES_2592x1920			  = 1<< 29, //!< 5M 4:3 Sunell cam
	NF_IPCAM_RES_2592x1944			  = 1<< 30, //!< 5M 4:3
	NF_IPCAM_RES_MAX                  = 31      //!<
} NF_IPCAM_RES_E;*/

/** @enum __NF_IPCAM_RES_E_
 *  @brief 카메라에서 재생가능한 해상도 분류.
 */

#define	NF_IPCAM_RES_320x240	SHIFT_64_00
#define	NF_IPCAM_RES_352x240	SHIFT_64_01
#define	NF_IPCAM_RES_352x288	SHIFT_64_02
#define	NF_IPCAM_RES_640x352	SHIFT_64_03
#define	NF_IPCAM_RES_640x480	SHIFT_64_04
#define	NF_IPCAM_RES_704x480	SHIFT_64_05
#define	NF_IPCAM_RES_704x576	SHIFT_64_06
#define	NF_IPCAM_RES_720x480	SHIFT_64_07
#define	NF_IPCAM_RES_720x576	SHIFT_64_08
#define	NF_IPCAM_RES_1280x720I	SHIFT_64_09
#define	NF_IPCAM_RES_1280x720	SHIFT_64_10
#define	NF_IPCAM_RES_1024x768	SHIFT_64_11
#define	NF_IPCAM_RES_1280x1024	SHIFT_64_12
#define	NF_IPCAM_RES_1920x1080I	SHIFT_64_13
#define	NF_IPCAM_RES_1920x1080	SHIFT_64_14
#define	NF_IPCAM_RES_640x360	SHIFT_64_15
#define	NF_IPCAM_RES_320x180	SHIFT_64_16
#define	NF_IPCAM_RES_640x360I	SHIFT_64_17
#define	NF_IPCAM_RES_640x400	SHIFT_64_18
#define	NF_IPCAM_RES_800x450	SHIFT_64_19
#define	NF_IPCAM_RES_1440x900	SHIFT_64_20
#define	NF_IPCAM_RES_800x600	SHIFT_64_21
#define	NF_IPCAM_RES_1600x1200	SHIFT_64_22
#define	NF_IPCAM_RES_2304x1296	SHIFT_64_23
#define	NF_IPCAM_RES_2048x1536	SHIFT_64_24
#define	NF_IPCAM_RES_2560x1440	SHIFT_64_25
#define	NF_IPCAM_RES_2688x1520	SHIFT_64_26
#define	NF_IPCAM_RES_2560x1600	SHIFT_64_27
#define	NF_IPCAM_RES_2560x1920	SHIFT_64_28
#define	NF_IPCAM_RES_2592x1920	SHIFT_64_29
#define	NF_IPCAM_RES_2592x1944	SHIFT_64_30
#define	NF_IPCAM_RES_2992x1680	SHIFT_64_31
#define	NF_IPCAM_RES_2880x1800	SHIFT_64_32
#define	NF_IPCAM_RES_3200x1800	SHIFT_64_33
#define	NF_IPCAM_RES_2880x2160	SHIFT_64_34
#define	NF_IPCAM_RES_3072x2048	SHIFT_64_35
#define	NF_IPCAM_RES_3200x2400	SHIFT_64_36
#define	NF_IPCAM_RES_3840x2160	SHIFT_64_37	//P4 temp merge
#define	NF_IPCAM_RES_2592x1520	SHIFT_64_38
#define	NF_IPCAM_RES_3000x3000	SHIFT_64_39
#define	NF_IPCAM_RES_2048x2048	SHIFT_64_40
#define	NF_IPCAM_RES_1280x1280	SHIFT_64_41
#define	NF_IPCAM_RES_640x640	SHIFT_64_42
#define	NF_IPCAM_RES_320x320	SHIFT_64_43
#define NF_IPCAM_RES_MAX		44 
/** @enum __NF_IPCAM_RES_E_
 *  @brief 해상도 추가로 인한 uint64 데이터 타입 변화 >> shift 연산 테이블.
 */
static uint64_t shift_res_table[64] = {
	SHIFT_64_00,
	SHIFT_64_01,
	SHIFT_64_02,
	SHIFT_64_03,
	SHIFT_64_04,
	SHIFT_64_05,
	SHIFT_64_06,
	SHIFT_64_07,
	SHIFT_64_08,
	SHIFT_64_09,
	SHIFT_64_10,
	SHIFT_64_11,
	SHIFT_64_12,
	SHIFT_64_13,
	SHIFT_64_14,
	SHIFT_64_15,
	SHIFT_64_16,
	SHIFT_64_17,
	SHIFT_64_18,
	SHIFT_64_19,
	SHIFT_64_20,
	SHIFT_64_21,
	SHIFT_64_22,
	SHIFT_64_23,
	SHIFT_64_24,
	SHIFT_64_25,
	SHIFT_64_26,
	SHIFT_64_27,
	SHIFT_64_28,
	SHIFT_64_29,
	SHIFT_64_30,
	SHIFT_64_31,
	SHIFT_64_32,
	SHIFT_64_33,
	SHIFT_64_34,
	SHIFT_64_35,
	SHIFT_64_36,
	SHIFT_64_37,
	SHIFT_64_38,
	SHIFT_64_39,
	SHIFT_64_40,
	SHIFT_64_41,
	SHIFT_64_42,
	SHIFT_64_43,
	SHIFT_64_44,
	SHIFT_64_45,
	SHIFT_64_46,
	SHIFT_64_47,
	SHIFT_64_48,
	SHIFT_64_49,
	SHIFT_64_50,
	SHIFT_64_51,
	SHIFT_64_52,
	SHIFT_64_53,
	SHIFT_64_54,
	SHIFT_64_55,
	SHIFT_64_56,
	SHIFT_64_57,
	SHIFT_64_58,
	SHIFT_64_59,
	SHIFT_64_60,
	SHIFT_64_61,
	SHIFT_64_62,
	SHIFT_64_63
};

/** @enum __NF_IPCAM_FPS_E_
 *  @brief NVR에서 지원하는 카메라 FPS 분류.
 */
typedef enum __NF_IPCAM_FPS_E_
{
	NF_IPCAM_FPS_300                  = 1<< 0, //!< 30 fps
	NF_IPCAM_FPS_150                  = 1<< 1, //!< 15 fps
	NF_IPCAM_FPS_100                  = 1<< 2, //!< 10 fps
	NF_IPCAM_FPS_70                   = 1<< 3, //!< 7 fps
	NF_IPCAM_FPS_40                   = 1<< 4, //!< 4 fps
	NF_IPCAM_FPS_20                   = 1<< 5, //!< 2 fps
	NF_IPCAM_FPS_10                   = 1<< 6, //!< 1 fps
	NF_IPCAM_FPS_250                  = 1<< 7, //!< 25 fps
	NF_IPCAM_FPS_120                  = 1<< 8, //!< 12 fps
	NF_IPCAM_FPS_60                   = 1<< 9, //!< 6 fps
	NF_IPCAM_FPS_30                   = 1<< 10,//!< 3 fps
	NF_IPCAM_FPS_125                  = 1<< 11,//!< 12.5 fps
	NF_IPCAM_FPS_AUDIO                = 1<< 12,//!< obsolete
	NF_IPCAM_FPS_MAX                  = 13     //!<
} NF_IPCAM_FPS_E;

/** @enum __NF_IPCAM_QUALITY_E_
 *  @brief NVR에서 설정하는 카메라 화질 분류.
 */
typedef enum __NF_IPCAM_QUALITY_E_
{
	NF_IPCAM_QUALITY_LOW,     //!< LOW
	NF_IPCAM_QUALITY_STANDARD,//!< STANDARD
	NF_IPCAM_QUALITY_HIGH,    //!< HIGH
	NF_IPCAM_QUALITY_HIGHEST, //!< HIGHEST
	NF_IPCAM_QUALITY_SUPER,   //!< SUPER
	NF_IPCAM_QUALITY_MAX      //!<
} NF_IPCAM_QUALITY_E;





typedef struct __RECEVT_SET_ENCODER_CMD_PARAM_T NF_RECEVT_SET_ENCODER_CMD_PARAM_T;
struct __RECEVT_SET_ENCODER_CMD_PARAM_T
{
	guint change_mask;
	NF_IPCAM_FPS_E fps1[NUM_ACTIVE_CH];
	NF_IPCAM_FPS_E fps2[NUM_ACTIVE_CH];
	NF_IPCAM_QUALITY_E qual1[NUM_ACTIVE_CH];
	NF_IPCAM_QUALITY_E qual2[NUM_ACTIVE_CH];
};





/** @enum __IPX_CODEC_TYPE_E_
 *  @brief NVR에서 지원하는 비디오,오디오 코덱 분류.
 */
typedef enum __IPX_CODEC_TYPE_E_{
	NF_IPCAM_ACODEC_G711_ULAW = 1<<0,//!< G711_ULAW
	NF_IPCAM_ACODEC_G711_ALAW = 1<<1,//!< G711_ALAW
	NF_IPCAM_ACODEC_NR = 2,          //!<

	NF_IPCAM_VCODEC_H264 = 1<<1,     //!< H264
	NF_IPCAM_VCODEC_H265 = 1<<2,     //!< H265
	NF_IPCAM_VCODEC_NR = 2     		 //!<
} IPX_CODEC_TYPE_E;

/** @enum _IPX_IPCAM_RX_METHOD_E
 *  @brief 카메라 RTSP 접속방법. 현재 RTSP_TCP만 사용.
 */
typedef enum _IPX_IPCAM_RX_METHOD_E {
	NF_IPCAM_RX_METHOD_HTTP           = 1<< 0,//!< HTTP
	NF_IPCAM_RX_METHOD_RTSP_TCP       = 1<< 1,//!< RTP over RTSP(TCP)
	NF_IPCAM_RX_METHOD_RTSP_TCP_HTTP  = 1<< 2,//!< RTP over RTSP(HTTP)
	NF_IPCAM_RX_METHOD_RTSP_UDP       = 1<< 3,//!< RTSP_UDP
	NF_IPCAM_RX_METHOD_RTSP_UDP_MULTI = 1<< 4,//!< RTSP_UDP_MULTI
	NF_IPCAM_RX_METHOD_RTP_TCP        = 1<< 5,//!< RTP_TCP
	NF_IPCAM_RX_METHOD_RTP_UDP        = 1<< 6,//!< UDP unicast
	NF_IPCAM_RX_METHOD_RTP_UDP_MULTI  = 1<< 7,//!< UDP multicast
	NF_IPCAM_RX_METHOD_NR             = 8     //!<
} IPX_IPCAM_RX_METHOD_E;

/** @enum _NF_IPCAM_FUNC_E
 *  @brief 카메라에서 지원하는 '특수'기능 목록.
 */
typedef enum _NF_IPCAM_FUNC_E {
	NF_IPCAM_FUNC_PTZ			= 1<<0, //!< PTZ
	NF_IPCAM_FUNC_MOTION		= 1<<1, //!< Motion
	NF_IPCAM_FUNC_ALARM_IN		= 1<<2, //!< Alarm in
	NF_IPCAM_FUNC_ALARM_OUT		= 1<<3, //!< Alarm out
	NF_IPCAM_FUNC_AUDIO_RX		= 1<<4, //!< Audio Rx
	NF_IPCAM_FUNC_AUDIO_TX		= 1<<5, //!< Audio Tx
	NF_IPCAM_FUNC_PRIVACY_MASK	= 1<<6, //!< Privacy Mask
	NF_IPCAM_FUNC_VA			= 1<<7, //!< VCA
	NF_IPCAM_FUNC_ROI			= 1<<8, //!< Hisilicon ROI
	NF_IPCAM_FUNC_SMART_MOTION	= 1<<9, //!< AI CAMERA
	NF_IPCAM_FUNC_CORRIDOR_MODE	= 1<<10, //!< Corridor Mode
	NF_IPCAM_FUNC_NR			= 11
} NF_IPCAM_FUNC_E;

/** @enum _NF_IPCAM_IMAGE_E
 *  @brief ITX카메라에서 지원하는 이미지 설정 옵션들.
 */
#define	NF_IPCAM_IMAGE_SHARPNESS	SHIFT_64_00
#define	NF_IPCAM_IMAGE_BRIGHTNESS	SHIFT_64_01
#define	NF_IPCAM_IMAGE_CONTRAST		SHIFT_64_02
#define	NF_IPCAM_IMAGE_COLOR		SHIFT_64_03
#define	NF_IPCAM_IMAGE_TINT		SHIFT_64_04
#define	NF_IPCAM_IMAGE_EXPOSURE		SHIFT_64_05
#define	NF_IPCAM_IMAGE_AGC		SHIFT_64_06
#define	NF_IPCAM_IMAGE_ESHUTTER		SHIFT_64_07
#define	NF_IPCAM_IMAGE_SLOWSHUTTER	SHIFT_64_08
#define	NF_IPCAM_IMAGE_MAXAGC		SHIFT_64_09
#define	NF_IPCAM_IMAGE_DCIRIS		SHIFT_64_10
#define	NF_IPCAM_IMAGE_BLC		SHIFT_64_11
#define	NF_IPCAM_IMAGE_CALIBRATION	SHIFT_64_12
#define	NF_IPCAM_IMAGE_ICF		SHIFT_64_13
#define	NF_IPCAM_IMAGE_WB		SHIFT_64_14
#define	NF_IPCAM_IMAGE_MWB		SHIFT_64_15
#define	NF_IPCAM_IMAGE_WDR		SHIFT_64_16
#define	NF_IPCAM_IMAGE_MIRRORING	SHIFT_64_17
#define	NF_IPCAM_IMAGE_ANTIFLICKER	SHIFT_64_18
#define	NF_IPCAM_IMAGE_DNN		SHIFT_64_19
#define	NF_IPCAM_IMAGE_PIRIS		SHIFT_64_20
#define	NF_IPCAM_IMAGE_PAN		SHIFT_64_21
#define	NF_IPCAM_IMAGE_PRESET		SHIFT_64_22
#define	NF_IPCAM_IMAGE_ZOOM		SHIFT_64_23
#define	NF_IPCAM_IMAGE_FOCUS		SHIFT_64_24
#define	NF_IPCAM_IMAGE_ONEPUSH		SHIFT_64_25
#define	NF_IPCAM_IMAGE_DNN_TOGGLE	SHIFT_64_26
#define	NF_IPCAM_IMAGE_MAX_SHUTTER	SHIFT_64_27
#define	NF_IPCAM_IMAGE_DNR		SHIFT_64_28
#define	NF_IPCAM_IMAGE_AUXILIARY	SHIFT_64_29
#define	NF_IPCAM_IMAGE_ADAPTIVEIR	SHIFT_64_30
#define	NF_IPCAM_IMAGE_DNN_SENSE_NTOD	SHIFT_64_31
#define	NF_IPCAM_IMAGE_DNN_SENSE_DTON	SHIFT_64_32
#define	NF_IPCAM_IMAGE_DEFOG		SHIFT_64_33
#define	NF_IPCAM_IMAGE_HLC		SHIFT_64_34
#define NF_IPCAM_IMAGE_IRCUTM		SHIFT_64_35
#define NF_IPCAM_IMAGE_FOCUS_LIMIT	SHIFT_64_36
#define NF_IPCAM_IMAGE_STABILIZER	SHIFT_64_37
#define NF_IPCAM_IMAGE_IR_CORRECTION	SHIFT_64_38
#define NF_IPCAM_IMAGE_DC_IRIS_CAL	SHIFT_64_39
#define NF_IPCAM_IMAGE_MAX_SHUTTER_MOTION_OFF_ON	SHIFT_64_40
#define NF_IPCAM_IMAGE_MAX_SHUTTER_AUTO_OFF_OFF		SHIFT_64_41
#define NF_IPCAM_IMAGE_MAX_SHUTTER_AUTO_OFF_ON_TV	SHIFT_64_42
#define NF_IPCAM_IMAGE_MAX_SHUTTER_AUTO_OFF_ON		SHIFT_64_43
#define NF_IPCAM_IMAGE_ANTI_FLICKER_MOTION_OFF		SHIFT_64_44
#define NF_IPCAM_IMAGE_ANTI_FLICKER_AUTO_OFF		SHIFT_64_45
#define NF_IPCAM_IMAGE_BASE_SHUTTER		SHIFT_64_46
#define	NF_IPCAM_IMAGE_DCIRIS_MOTION		SHIFT_64_47
#define	NF_IPCAM_IMAGE_DNR_AUTO_SMART		SHIFT_64_48
#define NF_IPCAM_IMAGE_COLORVU		SHIFT_64_49
#define	NF_IPCAM_IMAGE_NR		50

/** @enum _NF_IPCAM_IMAGE_MODES_E
 *  @brief 카메라 이미지 옵션별 설정 가능한 값들.
 */                       
typedef enum _NF_IPCAM_IMAGE_MODES_E {
	/* Exposure modes */
	NF_IPCAM_IMAGE_EXP_MODE_NULL1			= 1<<0,  //!< NF_IPCAM_IMAGE_EXP_MODE_NULL1
	NF_IPCAM_IMAGE_EXP_MODE_NULL2			= 1<<1,  //!< NF_IPCAM_IMAGE_EXP_MODE_NULL2
	NF_IPCAM_IMAGE_EXP_MODE_NULL3			= 1<<2,  //!< NF_IPCAM_IMAGE_EXP_MODE_NULL3
	NF_IPCAM_IMAGE_EXP_MODE_NULL4			= 1<<3,  //!< NF_IPCAM_IMAGE_EXP_MODE_NULL4
	NF_IPCAM_IMAGE_EXP_MODE_MANUAL			= 1<<4,  //!< NF_IPCAM_IMAGE_EXP_MODE_MANUAL
	NF_IPCAM_IMAGE_EXP_MODE_AUTO_INDOOR		= 1<<5,  //!< NF_IPCAM_IMAGE_EXP_MODE_AUTO_INDOOR
	NF_IPCAM_IMAGE_EXP_MODE_AUTO_OUTDOOR		= 1<<6,  //!< NF_IPCAM_IMAGE_EXP_MODE_AUTO_OUTDOOR
	NF_IPCAM_IMAGE_EXP_MODE_AUTO			= 1<<7,  //!< NF_IPCAM_IMAGE_EXP_MODE_AUTO
	NF_IPCAM_IMAGE_EXP_MODE_AUTO_MOTION		= 1<<8,  //!< NF_IPCAM_IMAGE_EXP_MODE_AUTO
	NF_IPCAM_IMAGE_EXP_MODE_AUTO_I3			= 1<<9,  //!< NF_IPCAM_IMAGE_EXP_MODE_AUTO_I3
	NF_IPCAM_IMAGE_EXP_MODE_MANUAL_I3		= 1<<10, //!< NF_IPCAM_IMAGE_EXP_MODE_MANUAL_I3
	NF_IPCAM_IMAGE_EXP_MODE_AUTO_INX		= 1<<11, //!< NF_IPCAM_IMAGE_EXP_MODE_AUTO_INX
	NF_IPCAM_IMAGE_EXP_MODE_AUTO_MOTION_INX		= 1<<12, //!< NF_IPCAM_IMAGE_EXP_MODE_AUTO_INX
	NF_IPCAM_IMAGE_EXP_MODE_MANUAL_INX		= 1<<13, //!< NF_IPCAM_IMAGE_EXP_MODE_MANUAL_INX
	NF_IPCAM_IMAGE_EXP_MODE_AUTO_NPT		= 1<<14, //!< NF_IPCAM_IMAGE_EXP_MODE_AUTO_NPT
	NF_IPCAM_IMAGE_EXP_MODE_MANUAL_NPT		= 1<<15, //!< NF_IPCAM_IMAGE_EXP_MODE_MANUAL_NPT
	NF_IPCAM_IMAGE_EXP_MODE_AUTO_NPT_X10		= 1<<16, //!< NF_IPCAM_IMAGE_EXP_MODE_AUTO_NPT
	NF_IPCAM_IMAGE_EXP_MODE_MANUAL_NPT_X10		= 1<<17, //!< NF_IPCAM_IMAGE_EXP_MODE_MANUAL_NPT
	NF_IPCAM_IMAGE_EXP_MODE_HI_AUTO_MOTION 	= 1<<18,
	NF_IPCAM_IMAGE_EXP_MODE_HI_AUTO	 	= 1<<19,
	NF_IPCAM_IMAGE_EXP_MODE_HI_MANUAL	 	= 1<<20,
	NF_IPCAM_IMAGE_EXP_MODE_HI_AUTO_MOTION_INDH 	= 1<<21,
	NF_IPCAM_IMAGE_EXP_MODE_NR			= 22,	 //!< NF_IPCAM_IMAGE_EXP_MODE_NR

	/* Slow shutter modes */
	NF_IPCAM_IMAGE_SLSH_MODE_OFF			= 1<<0,       //!< NF_IPCAM_IMAGE_SLSH_MODE_OFF
	NF_IPCAM_IMAGE_SLSH_MODE_ON				= 1<<1,       //!< NF_IPCAM_IMAGE_SLSH_MODE_ON
	NF_IPCAM_IMAGE_SLSH_MODE_X4				= 1<<2,       //!< NF_IPCAM_IMAGE_SLSH_MODE_X4
	NF_IPCAM_IMAGE_SLSH_MODE_X8				= 1<<3,       //!< NF_IPCAM_IMAGE_SLSH_MODE_X8
	NF_IPCAM_IMAGE_SLSH_NPT_MODE_OFF			= 1<<4,       //!< NF_IPCAM_IMAGE_SLSH_NPT_MODE_OFF
	NF_IPCAM_IMAGE_SLSH_NPT_MODE_ON				= 1<<5,       //!< NF_IPCAM_IMAGE_SLSH_NPT_MODE_ON 
	NF_IPCAM_IMAGE_SLSH_MODE2_OFF			= 1<<6,       //!< NF_IPCAM_IMAGE_SLSH_MODE2_OFF
	NF_IPCAM_IMAGE_SLSH_MODE2_ON			= 1<<7,       //!< NF_IPCAM_IMAGE_SLSH_MODE2_ON
	NF_IPCAM_IMAGE_SLSH_MODE2_X4			= 1<<8,       //!< NF_IPCAM_IMAGE_SLSH_MODE2_X4
	NF_IPCAM_IMAGE_SLSH_MODE2_X8			= 1<<9,       //!< NF_IPCAM_IMAGE_SLSH_MODE2_X8
	NF_IPCAM_IMAGE_SLSH_MODE3_OFF			= 1<<10,       //!< NF_IPCAM_IMAGE_SLSH_MODE3_OFF
	NF_IPCAM_IMAGE_SLSH_MODE3_ON			= 1<<11,       //!< NF_IPCAM_IMAGE_SLSH_MODE3_ON
	NF_IPCAM_IMAGE_SLSH_MODE3_X4			= 1<<12,       //!< NF_IPCAM_IMAGE_SLSH_MODE3_X4
	NF_IPCAM_IMAGE_SLSH_MODE3_X8			= 1<<13,       //!< NF_IPCAM_IMAGE_SLSH_MODE3_X8
	NF_IPCAM_IMAGE_SLSH_TWDR_OFF			= 1<<14,       //!< NF_IPCAM_IMAGE_SLSH_TWDR_OFF
	NF_IPCAM_IMAGE_SLSH_TWDR_ON				= 1<<15,   	  //!< NF_IPCAM_IMAGE_SLSH_TWDR_ON
	NF_IPCAM_IMAGE_SLSH_TWDR_X4				= 1<<16,   	  //!< NF_IPCAM_IMAGE_SLSH_TWDR_X4
	NF_IPCAM_IMAGE_SLSH_TWDR_X8				= 1<<17,   	  //!< NF_IPCAM_IMAGE_SLSH_TWDR_X8
	NF_IPCAM_IMAGE_SLSH_MODE_NR				= 18,    	//!< NF_IPCAM_IMAGE_SLSH_MODE_NR

	/* Max AGC modes */
	NF_IPCAM_IMAGE_MAGC_MODE_LOW			= 1<<0,       //!< NF_IPCAM_IMAGE_MAGC_MODE_LOW
	NF_IPCAM_IMAGE_MAGC_MODE_MID			= 1<<1,       //!< NF_IPCAM_IMAGE_MAGC_MODE_MID
	NF_IPCAM_IMAGE_MAGC_MODE_DEFAULT		= 1<<2,    //!< NF_IPCAM_IMAGE_MAGC_MODE_DEFAULT
	NF_IPCAM_IMAGE_MAGC_MODE_2				= 1<<3,        //!< NF_IPCAM_IMAGE_MAGC_MODE_2
	NF_IPCAM_IMAGE_MAGC_MODE_4				= 1<<4,        //!< NF_IPCAM_IMAGE_MAGC_MODE_4
	NF_IPCAM_IMAGE_MAGC_MODE_8				= 1<<5,        //!< NF_IPCAM_IMAGE_MAGC_MODE_8
	NF_IPCAM_IMAGE_MAGC_MODE_16				= 1<<6,       //!< NF_IPCAM_IMAGE_MAGC_MODE_16
	NF_IPCAM_IMAGE_MAGC_MODE_HIGH			= 1<<7,      //!< NF_IPCAM_IMAGE_MAGC_MODE_HIGH
	NF_IPCAM_IMAGE_MAGC_MODE_MAX			= 1<<8,       //!< NF_IPCAM_IMAGE_MAGC_MODE_MAX
	NF_IPCAM_IMAGE_MAGC_MODE_LOW_MID_30		= 1<<9, //!< NF_IPCAM_IMAGE_MAGC_MODE_LOW_MID_30
	NF_IPCAM_IMAGE_MAGC_MODE_HIGH_MID_36	= 1<<10,//!< NF_IPCAM_IMAGE_MAGC_MODE_HIGH_MID_36
	NF_IPCAM_IMAGE_MAGC_MODE_HIGH_42		= 1<<11,   //!< NF_IPCAM_IMAGE_MAGC_MODE_HIGH_42
	NF_IPCAM_IMAGE_MAGC_MODE_MAX_46			= 1<<12,   //!< NF_IPCAM_IMAGE_MAGC_MODE_MAX_46
	/* MAX AGC for Specific Vendor(CBC) */
	NF_IPCAM_IMAGE_MAGC_MODE_CBC_0			= 1<<13,   //!< NF_IPCAM_IMAGE_MAGC_MODE_CBC_0
	NF_IPCAM_IMAGE_MAGC_MODE_CBC_1			= 1<<14,   //!< NF_IPCAM_IMAGE_MAGC_MODE_CBC_1
	NF_IPCAM_IMAGE_MAGC_MODE_CBC_2			= 1<<15,   //!< NF_IPCAM_IMAGE_MAGC_MODE_CBC_2
	NF_IPCAM_IMAGE_MAGC_MODE_CBC_3			= 1<<16,   //!< NF_IPCAM_IMAGE_MAGC_MODE_CBC_3
	NF_IPCAM_IMAGE_MAGC_MODE_CBC_4			= 1<<17,   //!< NF_IPCAM_IMAGE_MAGC_MODE_CBC_4
	NF_IPCAM_IMAGE_MAGC_MODE_CBC_5			= 1<<18,   //!< NF_IPCAM_IMAGE_MAGC_MODE_CBC_5
	NF_IPCAM_IMAGE_MAGC_MODE_CBC_6			= 1<<19,   //!< NF_IPCAM_IMAGE_MAGC_MODE_CBC_6
	NF_IPCAM_IMAGE_MAGC_MODE_CBC_7			= 1<<20,   //!< NF_IPCAM_IMAGE_MAGC_MODE_CBC_7
	NF_IPCAM_IMAGE_MAGC_MODE_CBC_8			= 1<<21,   //!< NF_IPCAM_IMAGE_MAGC_MODE_CBC_8
	NF_IPCAM_IMAGE_MAGC_MODE_CBC_9			= 1<<22,   //!< NF_IPCAM_IMAGE_MAGC_MODE_CBC_9
	NF_IPCAM_IMAGE_MAGC_MODE_NR				= 23,         //!< NF_IPCAM_IMAGE_MAGC_MODE_NR

	/* IRIS control modes */
	NF_IPCAM_IMAGE_DCIRIS_OFF				= 1<<0,         //!< NF_IPCAM_IMAGE_DCIRIS_OFF
	NF_IPCAM_IMAGE_DCIRIS_ON				= 1<<1,          //!< NF_IPCAM_IMAGE_DCIRIS_ON
	NF_IPCAM_IMAGE_PIRIS_AUTO				= 1<<2,         //!< NF_IPCAM_IMAGE_PIRIS_AUTO
	NF_IPCAM_IMAGE_PIRIS_MANUAL				= 1<<3,       //!< NF_IPCAM_IMAGE_PIRIS_MANUAL
	NF_IPCAM_IMAGE_PIRIS_BQ					= 1<<4,	//!<  Best Quality
	NF_IPCAM_IMAGE_PIRIS_DF					= 1<<5,	//!<  Depth of Field
	NF_IPCAM_IMAGE_PIRIS_BQ_TRACKING		= 1<<6,    //!< NF_IPCAM_IMAGE_PIRIS_BQ_TRACKING
	NF_IPCAM_IMAGE_PIRIS_DF_TRACKING		= 1<<7,    //!< NF_IPCAM_IMAGE_PIRIS_DF_TRACKING
	NF_IPCAM_IMAGE_DCIRIS_AXIS_ON			= 1<<8,    //!< AXIS DCIRIS ON(true)
	NF_IPCAM_IMAGE_DCIRIS_AXIS_OFF			= 1<<9,    //!<	AXIS DCIRIS OFF(false) 
	NF_IPCAM_IMAGE_IRIS_NR					= 10,              //!< NF_IPCAM_IMAGE_IRIS_NR

	/* Backlight compensation modes */
	NF_IPCAM_IMAGE_BLC_OFF					= 1<<0,           //!< NF_IPCAM_IMAGE_BLC_OFF
	NF_IPCAM_IMAGE_BLC_ON					= 1<<1,            //!< NF_IPCAM_IMAGE_BLC_ON
	NF_IPCAM_IMAGE_BLC_ADAPTIVE				= 1<<3,       //!< NF_IPCAM_IMAGE_BLC_ADAPTIVE
	NF_IPCAM_IMAGE_BLC_ZONE_LOWER			= 1<<4,      //!< NF_IPCAM_IMAGE_BLC_ZONE_LOWER
	NF_IPCAM_IMAGE_BLC_ZONE_MIDDLE			= 1<<5,     //!< NF_IPCAM_IMAGE_BLC_ZONE_MIDDLE
	NF_IPCAM_IMAGE_BLC_ZONE_UPPER			= 1<<6,      //!< NF_IPCAM_IMAGE_BLC_ZONE_UPPER
	NF_IPCAM_IMAGE_BLC_ZONE_LEFT			= 1<<7,       //!< NF_IPCAM_IMAGE_BLC_ZONE_LEFT
	NF_IPCAM_IMAGE_BLC_ZONE_RIGHT			= 1<<8,      //!< NF_IPCAM_IMAGE_BLC_ZONE_RIGHT
	NF_IPCAM_IMAGE_BLC_PTZ_OFF			= 1<<9,  //!< NF_IPCAM_IMAGE_BLC_PTZ_ON
	NF_IPCAM_IMAGE_BLC_PTZ_ON			= 1<<10,  //!< NF_IPCAM_IMAGE_BLC_PTZ_ON
	NF_IPCAM_IMAGE_BLC_NR				= 11,               //!< NF_IPCAM_IMAGE_BLC_NR

	/* Day and night modes */
	NF_IPCAM_IMAGE_DN_AUTO					= 1<<0,           //!< NF_IPCAM_IMAGE_DN_AUTO
	NF_IPCAM_IMAGE_DN_DAY					= 1<<1,            //!< NF_IPCAM_IMAGE_DN_DAY
	NF_IPCAM_IMAGE_DN_NIGHT					= 1<<2,          //!< NF_IPCAM_IMAGE_DN_NIGHT
	NF_IPCAM_IMAGE_DN_DUMMY					= 1<<3,          //!< NF_IPCAM_IMAGE_DN_NIGHT
	// ONVIF -
	NF_IPCAM_IMAGE_DN_NPT_AUTO				= 1<<7,           //!< NF_IPCAM_IMAGE_DN_AUTO
	NF_IPCAM_IMAGE_DN_NPT_DAY				= 1<<8,            //!< NF_IPCAM_IMAGE_DN_DAY
	NF_IPCAM_IMAGE_DN_NPT_NIGHT				= 1<<9,          //!< NF_IPCAM_IMAGE_DN_NIGHT
	NF_IPCAM_IMAGE_DN_NPT3_AUTO				= 1<<10,           //!< NF_IPCAM_IMAGE_DN_AUTO
	NF_IPCAM_IMAGE_DN_NPT3_DAY				= 1<<11,            //!< NF_IPCAM_IMAGE_DN_DAY
	NF_IPCAM_IMAGE_DN_NPT3_NIGHT			= 1<<12,          //!< NF_IPCAM_IMAGE_DN_NIGHT
	NF_IPCAM_IMAGE_DN_SCHEDULE				= 1<<13,          //!< NF_IPCAM_IMAGE_DN_SCHEDULE
	NF_IPCAM_IMAGE_DN_AXIS_AUTO				= 1<<14,  		//!< ONVIF_ON
	NF_IPCAM_IMAGE_DN_AXIS_ON				= 1<<15,  		//!< ONVIF_ON
	NF_IPCAM_IMAGE_DN_AXIS_OFF				= 1<<16,  		//!< ONVIF_ON
	NF_IPCAM_IMAGE_DN_EXTERNAL				= 1<<17,  		//!< ITX_EXTERNAL
	NF_IPCAM_IMAGE_DN_NR					= 18,                //!< NF_IPCAM_IMAGE_DN_NR

	/* Toggle condition lasting modes */
	NF_IPCAM_IMAGE_TGTIME_0SEC				= 1<<0,        //!< NF_IPCAM_IMAGE_TGTIME_0SEC
	NF_IPCAM_IMAGE_TGTIME_5SEC				= 1<<1,        //!< NF_IPCAM_IMAGE_TGTIME_5SEC
	NF_IPCAM_IMAGE_TGTIME_10SEC				= 1<<2,       //!< NF_IPCAM_IMAGE_TGTIME_10SEC
	NF_IPCAM_IMAGE_TGTIME_15SEC				= 1<<3,       //!< NF_IPCAM_IMAGE_TGTIME_15SEC
	NF_IPCAM_IMAGE_TGTIME_30SEC				= 1<<4,       //!< NF_IPCAM_IMAGE_TGTIME_30SEC
	NF_IPCAM_IMAGE_TGTIME_60SEC				= 1<<5,       //!< NF_IPCAM_IMAGE_TGTIME_60SEC
	NF_IPCAM_IMAGE_TGTIME_ALARM				= 1<<6,       //!< NF_IPCAM_IMAGE_TGTIME_ALARM
	NF_IPCAM_IMAGE_TGTIME_NR				= 7,             //!< NF_IPCAM_IMAGE_TGTIME_NR

	/* White balance modes */
	NF_IPCAM_IMAGE_WB_MODE_NULL1			= 1<<0,       //!< NF_IPCAM_IMAGE_WB_MODE_NULL1
	NF_IPCAM_IMAGE_WB_MODE_NULL2			= 1<<1,       //!< NF_IPCAM_IMAGE_WB_MODE_NULL2
	NF_IPCAM_IMAGE_WB_MODE_NULL3			= 1<<2,       //!< NF_IPCAM_IMAGE_WB_MODE_NULL3
	NF_IPCAM_IMAGE_WB_MODE_MANUAL			= 1<<3,      //!< NF_IPCAM_IMAGE_WB_MODE_MANUAL
	NF_IPCAM_IMAGE_WB_MODE_AUTO				= 1<<4,       //!< NF_IPCAM_IMAGE_WB_MODE_AUTO
	NF_IPCAM_IMAGE_WB_MODE_AUTO_W			= 1<<5,      //!< NF_IPCAM_IMAGE_WB_MODE_AUTO_W
	NF_IPCAM_IMAGE_WB_MODE_NR				= 6,            //!< NF_IPCAM_IMAGE_WB_MODE_NR

	/* Manual white balance modes */
	NF_IPCAM_IMAGE_MWB_MODE_INDOOR			= 1<<0,     //!< NF_IPCAM_IMAGE_MWB_MODE_INDOOR
	NF_IPCAM_IMAGE_MWB_MODE_OUTDOOR			= 1<<1,    //!< NF_IPCAM_IMAGE_MWB_MODE_OUTDOOR
	NF_IPCAM_IMAGE_MWB_MODE_FLUORESCENT		= 1<<2, //!< NF_IPCAM_IMAGE_MWB_MODE_FLUORESCENT
	NF_IPCAM_IMAGE_MWB_MODE_NR				= 3,            //!< NF_IPCAM_IMAGE_MWB_MODE_NR

	NF_IPCAM_IMAGE_ADAPTIVE_IR_OFF			= 1<<0,
	NF_IPCAM_IMAGE_ADAPTIVE_IR_ON			= 1<<1,
	NF_IPCAM_IMAGE_ADAPTIVE_IR_NR			= 2,

	NF_IPCAM_IMAGE_DEFOG_OFF			= 1<<0,
	NF_IPCAM_IMAGE_DEFOG_ON				= 1<<1,
	NF_IPCAM_IMAGE_DEFOG_LOW			= 1<<2,
	NF_IPCAM_IMAGE_DEFOG_MID			= 1<<3,
	NF_IPCAM_IMAGE_DEFOG_HIGH			= 1<<4,
	NF_IPCAM_IMAGE_DEFOG_X10_OFF			= 1<<5,
	NF_IPCAM_IMAGE_DEFOG_X10_LOW			= 1<<6,
	NF_IPCAM_IMAGE_DEFOG_X10_MID			= 1<<7,
	NF_IPCAM_IMAGE_DEFOG_X10_HIGH			= 1<<8,
	NF_IPCAM_IMAGE_DEFOG_HI_OFF			= 1<<9,	 // Hisilicon
	NF_IPCAM_IMAGE_DEFOG_HI_LOW			= 1<<10, // Hisilicon
	NF_IPCAM_IMAGE_DEFOG_HI_MID			= 1<<11, // Hisilicon
	NF_IPCAM_IMAGE_DEFOG_HI_HIGH			= 1<<12, // Hislilicon
	NF_IPCAM_IMAGE_DEFOG_NR				= 13,

	NF_IPCAM_IMAGE_HLC_OFF				= 1<<0,
	NF_IPCAM_IMAGE_HLC_LOW				= 1<<1,
	NF_IPCAM_IMAGE_HLC_MID				= 1<<2,
	NF_IPCAM_IMAGE_HLC_HIGH				= 1<<3,
	NF_IPCAM_IMAGE_HLC_X10_OFF			= 1<<4,
	NF_IPCAM_IMAGE_HLC_X10_LOW			= 1<<5,
	NF_IPCAM_IMAGE_HLC_X10_MID			= 1<<6,
	NF_IPCAM_IMAGE_HLC_X10_HIGH			= 1<<7,
	NF_IPCAM_IMAGE_HLC_NR				= 8,


	NF_IPCAM_IMAGE_FOCUS_LIMIT_30			= 1<<0,
	NF_IPCAM_IMAGE_FOCUS_LIMIT_100			= 1<<1,
	NF_IPCAM_IMAGE_FOCUS_LIMIT_NR			= 2,

	NF_IPCAM_IMAGE_STABILIZER_OFF			= 1<<0,
	NF_IPCAM_IMAGE_STABILIZER_ON			= 1<<1,
	NF_IPCAM_IMAGE_STABILIZER_NR			= 2,

	NF_IPCAM_IMAGE_IR_CORRECTION_OFF		= 1<<0,
	NF_IPCAM_IMAGE_IR_CORRECTION_ON			= 1<<1,
	NF_IPCAM_IMAGE_IR_CORRECTION_NR			= 2,

} NF_IPCAM_IMAGE_MODES_E;

/** @enum _NF_IPCAM_ALARM_MODEES_E
 *  @brief 카메라 알람 동작 구분.
 */
typedef enum _NF_IPCAM_ALARM_MODES_E {
	NF_IPCAM_ALARM_TYPE_NO					= 1<<0,//!< Normal Open
	NF_IPCAM_ALARM_TYPE_NC					= 1<<1 //!< Normal Close
} NF_IPCAM_ALARM_MODES_E;

/** @enum _NF_IPCAM_ANTI_FLICKER_E
 *  @brief 카메라 antiflicker 모드 구분.
 */
typedef enum _NF_IPCAM_ANTI_FLICKER_E {
	NF_IPCAM_AF_NTSC						= 1<<0,//!< NTSC
	NF_IPCAM_AF_PAL							= 1<<1 //!< PAL
} NF_IPCAM_ANTI_FLICKER_E;

/** @enum _NF_IPCAM_MIRROR_MODES_E
 *  @brief 카메라 mirror 동작 옵션.
 */
typedef enum _NF_IPCAM_MIRROR_MODES_E {
	NF_IPCAM_MIRROR_UNUSED0					= 1<<0, //!< Unused
	NF_IPCAM_MIRROR_NONE					= 1<<1, //!< None
	NF_IPCAM_MIRROR_HORIZONTAL				= 1<<2, //!< Horizontal
	NF_IPCAM_MIRROR_VERTICAL				= 1<<3, //!< Vertical
	NF_IPCAM_MIRROR_FLIP					= 1<<4, //!< Flip
	NF_IPCAM_MIRROR_AXIS_R0					= 1<<5, //!< 
	NF_IPCAM_MIRROR_AXIS_R90				= 1<<6, //!< 
	NF_IPCAM_MIRROR_AXIS_R180				= 1<<7, //!< 
	NF_IPCAM_MIRROR_AXIS_R270				= 1<<8, //!< 
	NF_IPCAM_MIRROR_AXIS_M0					= 1<<9, //!< 
	NF_IPCAM_MIRROR_AXIS_M90				= 1<<10, //!< 
	NF_IPCAM_MIRROR_AXIS_M180				= 1<<11, //!< 
	NF_IPCAM_MIRROR_AXIS_M270				= 1<<12, //!< 
	NF_IPCAM_MIRROR_HDPRO_NONE				= 1<<13,
	NF_IPCAM_MIRROR_HDPRO_R180				= 1<<14,
	NF_IPCAM_MIRROR_HDPRO_HORIZONTAL		= 1<<15,
	NF_IPCAM_MIRROR_HDPRO_VERTICAL			= 1<<16,
	NF_IPCAM_MIRROR_NR						= 17     //!<
} NF_IPCAM_MIRROR_MODES_E;

/** @enum _NF_IPCAM_CAPTURE_MODES_E
 *  @brief 카메라 capture_mode 동작 옵션.
 */
typedef enum _NF_IPCAM_CAPTURE_MODES_E {
	NF_IPCAM_CAPTURE_UNUSED		= 1<<0, //!< Unused
	NF_IPCAM_CAPTURE_5M_30FPS	= 1<<1, //!< 5M 30FPS
	NF_IPCAM_CAPTURE_60FPS		= 1<<2, //!< 60FPS (2M,3M,5M)
	NF_IPCAM_CAPTURE_3M_30FPS_1	= 1<<3, //!< 3M 30FPS (2048x1536) use
	NF_IPCAM_CAPTURE_3M_30FPS_2	= 1<<4, //!< 3M 30FPS (2304x1296)
	NF_IPCAM_CAPTURE_2M_30FPS	= 1<<5, //!< 2M 30FPS 
	NF_IPCAM_CAPTURE_NR			= 6     //!< 
} NF_IPCAM_CAPTURE_MODES_E;

/** @enum _NF_IPCAM_BITRATE_CONTROLS_E
 *  @brief 카메라 bitrate_control 옵션.
 */
typedef enum _NF_IPCAM_BITRATE_CONTROLS_E {
	NF_IPCAM_BITRATE_CONTROL_CBR	= 1<<0, //!< CBR
	NF_IPCAM_BITRATE_CONTROL_VBR 	= 1<<1, //!< VBR
	NF_IPCAM_BITRATE_CONTROL_MBR	= 1<<2, //!< MBR
	NF_IPCAM_BITRATE_CONTROL_VBR_PLUS= 1<<3, //!< VBR+
	NF_IPCAM_BITRATE_CONTROL_NR		= 4     //!< 
} NF_IPCAM_BITRATE_CONTROLS_E;

/** @enum _NF_IPCAM_IMAGE_ONVIF
 *  @brief ONVIF에서 지원하는 이미지 옵션.(ITX전용 옵션 포함)
 */
#define	NF_IPCAM_IMAGE_ONVIF_BRIGHTNESS			SHIFT_64_00 //!< BRIGHTNESS
#define	NF_IPCAM_IMAGE_ONVIF_CONTRAST			SHIFT_64_01 //!< CONTRAST
#define	NF_IPCAM_IMAGE_ONVIF_SHARPNESS			SHIFT_64_02 //!< SHARPNESS
#define	NF_IPCAM_IMAGE_ONVIF_COLOR			SHIFT_64_03 //!< COLOR
#define	NF_IPCAM_IMAGE_ONVIF_FOCUS_MODE			SHIFT_64_04 //!< FOCUS_MODE
#define	NF_IPCAM_IMAGE_ONVIF_FOCUS_DEFAULTSPEED		SHIFT_64_05 //!< FOCUS_DEFAULTSPEED
#define	NF_IPCAM_IMAGE_ONVIF_FOCUS_NEARLIMIT		SHIFT_64_06 //!< FOCUS_NEARLIMIT
#define	NF_IPCAM_IMAGE_ONVIF_FOCUS_FARLIMIT		SHIFT_64_07 //!< FOCUS_FARLIMIT
#define	NF_IPCAM_IMAGE_ONVIF_FOCUS_ONEPUSH		SHIFT_64_08 //!< FOCUS_ONEPUSH
#define	NF_IPCAM_IMAGE_ONVIF_FOCUS_ABPOSITION		SHIFT_64_09 //!< FOCUS_ABPOSITION
#define	NF_IPCAM_IMAGE_ONVIF_FOCUS_ABSPEED		SHIFT_64_10 //!< FOCUS_ABSPEED
#define	NF_IPCAM_IMAGE_ONVIF_FOCUS_REDISTANCE		SHIFT_64_11 //!< FOCUS_REDISTANCE
#define	NF_IPCAM_IMAGE_ONVIF_FOCUS_RESPEED		SHIFT_64_12 //!< FOCUS_RESPEED
#define	NF_IPCAM_IMAGE_ONVIF_FOCUS_COSPEED		SHIFT_64_13 //!< FOCUS_COSPEED
#define	NF_IPCAM_IMAGE_ONVIF_WB_MODE			SHIFT_64_14 //!< WB_MODE
#define	NF_IPCAM_IMAGE_ONVIF_WB_CRGAIN			SHIFT_64_15 //!< WB_CRGAIN
#define	NF_IPCAM_IMAGE_ONVIF_WB_CBGAIN			SHIFT_64_16 //!< WB_CBGAIN
#define	NF_IPCAM_IMAGE_ONVIF_ROTATION			SHIFT_64_17 //!< ROTATION(ITX only)
#define	NF_IPCAM_IMAGE_ONVIF_FOCUS_HOME			SHIFT_64_18 //!< FOCUS_HOME(ITX only)
#define	NF_IPCAM_IMAGE_ONVIF_WB_PRESET			SHIFT_64_19 //!< WB_PRESET(ITX only)
#define	NF_IPCAM_IMAGE_ONVIF_TINT			SHIFT_64_20 //!< TINT(ITX only)
#define	NF_IPCAM_IMAGE_ONVIF_FOCUS_NEARFAR		SHIFT_64_21 //!< FOCUS_NEARFAR(continuous)
#define	NF_IPCAM_IMAGE_ONVIF_FOCUS_LIMIT		SHIFT_64_22 //!< FOCUS_LIMIT
#define	NF_IPCAM_IMAGE_ONVIF_STABILIZER			SHIFT_64_23 //!< STABILIZER
#define	NF_IPCAM_IMAGE_ONVIF_IR_CORRECTION		SHIFT_64_24 //!< IR CORRECTION
#define	NF_IPCAM_IMAGE_ONVIF_NR				25

/** @enum _NF_IPCAM_EXPOSURE_ONVIF
 *  @brief ONVIF에서 지원하는 Exposure 옵션.(ITX전용 옵션 포함)
 */
// _NF_IPCAM_EXPOSURE_ONVIF
#define	NF_IPCAM_EXPOSURE_ONVIF_MODE		SHIFT_64_00
#define	NF_IPCAM_EXPOSURE_ONVIF_PRIORITY	SHIFT_64_01
#define	NF_IPCAM_EXPOSURE_ONVIF_MINETIME	SHIFT_64_02
#define	NF_IPCAM_EXPOSURE_ONVIF_MAXETIME	SHIFT_64_03
#define	NF_IPCAM_EXPOSURE_ONVIF_ETIME		SHIFT_64_04
#define	NF_IPCAM_EXPOSURE_ONVIF_MINGAIN		SHIFT_64_05
#define	NF_IPCAM_EXPOSURE_ONVIF_MAXGAIN		SHIFT_64_06
#define	NF_IPCAM_EXPOSURE_ONVIF_GAIN		SHIFT_64_07
#define	NF_IPCAM_EXPOSURE_ONVIF_MINIRIS		SHIFT_64_08
#define	NF_IPCAM_EXPOSURE_ONVIF_MAXIRIS		SHIFT_64_09
#define	NF_IPCAM_EXPOSURE_DCIRIS		SHIFT_64_10
#define	NF_IPCAM_EXPOSURE_ONVIF_BOTTOM		SHIFT_64_11
#define	NF_IPCAM_EXPOSURE_ONVIF_TOP		SHIFT_64_12
#define	NF_IPCAM_EXPOSURE_ONVIF_RIGHT		SHIFT_64_13
#define	NF_IPCAM_EXPOSURE_ONVIF_LEFT		SHIFT_64_14
#define	NF_IPCAM_EXPOSURE_SLOWSHUTTER		SHIFT_64_15
#define	NF_IPCAM_EXPOSURE_MAXAGC		SHIFT_64_16
#define	NF_IPCAM_EXPOSURE_ONVIF_IRIS		SHIFT_64_17
#define	NF_IPCAM_EXPOSURE_DUMMY			SHIFT_64_18
#define	NF_IPCAM_EXPOSURE_ANTI_FLICKER		SHIFT_64_19
#define	NF_IPCAM_EXPOSURE_MAX_SHUTTER_50	SHIFT_64_20
#define	NF_IPCAM_EXPOSURE_MAX_SHUTTER_60	SHIFT_64_21
#define	NF_IPCAM_EXPOSURE_ONVIF_BLC_MODE	SHIFT_64_22
#define	NF_IPCAM_EXPOSURE_ONVIF_BLC_LEVEL	SHIFT_64_23
#define	NF_IPCAM_EXPOSURE_MAX_SHUTTER_OFF	SHIFT_64_24
#define	NF_IPCAM_EXPOSURE_DNR_MODE		SHIFT_64_25
#define	NF_IPCAM_EXPOSURE_ONVIF_WDR_MODE	SHIFT_64_26 
#define	NF_IPCAM_EXPOSURE_ONVIF_WDR_LEVEL	SHIFT_64_27 
#define	NF_IPCAM_EXPOSURE_ONVIF_IRCUT		SHIFT_64_28 
#define	NF_IPCAM_EXPOSURE_ONVIF_DNN_TOGGLE	SHIFT_64_29
#define	NF_IPCAM_EXPOSURE_ONVIF_ADAPTIVEIR	SHIFT_64_30 
#define	NF_IPCAM_EXPOSURE_ONVIF_DNN_SENSE_NTOD	SHIFT_64_31 
#define	NF_IPCAM_EXPOSURE_ONVIF_DNN_SENSE_DTON	SHIFT_64_32 
#define	NF_IPCAM_EXPOSURE_ONVIF_DEFOG		SHIFT_64_33 
#define	NF_IPCAM_EXPOSURE_ONVIF_HLC		SHIFT_64_34 
#define	NF_IPCAM_EXPOSURE_ONVIF_IRCUTM		SHIFT_64_35 
#define	NF_IPCAM_EXPOSURE_MAX_SHUTTER_MOTION_OFF	SHIFT_64_36 
#define	NF_IPCAM_EXPOSURE_ONVIF_DC_IRIS_CAL			SHIFT_64_37 
#define	NF_IPCAM_EXPOSURE_ANTI_FLICKER_MOTION		SHIFT_64_38 
#define NF_IPCAM_EXPOSURE_MAX_SHUTTER_MOTION_OFF_ON	SHIFT_64_39
#define NF_IPCAM_EXPOSURE_MAX_SHUTTER_AUTO_OFF_OFF	SHIFT_64_40
#define NF_IPCAM_EXPOSURE_MAX_SHUTTER_AUTO_OFF_ON_TV	SHIFT_64_41
#define NF_IPCAM_EXPOSURE_MAX_SHUTTER_AUTO_OFF_ON	SHIFT_64_42
#define	NF_IPCAM_EXPOSURE_ANTI_FLICKER_MOTION_OFF	SHIFT_64_43
#define NF_IPCAM_EXPOSURE_ANTI_FLICKER_AUTO_OFF		SHIFT_64_44
#define	NF_IPCAM_EXPOSURE_BASE_SHUTTER_50			SHIFT_64_45
#define	NF_IPCAM_EXPOSURE_BASE_SHUTTER_60			SHIFT_64_46
#define NF_IPCAM_EXPOSURE_BASE_SHUTTER_100          SHIFT_64_47
#define NF_IPCAM_EXPOSURE_BASE_SHUTTER_120          SHIFT_64_48
#define NF_IPCAM_EXPOSURE_BASE_SHUTTER_100_300      SHIFT_64_49
#define NF_IPCAM_EXPOSURE_BASE_SHUTTER_100_5000     SHIFT_64_50
#define NF_IPCAM_EXPOSURE_BASE_SHUTTER_120_360      SHIFT_64_51
#define NF_IPCAM_EXPOSURE_BASE_SHUTTER_120_5000     SHIFT_64_52
#define NF_IPCAM_EXPOSURE_BASE_SHUTTER_120_262      SHIFT_64_53
#define NF_IPCAM_EXPOSURE_BASE_SHUTTER_30_262       SHIFT_64_54
#define NF_IPCAM_EXPOSURE_BASE_SHUTTER_25_100       SHIFT_64_55
#define NF_IPCAM_EXPOSURE_BASE_SHUTTER_25_300       SHIFT_64_56
#define NF_IPCAM_EXPOSURE_BASE_SHUTTER_25_5000      SHIFT_64_57
#define NF_IPCAM_EXPOSURE_BASE_SHUTTER_30_120       SHIFT_64_58
#define NF_IPCAM_EXPOSURE_BASE_SHUTTER_30_360       SHIFT_64_59
#define NF_IPCAM_EXPOSURE_BASE_SHUTTER_30_5000      SHIFT_64_60
#define	NF_IPCAM_EXPOSURE_DCIRIS_MOTION				SHIFT_64_61
#define NF_IPCAM_EXPOSURE_DN_SCHEDULE				SHIFT_64_62
#define	NF_IPCAM_EXPOSURE_DNR_MODE_AUTO_SMART		SHIFT_64_63
#define	NF_IPCAM_EXPOSURE_ONVIF_NR		64	

/* Focus Tab */
#define NF_IPCAM_FOCUS_DNN_COMP			SHIFT_64_00
#define NF_IPCAM_FOCUS_TEM_COMP			SHIFT_64_01

/** @enum _NF_IPCAM_PTZ_ONVIF
 *  @brief ONVIF에서 지원하는 PTZ 기능.
 */
typedef enum _NF_IPCAM_PTZ_ONVIF {
	NF_IPCAM_PTZ_ONVIF_ABSOLUTE_PANTILT		= 1<<0, //!< ABSOLUTE_PANTILT
	NF_IPCAM_PTZ_ONVIF_ABSOLUTE_ZOOM		= 1<<1, //!< ABSOLUTE_ZOOM
	NF_IPCAM_PTZ_ONVIF_RELATIVE_PANTILT		= 1<<2, //!< RELATIVE_PANTILT
	NF_IPCAM_PTZ_ONVIF_RELATIVE_ZOOM		= 1<<3, //!< RELATIVE_ZOOM
	NF_IPCAM_PTZ_ONVIF_CONTINUOUS_PANTILT	= 1<<4, //!< CONTINUOUS_PANTILT
	NF_IPCAM_PTZ_ONVIF_CONTINUOUS_ZOOM		= 1<<5, //!< CONTINUOUS_ZOOM
	NF_IPCAM_PTZ_ONVIF_GOTOHOME				= 1<<6, //!< GOTOHOME
	NF_IPCAM_PTZ_ONVIF_SETHOME				= 1<<7, //!< SETHOME
	NF_IPCAM_PTZ_ONVIF_PRESET				= 1<<8, //!< PRESET
	NF_IPCAM_PTZ_ONVIF_AUXILIARY			= 1<<9, //!< AUXILIARY
	NF_IPCAM_PTZ_ONVIF_NR					= 10    //!<
} NF_IPCAM_PTZ_ONVIF;

/** @enum _NF_IPCAM_IMAGE_MODE_ONVIF
 *  @brief ONVIF카메라 이미지, Exposure 설정 옵션 들.
 *
 *  @note ITX옵션들은 _NF_IPCAM_IMAGE_MODES_E의 값과 동일하여야 한다.\n
 *  ex - NF_IPCAM_EXPOSURE_MODE_ITX_MANUAL == NF_IPCAM_IMAGE_EXP_MODE_MANUAL
 *
 *  @see _NF_IPCAM_IMAGE_MODES_E
 */
typedef enum _NF_IPCAM_IMAGE_MODE_ONVIF {
	// max no. of this
	NF_IPCAM_MODE_ONVIF_NR_MAX				= 10,    //!<
	// exposure
	NF_IPCAM_EXPOSURE_MODE_DUMMY			= 1<<0,  //!< DUMMY
	NF_IPCAM_EXPOSURE_MODE_ONVIF_AUTO		= 1<<1,  //!< ONVIF_AUTO
	NF_IPCAM_EXPOSURE_MODE_ONVIF_MANUAL		= 1<<2,  //!< ONVIF_MANUAL
	//
	NF_IPCAM_EXPOSURE_MODE_ITX_MANUAL		= 1<<4,  //!< ITX_MANUAL
	NF_IPCAM_EXPOSURE_MODE_ITX_AUTO_INDOOR		= 1<<5,  //!< ITX_AUTO_INDOOR
	NF_IPCAM_EXPOSURE_MODE_ITX_AUTO_OUTDOOR		= 1<<6,  //!< ITX_AUTO_OUTDOOR
	NF_IPCAM_EXPOSURE_MODE_ITX_AUTO			= 1<<7,  //!< ITX_AUTO
	NF_IPCAM_EXPOSURE_MODE_ITX_AUTO_MOTION		= 1<<8,  //!< ITX_AUTO_MOTION
	NF_IPCAM_EXPOSURE_MODE_ITX_AUTO_I3		= 1<<9,  //!< ITX_AUTO_I3
	NF_IPCAM_EXPOSURE_MODE_ITX_MANUAL_I3		= 1<<10,  //!< ITX_MANUAL_I3
	NF_IPCAM_EXPOSURE_MODE_ITX_AUTO_INX		= 1<<11, //!< ITX_AUTO_INX
	NF_IPCAM_EXPOSURE_MODE_ITX_AUTO_MOTION_INX	= 1<<12, //!< ITX_AUTO_MOTION_INX
	NF_IPCAM_EXPOSURE_MODE_ITX_MANUAL_INX		= 1<<13, //!< ITX_MANUAL_INX
	NF_IPCAM_EXPOSURE_MODE_ITX_AUTO_NPT		= 1<<14, //!< NF_IPCAM_IMAGE_EXP_MODE_AUTO_NPT
	NF_IPCAM_EXPOSURE_MODE_ITX_MANUAL_NPT		= 1<<15, //!< NF_IPCAM_IMAGE_EXP_MODE_MANUAL_NPT
	NF_IPCAM_EXPOSURE_MODE_ITX_AUTO_NPT_X10		= 1<<16, //!< NF_IPCAM_IMAGE_EXP_MODE_AUTO_NPT
	NF_IPCAM_EXPOSURE_MODE_ITX_MANUAL_NPT_X10	= 1<<17, //!< NF_IPCAM_IMAGE_EXP_MODE_MANUAL_NPT
	NF_IPCAM_EXPOSURE_MODE_HI_AUTO_MOTION		= 1<<18, //!< HISILICON AUTO(motion priority)
	NF_IPCAM_EXPOSURE_MODE_HI_AUTO				= 1<<19, //!< HISILICON AUTO
	NF_IPCAM_EXPOSURE_MODE_HI_MANUAL			= 1<<20, //!< HISILICON AUTO
	NF_IPCAM_EXPOSURE_MODE_HI_AUTO_MOTION_INDH	= 1<<21, //!< HISILICON AUTO(motion priority, INDH)
	NF_IPCAM_EXPOSURE_MODE_AXIS_AUTO			= 1<<22, //!< Axis Automatic
	NF_IPCAM_EXPOSURE_MODE_AXIS_FREE_50HZ		= 1<<23, //!< AXIS 50
	NF_IPCAM_EXPOSURE_MODE_AXIS_FREE_60HZ		= 1<<24, //!< AXIS 60
	NF_IPCAM_EXPOSURE_MODE_AXIS_HOLD			= 1<<25, //!< AXIS H.c
	NF_IPCAM_EXPOSURE_MODE_AXIS_REDUECED_50HZ	= 1<<26, //!< AXIS R 50
	NF_IPCAM_EXPOSURE_MODE_AXIS_REDUECED_60HZ	= 1<<27, //!< AXIS 5 60
	NF_IPCAM_EXPOSURE_MODE_ONVIF_NR				= 28,    //!<

	// exposure.priority
	NF_IPCAM_PRIORITY_MODE_ONVIF_LOWNOISE	= 1<<0,  //!< ONVIF_LOWNOISE
	NF_IPCAM_PRIORITY_MODE_ONVIF_FRAMERATE	= 1<<1,  //!< ONVIF_FRAMERATE
	NF_IPCAM_PRIORITY_MODE_ONVIF_DEFAULT	= 1<<2,  //!< ONVIF_Default//include AXIS Default
	NF_IPCAM_PRIORITY_MODE_ONVIF_MOTION		= 1<<3,  //!< ONVIF_Motion//include AXIS Motion
	NF_IPCAM_PRIORITY_MODE_ONVIF_NR			= 4,     //!<
	// focus
	NF_IPCAM_FOCUS_MODE_DUMMY				= 1<<0,  //!< DUMMY
	NF_IPCAM_FOCUS_MODE_ONVIF_AUTO			= 1<<1,  //!< ONVIF_AUTO
	NF_IPCAM_FOCUS_MODE_ONVIF_ABSOLUTE		= 1<<2,  //!< ONVIF_ABSOLUTE
	NF_IPCAM_FOCUS_MODE_ONVIF_RELATIVE		= 1<<3,  //!< ONVIF_RELATIVE
	NF_IPCAM_FOCUS_MODE_ONVIF_CONTINUOUS	= 1<<4,  //!< ONVIF_CONTINUOUS
	NF_IPCAM_FOCUS_MODE_ITX_CONTINUOUS		= 1<<5,  //!< ITX_CONTINUOUS
	NF_IPCAM_FOCUS_MODE_ITX_ABSOLUTE		= 1<<6,  //!< ITX_ABSOLUTE
	NF_IPCAM_FOCUS_MODE_ITX_AUTO			= 1<<7,  //!< ITX_AUTO
	NF_IPCAM_FOCUS_MODE_ITX_SEMI_AUTO		= 1<<8,  //!< ITX_SEMI_AUTO
	NF_IPCAM_FOCUS_MODE_ONVIF_NR			= 9,     //!<
	// ircut filter
	NF_IPCAM_IRCUT_MODE_ITX_AUTO			= 1<<0,  //!< ITX_AUTO
	NF_IPCAM_IRCUT_MODE_ITX_DAYTIME			= 1<<1,  //!< ITX_DAYTIME
	NF_IPCAM_IRCUT_MODE_ITX_NIGHTTIME		= 1<<2,  //!< ITX_NIGHTTIME
	NF_IPCAM_IRCUT_MODE_ONVIF_ON			= 1<<3,  //!< ONVIF_ON
	NF_IPCAM_IRCUT_MODE_ONVIF_OFF			= 1<<4,  //!< ONVIF_OFF
	NF_IPCAM_IRCUT_MODE_ONVIF_AUTO			= 1<<5,  //!< ONVIF_AUTO
	NF_IPCAM_IRCUT_MODE_DUMMY				= 1<<6,  //!< DUMMY
	NF_IPCAM_IRCUT_MODE_NPT_AUTO			= 1<<7,  //!< NPT_AUTO
	NF_IPCAM_IRCUT_MODE_NPT_DAYTIME			= 1<<8,  //!< NPT_DAYTIME
	NF_IPCAM_IRCUT_MODE_NPT_NIGHTTIME		= 1<<9,  //!< NPT_NIGHTTIME
	NF_IPCAM_IRCUT_MODE_NPT3_AUTO			= 1<<10,  //!< NPT3_AUTO
	NF_IPCAM_IRCUT_MODE_NPT3_DAYTIME		= 1<<11,  //!< NPT3_DAYTIME
	NF_IPCAM_IRCUT_MODE_NPT3_NIGHTTIME		= 1<<12,  //!< NPT3_NIGHTTIME
	NF_IPCAM_IRCUT_MODE_ITX_SCHEDULE		= 1<<13,  //!< NPT3_SCHEDULE
	NF_IPCAM_IRCUT_MODE_AXIS_AUTO			= 1<<14,  //!< ONVIF_ON
	NF_IPCAM_IRCUT_MODE_AXIS_ON				= 1<<15,  //!< ONVIF_ON
	NF_IPCAM_IRCUT_MODE_AXIS_OFF			= 1<<16,  //!< ONVIF_ON
	NF_IPCAM_IRCUT_MODE_ITX_EXTERNAL		= 1<<17,  //!< ITX_EXTERNAL
	NF_IPCAM_IRCUT_MODE_ONVIF_NR			= 18,     //!<
	// wide dynamic range
	NF_IPCAM_WDR_MODE_DUMMY					= 1<<0,  //!< DUMMY
	NF_IPCAM_WDR_MODE_ONVIF_OFF				= 1<<1,  //!< ONVIF_OFF//Axis 
	NF_IPCAM_WDR_MODE_ONVIF_ON				= 1<<2,  //!< ONVIF_ON//Axis
	NF_IPCAM_WDR_MODE_ITX_OFF				= 1<<3,  //!< ITX_OFF
	NF_IPCAM_WDR_MODE_ITX_ON				= 1<<4,  //!< ITX_ON
	NF_IPCAM_WDR_MODE_ITX_AUTO_LOW			= 1<<5,  //!< ITX_AUTO_LOW
	NF_IPCAM_WDR_MODE_ITX_AUTO_MID			= 1<<6,  //!< ITX_AUTO_MID
	NF_IPCAM_WDR_MODE_ITX_AUTO_HIGH			= 1<<7,  //!< ITX_AUTO_HIGH
	NF_IPCAM_WDR_MODE_ITX_LOW				= 1<<8,  //!< ITX_LOW
	NF_IPCAM_WDR_MODE_ITX_MID				= 1<<9,  //!< ITX_MID
	NF_IPCAM_WDR_MODE_ITX_HIGH				= 1<<10, //!< ITX_HIGH
	NF_IPCAM_WDR_MODE_ITX_ON2				= 1<<11, //!< ITX_HIGH
	NF_IPCAM_WDR_MODE_ITX_NPT_LOW				= 1<<12,  //!< ITX_LOW
	NF_IPCAM_WDR_MODE_ITX_NPT_MID				= 1<<13,  //!< ITX_MID
	NF_IPCAM_WDR_MODE_ITX_NPT_HIGH				= 1<<14, //!< ITX_HIGH
	NF_IPCAM_WDR_MODE_ITX_NPTEH_ON				= 1<<15,  //!< ITX_ON
	NF_IPCAM_WDR_MODE_ITX_NPTEH_AUTO_LOW			= 1<<16,  //!< ITX_AUTO_LOW
	NF_IPCAM_WDR_MODE_ITX_NPTEH_AUTO_MID			= 1<<17,  //!< ITX_AUTO_MID
	NF_IPCAM_WDR_MODE_ITX_NPTEH_AUTO_HIGH			= 1<<18,  //!< ITX_AUTO_HIGH
	NF_IPCAM_WDR_MODE_ITX_INX_ON				= 1<<19,  //!< ITX_AUTO_HIGH
	NF_IPCAM_WDR_MODE_HI_LOW			= 1<<20,  //!< HIsilicon
	NF_IPCAM_WDR_MODE_HI_MID			= 1<<21,  //!< HIsilicon
	NF_IPCAM_WDR_MODE_HI_HIGH			= 1<<22,  //!< HIsilicon
	NF_IPCAM_WDR_MODE_ITX_INXH_ON			= 1<<23,  //!< HIsilicon ON 
	NF_IPCAM_WDR_MODE_HI2_OFF				= 1<<24,  //!< HIsilicon ON 
	NF_IPCAM_WDR_MODE_HI2_ON				= 1<<25,  //!< HIsilicon ON 
	NF_IPCAM_WDR_MODE_HI2_LOW				= 1<<26,  //!< HIsilicon LOW 
	NF_IPCAM_WDR_MODE_HI2_MID				= 1<<27,  //!< HIsilicon MID 
	NF_IPCAM_WDR_MODE_HI2_HIGH				= 1<<28,  //!< HIsilicon HIGH 
	NF_IPCAM_WDR_MODE_HI2_ON2				= 1<<29,  //!< HIsilicon ON2 (Mini TWDR 2M) 
	NF_IPCAM_WDR_MODE_ONVIF_NR				= 30,    //!<
	
	
	// white balance
	NF_IPCAM_WB_MODE_DUMMY					= 1<<0,  //!< DUMMY
	NF_IPCAM_WB_MODE_ONVIF_MANUAL			= 1<<1,  //!< ONVIF_MANUAL
	//
	NF_IPCAM_WB_MODE_ITX_MANUAL				= 1<<3,  //!< ITX_MANUAL
	NF_IPCAM_WB_MODE_ONVIF_AUTO				= 1<<4,  //!< ONVIF_AUTO
	NF_IPCAM_WB_MODE_ITX_AUTO_W				= 1<<5,  //!< ITX_AUTO_W
	NF_IPCAM_WB_MODE_AXIS_AUTO				= 1<<6,	 //!< AXIS AUTO
	NF_IPCAM_WB_MODE_AXIS_AUTO_OUT			= 1<<7,	 //!< AXIS AUTO outdoor
	NF_IPCAM_WB_MODE_AXIS_HOLD				= 1<<8,	 //!< AXIS HOLD current
	NF_IPCAM_WB_MODE_AXIS_FIXED_OUT1		= 1<<9,	 //!< AXIS FIXED outdoor1
	NF_IPCAM_WB_MODE_AXIS_FIXED_OUT2		= 1<<10, //!< AXIS FIXED outdoor2
	NF_IPCAM_WB_MODE_AXIS_FIXED_IN			= 1<<11, //!< AXIS FIXED indoor
	NF_IPCAM_WB_MODE_AXIS_FIXED_FLUORE1		= 1<<12, //!< AXIS FIXED fluorescent1
	NF_IPCAM_WB_MODE_AXIS_FIXED_FLUORE2		= 1<<13, //!< AXIS FIXED fluorescent2
	NF_IPCAM_WB_MODE_AXIS_MANUAL			= 1<<14, //!< AXIS MANUAL
	NF_IPCAM_WB_MODE_ONVIF_NR				= 15,     //!<
	// backlight mode
	NF_IPCAM_BLC_MODE_ONVIF_OFF				= 1<<0,  //!< ONVIF_OFF
	NF_IPCAM_BLC_MODE_ONVIF_ON				= 1<<1,  //!< ONVIF_ON
	NF_IPCAM_BLC_MODE_DUMMY					= 1<<2,  //!< DUMMY
	NF_IPCAM_BLC_MODE_ITX_ADAPTIVE			= 1<<3,  //!< ITX_ADAPTIVE
	NF_IPCAM_BLC_MODE_ITX_ZONE_LOWER		= 1<<4,  //!< ITX_ZONE_LOWER
	NF_IPCAM_BLC_MODE_ITX_ZONE_MIDDLE		= 1<<5,  //!< ITX_ZONE_MIDDLE
	NF_IPCAM_BLC_MODE_ITX_ZONE_UPPER		= 1<<6,  //!< ITX_ZONE_UPPER
	NF_IPCAM_BLC_MODE_ITX_ZONE_LEFT			= 1<<7,  //!< ITX_ZONE_LEFT
	NF_IPCAM_BLC_MODE_ITX_ZONE_RIGHT		= 1<<8,  //!< ITX_ZONE_RIGHT
	NF_IPCAM_BLC_MODE_NPT_OFF			= 1<<9,   //!< MODE_PTZ_OFF
	NF_IPCAM_BLC_MODE_NPT_ON			= 1<<10,   //!< MODE_PTZ_ON
	NF_IPCAM_BLC_MODE_AXIS_ON				= 1<<11,   //!< AXIS_ON
	NF_IPCAM_BLC_MODE_AXIS_OFF				= 1<<12,   //!< AXIS_OFF
	NF_IPCAM_BLC_MODE_ONVIF_NR				= 13,     //!<
	// focus move option
	/*
	NF_IPCAM_FOCUS_MOVE_ONVIF_ABSOLUTE		= 1<<0,
	NF_IPCAM_FOCUS_MOVE_ONVIF_RELATIVE		= 1<<1,
	NF_IPCAM_FOCUS_MOVE_ONVIF_CONTINUOUS	= 1<<2,
	NF_IPCAM_FOCUS_MOVE_ITX_CONTINUOUS		= 1<<3,
	NF_IPCAM_FOCUS_MOVE_ONVIF_NR			= 4
	*/
	NF_IPCAM_PTZ_MODE_ONVIF_ABSOLUTE		= 1<<0,  //!< ABSOLUTE
	NF_IPCAM_PTZ_MODE_ONVIF_RELATIVE		= 1<<1,  //!< RELATIVE
	NF_IPCAM_PTZ_MODE_ONVIF_CONTINUOUS		= 1<<2,  //!< CONTINUOUS
	NF_IPCAM_PTZ_MODE_ONVIF_NR				= 3,     //!<
	// anti-flicker
	NF_IPCAM_ANTI_FLICKER_MODE_60HZ			= 1<<0,  //!< 60HZ
	NF_IPCAM_ANTI_FLICKER_MODE_50HZ			= 1<<1,  //!< 50HZ
	NF_IPCAM_ANTI_FLICKER_MODE_OFF			= 1<<2,  //!< OFF
	NF_IPCAM_ANTI_FLICKER_NPT_MODE_OFF		= 1<<3,  //!< OFF
	NF_IPCAM_ANTI_FLICKER_NPT_MODE_ON		= 1<<4,  //!< OFF
	NF_IPCAM_ANTI_FLICKER_NPT_X10_MODE_OFF	= 1<<5,  //!< OFF
	NF_IPCAM_ANTI_FLICKER_NPT_X10_MODE_ON	= 1<<6,  //!< OFF
	NF_IPCAM_ANTI_FLICKER_MODE_MOTION_OFF	= 1<<7, //!< HISILICON
	NF_IPCAM_ANTI_FLICKER_MODE_HI_MOTION_OFF = 1<<8, //!< HISILICON Exposure(Motion) OFF
	NF_IPCAM_ANTI_FLICKER_MODE_HI_AUTO_OFF		= 1<<9, //!< HISILICON Exposure(Auto) OFF
	NF_IPCAM_ANTI_FLICKER_MODE_NR			= 10,     //!<
	// max shutter speed
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_25		= 1<<0,  //!< PAL_25
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_50		= 1<<1,  //!< PAL_50
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_100		= 1<<2,  //!< PAL_100
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_150		= 1<<3,  //!< PAL_150
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_200		= 1<<4,  //!< PAL_200
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_250		= 1<<5,  //!< PAL_250
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_300		= 1<<6,  //!< PAL_300
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_500		= 1<<7,  //!< PAL_500
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_800		= 1<<8,  //!< PAL_800
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_1000		= 1<<9,  //!< PAL_1000
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_1500		= 1<<10,  //!< PAL1500
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_2000		= 1<<11,  //!< PAL_2000
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_2500		= 1<<12,  //!< PAL_2500
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_3000		= 1<<13,  //!< PAL_3000
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_4000		= 1<<14,  //!< PAL_4000
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_5000		= 1<<15,  //!< PAL_5000
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_262		= 1<<16,  //!< PAL_242
	NF_IPCAM_MAX_SHUTTER_MODE_PAL_NR		= 17,     //!<

	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_30		= 1<<0,  //!< NTSC_30
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_60		= 1<<1,  //!< NTSC_60
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_120		= 1<<2,  //!< NTSC_120
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_180		= 1<<3,  //!< NTSC_180
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_240		= 1<<4,  //!< NTSC_240
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_300		= 1<<5,  //!< NTSC_300
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_360		= 1<<6,  //!< NTSC_360
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_500		= 1<<7,  //!< NTSC_500
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_800		= 1<<8,  //!< NTSC_800
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_1000		= 1<<9,  //!< NTSC_1000
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_1500		= 1<<10,  //!< NTSC_1500
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_2000		= 1<<11,  //!< NTSC_2000
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_2500		= 1<<12,  //!< NTSC_2500
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_3000		= 1<<13,  //!< NTSC_3000
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_4000		= 1<<14,  //!< NTSC_4000
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_5000		= 1<<15,  //!< NTSC_5000
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_262		= 1<<16,  //!< NTSC_242
	NF_IPCAM_MAX_SHUTTER_MODE_NTSC_NR		= 17,     //!<

	NF_IPCAM_BASE_SHUTTER_MODE_PAL_25		= 1<<0,  //!< PAL_25
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_50		= 1<<1,  //!< PAL_50
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_100		= 1<<2,  //!< PAL_100
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_150		= 1<<3,  //!< PAL_150
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_200		= 1<<4,  //!< PAL_200
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_250		= 1<<5,  //!< PAL_250
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_300		= 1<<6,  //!< PAL_300
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_500		= 1<<7,  //!< PAL_500
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_800		= 1<<8,  //!< PAL_800
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_1000		= 1<<9,  //!< PAL_1000
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_1500		= 1<<10,  //!< PAL1500
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_2000		= 1<<11,  //!< PAL_2000
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_2500		= 1<<12,  //!< PAL_2500
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_3000		= 1<<13,  //!< PAL_3000
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_4000		= 1<<14,  //!< PAL_4000
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_5000		= 1<<15,  //!< PAL_5000
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_262		= 1<<16,  //!< PAL_242
	NF_IPCAM_BASE_SHUTTER_MODE_PAL_NR		= 17,     //!<

	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_30		= 1<<0,  //!< NTSC_30
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_60		= 1<<1,  //!< NTSC_60
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_120		= 1<<2,  //!< NTSC_120
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_180		= 1<<3,  //!< NTSC_180
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_240		= 1<<4,  //!< NTSC_240
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_300		= 1<<5,  //!< NTSC_300
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_360		= 1<<6,  //!< NTSC_360
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_500		= 1<<7,  //!< NTSC_500
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_800		= 1<<8,  //!< NTSC_800
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_1000	= 1<<9,  //!< NTSC_1000
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_1500	= 1<<10,  //!< NTSC_1500
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_2000	= 1<<11,  //!< NTSC_2000
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_2500	= 1<<12,  //!< NTSC_2500
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_3000	= 1<<13,  //!< NTSC_3000
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_4000	= 1<<14,  //!< NTSC_4000
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_5000	= 1<<15,  //!< NTSC_5000
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_262		= 1<<16,  //!< NTSC_242
	NF_IPCAM_BASE_SHUTTER_MODE_NTSC_NR		= 17,     //!<

	// dnr mode
	NF_IPCAM_DNR_MODE_DUMMY					= 1<<0,  //!< DUMMY
	NF_IPCAM_DNR_MODE_OFF					= 1<<1,  //!< OFF
	NF_IPCAM_DNR_MODE_AUTO_LOW				= 1<<2,  //!< AUTO_LOW
	NF_IPCAM_DNR_MODE_AUTO_MID				= 1<<3,  //!< AUTO_MID
	NF_IPCAM_DNR_MODE_AUTO_HIGH				= 1<<4,  //!< AUTO_HIGH
	NF_IPCAM_DNR_MODE_MANUAL_LOW			= 1<<5,  //!< MANUAL_LOW
	NF_IPCAM_DNR_MODE_MANUAL_MID			= 1<<6,  //!< MANUAL_MID
	NF_IPCAM_DNR_MODE_MANUAL_HIGH			= 1<<7,  //!< MANUAL_HIGH
	NF_IPCAM_DNR_MODE_AUTO_SMART			= 1<<8,  //!< AUTO_SMART
	NF_IPCAM_DNR_MODE_NR					= 9,     //!<

	// Adaptive IR
	NF_IPCAM_ADAPTIVE_IR_OFF			= 1<<0,	// !< OFF
	NF_IPCAM_ADAPTIVE_IR_ON				= 1<<1,	// !< ON
	NF_IPCAM_ADAPTIVE_IR_NR				= 2,	// !< ON

	// DEFOG
	NF_IPCAM_DEFOG_OFF				= 1<<0,
	NF_IPCAM_DEFOG_ON				= 1<<1,
	NF_IPCAM_DEFOG_LOW				= 1<<2,
	NF_IPCAM_DEFOG_MID				= 1<<3,
	NF_IPCAM_DEFOG_HIGH				= 1<<4,
	NF_IPCAM_DEFOG_X10_OFF				= 1<<5,
	NF_IPCAM_DEFOG_X10_LOW				= 1<<6,
	NF_IPCAM_DEFOG_X10_MID				= 1<<7,
	NF_IPCAM_DEFOG_X10_HIGH				= 1<<8,
	NF_IPCAM_DEFOG_HI_OFF				= 1<<9,	 // Hisilicon
	NF_IPCAM_DEFOG_HI_LOW				= 1<<10, // Hisilicon
	NF_IPCAM_DEFOG_HI_MID				= 1<<11, // Hisilicon
	NF_IPCAM_DEFOG_HI_HIGH				= 1<<12, // Hislilicon
	NF_IPCAM_DEFOG_NR				= 13,

	// HLC
	NF_IPCAM_HLC_OFF				= 1<<0,
	NF_IPCAM_HLC_LOW				= 1<<1,
	NF_IPCAM_HLC_MID				= 1<<2,
	NF_IPCAM_HLC_HIGH				= 1<<3,
	NF_IPCAM_HLC_X10_OFF				= 1<<4,
	NF_IPCAM_HLC_X10_LOW				= 1<<5,
	NF_IPCAM_HLC_X10_MID				= 1<<6,
	NF_IPCAM_HLC_X10_HIGH				= 1<<7,
	NF_IPCAM_HLC_NR					= 8,

	// Focus Limit
	NF_IPCAM_FOCUS_LIMIT_30				= 1<<0,
	NF_IPCAM_FOCUS_LIMIT_100			= 1<<1,
	NF_IPCAM_FOCUS_LIMIT_NR				= 2,

	// Stabilizer
	NF_IPCAM_STABILIZER_OFF				= 1<<0,
	NF_IPCAM_STABILIZER_ON				= 1<<1,
	NF_IPCAM_STABILIZER_NR				= 2,

	// IR Correction
	NF_IPCAM_IR_CORRECTION_OFF			= 1<<0,
	NF_IPCAM_IR_CORRECTION_ON			= 1<<1,
	NF_IPCAM_IR_CORRECTION_NR			= 2,
    
	// COLORVU_CTRL
	NF_IPCAM_COLORVU_CTRL_NONE   		= 1<<0,
	NF_IPCAM_COLORVU_CTRL_MANUAL		= 1<<1,
	NF_IPCAM_COLORVU_CTRL_AUTO 			= 1<<2,
	NF_IPCAM_COLORVU_CTRL_NR            = 3,

} NF_IPCAM_IMAGE_MODE_ONVIF;

/** 
 * @enum _NF_IPCAM_AUXILIARY_CATEGORY_ONVIF
 * @brief ONVIF 카메라의 Auxiliary 기능 카테고리
 */
enum _NF_IPCAM_AUXILIARY_CATEGORY_ONVIF
{
	AUXILIARY_CATEGORY_DEVICE,
	AUXILIARY_CATEGORY_PTZ
};

typedef struct _NFIPCamEncoderCap NFIPCamEncoderCap;

/** @struct _NFIPCamEncoderCap
 *  @brief Encoder(Stream Setup) 설정 capability struct.
 */
struct _NFIPCamEncoderCap
{
	gint ch;					//!< 채널 번호.
	gint encoder_cnt;			//!< Stream 수.

	uint64_t res_support[3];		//!< 해상도 지원 bitmask.
	guint fps_max[3];			//!< 최대 fps.
	guint bitrate_max[3];		//!< 최대 bitrate.
	guint bitrate_min[3];		//!< 최소 bitrate.
	guint bitctrl_support[3];	//!< bitrate control 지원 .
	guint vcodec_support[3];

	uint64_t res_default[3];		//!< 현재 해상도.
	guint fps_max_default[3];	//!< 현재 fps.
	guint br_max_default[3];	//!< 현재 최대 bitrate.
	guint br_min_default[3];	//!< 현재 최소 bitrate.
	guint bitctrl_default[3];	//!< 현재 bitrate control.
	guint vcodec_default[3];
};


typedef struct _NFIPCamSetupVCodec	NFIPCamSetupVCodec;

/** @struct _NFIPCamSetupVCodec
 *  @brief 비디오 스트림 설정 옵션 struct.
 */
struct _NFIPCamSetupVCodec
{
	gint ch;			//!< 채널 번호.
	gint stream_cnt;	//!< Stream 수
	uint64_t resolution[3];//!< 해상도	@see NF_IPCAM_RES_E
	guint fps[3];		//!< fps	@see NF_IPCAM_FPS_E
	guint bitrate[3];	//!< bitrate
	guint ntsc_pal;		//!< ntsc/pal 여부.	@see NF_IPCAM_ANTI_FLICKER_E
	guint mirror;		//!< mirror	@see NF_IPCAM_MIRROR_MODES_E
	guint capture;		//!< capture mode @see NF_IPCAM_CAPTURE_MODES_E
	guint bitctrl[3];   //!< bitrate control @NF_IPCAM_BITRATE_CONTROLS_E
	guint vcodec[3];   	//!< vcodec @see IPX_CODEC_TYPE_E
};

typedef struct _NFIPCamSetupACodec	NFIPCamSetupACodec;

/** @struct _NFIPCamSetupACodec
 *  @brief 오디오 코덱 설정 옵션 struct.
 */
struct _NFIPCamSetupACodec
{
	gint ch;				//!< 채널 번호
	guint audio_tx;			//!< 오디오 tx 설정여부
	guint audio_rx;			//!< 오디오 rx 설정여부
	guint audio_codec;		//!< 오디오 코덱. @see __IPX_CODEC_TYPE_E_
	guint mic_volume;		//!< 마이크 볼륨.
	guint speaker_volume;	//!< 스피커 볼륨.
};

typedef struct _NFIPCamSetupImage NFIPCamSetupImage;

/** @struct _NFIPCamSetupImage
 *  @brief 이미지 설정 struct.
 */
struct _NFIPCamSetupImage
{
	gint ch;
	gint exposure;
	gint agc;
	gint eshutter_speed;
	gint slow_shutter;
	gint max_agc;
	gint iris;
	gint blc;
	gint day_night;
	gint det_time;
	gint white_balance;
	gint mwb;
	gint sharpness;
	gint brightness;
	gint contrast;
	gint color;
	gint tint;
	gint wdr;
	gint focus_mode;
	gint anti_flicker;
	gint max_shutter;
	gint base_shutter;
	gint dnr_ctr;
	gint adaptive_ir;
	gint dnn_sense_ntod;
	gint dnn_sense_dton;
	gint defog;
	gint hlc;
	gint focus_limit;
	gint stabilizer;
	gint ir_correction;
	gint dnn_start_hour;
	gint dnn_start_min;
	gint dnn_end_hour;
	gint dnn_end_min;
    
    gint colorvu_ctrl;
	gint colorvu_level;
};

typedef struct _NFIPCamSetupFocusComp NFIPCamSetupFocusComp;

/** @struct _NFIPCamSetupFocusComp
 *  @brief 포커스 보정설정 struct.
 */
struct _NFIPCamSetupFocusComp
{
	gint ch;
	guint dnn_comp_mode;	// Focus Day and Night Compensation Mode
	guint tem_comp_mode;	// Focus temperature Compensation Mode
};

typedef struct _NFIPCamSetupImage_onvif NFIPCamSetupImage_onvif;

/** @struct _NFIPCamSetupImage_onvif
 *  @brief ONVIF 이미지 설정 struct.
 */
struct _NFIPCamSetupImage_onvif
{
	gint ch;

	gint brightness;
	gint contrast;
	gint sharpness;
	gint color;

	gint tint;

	gint focus_mode;
	gint default_speed;
	gint near_limit;
	gint far_limit;

	gint white_balance;
	gint crgain;
	gint cbgain;

	//gint ircut;

	gint mwb;
	// dont use
	//gint blc_mode;
	//gint blc_level;
	//gint wide_dynamic_mode;
	//gint wide_level;

	gint det_time;

};

typedef struct _NFIPCamSetupExposure_onvif NFIPCamSetupExposure_onvif;

/** @struct _NFIPCamSetupExposure_onvif
 *  @brief ONVIF exposure 설정 struct.
 */
struct _NFIPCamSetupExposure_onvif
{
	gint ch;

	gint mode;
	gint priority;

	gint minetime;
	gint maxetime;
	gint etime;
	gint mingain;
	gint maxgain;
	gint gain;
	gint miniris;
	gint maxiris;
	gint iris;
	gint bottom;
	gint top;
	gint right;
	gint left;

	gint slow_shutter;
	gint max_agc;
	gint iris_control;

	gint wide_dynamic_mode;
	gint wide_level;

	gint blc_mode;
	gint blc_level;

	gint ircut;
	gint mirror;
};

typedef struct _NFIPCamSetupFocus_onvif NFIPCamSetupFocus_onvif;

/** @struct _NFIPCamSetupFocus_onvif
 *  @brief ONVIF focus설정 struct.
 */
struct _NFIPCamSetupFocus_onvif
{
	gint ch;
	gint mode;
	gint position;
	gint distance;
	gint speed;
};

typedef struct _NFIPCamSetupPTZ_onvif NFIPCamSetupPTZ_onvif;

/** @struct _NFIPCamSetupPTZ_onvif
 *  @brief ONVIF PTZ설정 struct.
 */
struct _NFIPCamSetupPTZ_onvif
{
	gint ch;
	gint mode;

	gint ePTZAreaId;

	gint absolute_pan;
	gint absolute_tilt;
	gint absolute_zoom;
	gint relative_pan;
	gint relative_tilt;
	gint relative_zoom;
	gint speed_pan;
	gint speed_tilt;
	gint speed_zoom;
};

typedef struct _NFIPCamSetupColor NFIPCamSetupColor;

/** @struct _NFIPCamSetupColor
 *  @brief 카메라 color설정 struct.
 *  @deprecated
 */
struct _NFIPCamSetupColor
{
	gint ch;
	gint brightness;
	gint contrast;
	gint color;
	gint tint;
};

typedef struct _NF_IPCAM_POINT__
{
	int x;
	int y;
} NF_IPCAM_POINT;

typedef struct _NFIPCamROIAreaProfile NFIPCamROIAreaProfile;
/** @struct _NFIPCamROIAreaProfile
 *  @brief ROI Area capability struct.
 */
struct _NFIPCamROIAreaProfile
{
	gint ch;
	gint block_width;
	gint block_height;
	gint area_num;
	gint chipset;
	gint isOption;
	gint isSupport;
};
int nf_ipcam_get_roi_area_profile(gint ch, NFIPCamROIAreaProfile* info);

int nf_ipcam_get_corridor_mode(gint ch, gint* value);
int nf_ipcam_get_is_supported_corridor(gint ch);

/** @enum __ROI_MODE_
 *  @brief 모션 설정 방법.
 */
typedef enum __ROI_MODE_
{
	ROI_OFF = 1<<0,        //!<
	ROI_AUTO = 1<<1 	,        //!<
	ROI_MANUAL = 1<<2 	,        //!<
    ROI_MODE_NR = 3
} ROI_MODE;

/** @enum __ROI_BACKGROUND_IMAGE_QUALITY_
 *  @brief 모션 설정 방법.
 */
typedef enum __ROI_BACKGROUND_IMAGE_QUALITY_
{
	ROI_LOW = 0,        //!<
	ROI_MID 	,        //!<
	ROI_HIGH 	,        //!<
} ROI_QUALITY;

/** @struct _ROI_AREA_
 *  @brief  영역 정보 struct.
 */
typedef struct _ROI_AREA_
{
	NF_IPCAM_POINT left_top;
	NF_IPCAM_POINT right_bottom;

	int interest_level;

}ROI_AREA;

typedef struct _NFIPCamSetupROIArea NFIPCamSetupROIArea;

struct _NFIPCamSetupROIArea
{
	gint ch;
	gint width;
	gint height;
	ROI_MODE roi_mode;
	ROI_QUALITY roi_quality;
	gint roi_area_num;
	ROI_AREA roi_area[MAX_ROI_AREA];
};

/** @enum __MOTION_AREA_METHOD_E_
 *  @brief 모션 설정 방법.
 */
typedef enum __MOTION_AREA_METHOD_E_
{
	MAM_NONE = 0,        //!<
	MAM_RECTANGLE,   //!<
	MAM_POLYGON,	 //!<
	MAM_CELL,        //!<
	MAM_RAW_STREAM,  //!<
	MAM_SIM_RECTANGLE,//!< S1 시나리오로, Pixel방식일 때 임의로 Rectangle 방식처럼 구현함.
	MAM_GENERAL
} MOTION_AREA_METHOD_E;

typedef struct _MOTION_AREA__ MAREA;	// private structure

/** @struct _MOTION_AREA__
 *  @brief 모션 영역 정보 struct.
 */
struct _MOTION_AREA__
{
	int sensitivity;
	union {
		struct {
			int num_point;
			NF_IPCAM_POINT point[49];
		} POLYGON;

		struct {
			NF_IPCAM_POINT left_top;
			NF_IPCAM_POINT right_bottom;
			//char reserved[380];
		} RECTANGLE;

		struct {
			char active_cell[396];
		} CELL;
	} FIGURE;
};

typedef struct _NFIPCamMotionSmartOption NFIPCamMotionSmartOption;
struct _NFIPCamMotionSmartOption
{
    char name[50];
    int enable;
    int threshold;
};


/** @struct _NFIPCamSetupMotionSmart
 *  @brief 스마트 모션 설정 struct.
 */
typedef struct _NFIPCamSetupMotionSmart NFIPCamSetupMotionSmart;
struct _NFIPCamSetupMotionSmart
{
	gint ch;
	guint smart_motion_enable;
	guint ai_alarm_event;
    NFIPCamMotionSmartOption smart_motion_options[MAX_AI_MOTION];
    guint smart_motion_option_size;
};

/** @struct _NFIPCamSetupHallwayMode
 *  *  @brief Hallway mode 관련 struct (복도모드)
 *   */
typedef struct _NFIPCamSetupCorridorMode NFIPCamSetupCorridorMode;
struct _NFIPCamSetupCorridorMode
{
		int ch;
		int corridor_mode;
		int min;
		int max;
};

typedef struct _NFIPCamSetupMotionArea NFIPCamSetupMotionArea;

/** @struct _NFIPCamSetupMotionArea
 *  @brief 모션 설정 struct.
 */
struct _NFIPCamSetupMotionArea
{
	gint ch;
	gint block_width;
	gint block_height;
	MOTION_AREA_METHOD_E method;
	gint area_num;
	MAREA marea[MAX_MOTION_AREA];
	char area[1400];

};

typedef struct _NF_ONVIF_MOTION_DATA NF_ONVIF_MOTION_DATA;
struct _NF_ONVIF_MOTION_DATA
{
	pthread_t thread_id;
	int ch;
	NFIPCamSetupMotionArea area;
	NFIPCamSetupMotionSmart smart;
};

typedef struct _NFIPCamAFCapa NFIPCamAFCapa;
/** @struct _NFIPCamAFCapa
 *  @brief 렌즈 capability struct.
 */
struct _NFIPCamAFCapa
{
	gint mfz;
	gint iris_mode;
	gint zoom_min;
	gint zoom_max;
	gint focus_min;
	gint focus_max;
	gint iris_min;
	gint iris_max;
	gint iris;
};

typedef struct _NFIPCamPrivacyMaskProfile NFIPCamPrivacyMaskProfile;
/** @struct _NFIPCamPrivacyMaskProfile
 *  @brief Privacy Mask capability struct.
 */
struct _NFIPCamPrivacyMaskProfile
{
	gint ch;
	gint is_support;
	gint block_width;
	gint block_height;
	gint area_num;
};

typedef struct _NFIPCamPrivacyMask NFIPCamPrivacyMask;
/** @struct _NFIPCamPrivacyMask
 *  @brief Privacy Mask 설정 struct.
 */
struct _NFIPCamPrivacyMask
{
	gint ch;
	gint rect_cnt;
	guint color[10];
	NF_IPCAM_POINT lt[10];
	NF_IPCAM_POINT rb[10];
};

typedef struct _NFIPCamAuxiliary NFIPCamAuxiliary;
/** @struct _NFIPCamAuxiliary
 *  @brief ONVIF 카메라의 Auxiliary 정보 struct.
 */
struct _NFIPCamAuxiliary
{
	unsigned int size;
	char commands[MAX_AUXILIARY_COMMANDS][32];
};

/* Camera Focus Compentsation Profile */
typedef struct _NFIPCamFocusCompProfile	NFIPCamFocusCompProfile;
struct _NFIPCamFocusCompProfile
{
	gint ch;
	gint supported; //!< NF_IPCAM_FUNC_FOCUS_COMP_DN | NF_IPCAM_FUNC_FOCUS_COMP_TEMP | NF_IPCAM_FUNC_FOCUS_COMP_AREA
	guint tem_comp_mode;
	guint dnn_comp_mode;
};

void nf_ipcam_init(void);
void nf_ipcam_finalize(void);
void nf_ipcam_stop(void);
void nf_ipcam_start(void);



/**********************      IP Camera Setup API      **********************/

/** @enum __NF_IPCAM_SETUP_TYPE_E_
 *  @brief 카메라로 보낼 수 있는 Setup 유형.
 *  enum 추가시 model db의 func에도 추가해주어야 한다.
 */
typedef enum __NF_IPCAM_SETUP_TYPE_E_ {
	NF_IPCAM_TYPE_INIT = 0,
	NF_IPCAM_TYPE_CUSTOM0,
	NF_IPCAM_TYPE_CUSTOM1,
	NF_IPCAM_TYPE_CUSTOM2,
	NF_IPCAM_TYPE_CUSTOM3,
	NF_IPCAM_TYPE_REBOOT_SOFT = 5,
	NF_IPCAM_TYPE_FACTORY_DEFAULT,
	NF_IPCAM_TYPE_SET_VCODEC,
	NF_IPCAM_TYPE_SET_ACODEC,
	NF_IPCAM_TYPE_SET_IMAGE,
	NF_IPCAM_TYPE_SET_ALARM = 10,
	NF_IPCAM_TYPE_SET_MOTION,
	NF_IPCAM_TYPE_SET_PMASK,
	NF_IPCAM_TYPE_GET_LENSCAP,
	NF_IPCAM_TYPE_SET_ORIGIN,
	NF_IPCAM_TYPE_SET_AF_MODE = 15,
	NF_IPCAM_TYPE_SET_AR_MODE,
	NF_IPCAM_TYPE_SET_PAN_TILT,
	NF_IPCAM_TYPE_SET_ZOOM,
	NF_IPCAM_TYPE_SET_FOCUS,
	NF_IPCAM_TYPE_SET_IRIS = 20,
	NF_IPCAM_TYPE_SET_ONESHOT,
	NF_IPCAM_TYPE_GET_PAN,
	NF_IPCAM_TYPE_GET_TILT,
	NF_IPCAM_TYPE_GET_ZOOM,
	NF_IPCAM_TYPE_GET_FOCUS = 25,
	NF_IPCAM_TYPE_GET_IRIS,
	NF_IPCAM_TYPE_SET_STOP,
	NF_IPCAM_TYPE_PRESET_SET,
	NF_IPCAM_TYPE_PRESET_CLEAR,
	NF_IPCAM_TYPE_PRESET_GO = 30,
	NF_IPCAM_TYPE_POLL_EVENT,
	NF_IPCAM_TYPE_SET_IMAGE_ONVIF,
	NF_IPCAM_TYPE_SET_EXP_ONVIF,
	NF_IPCAM_TYPE_SET_FOCUS_ONVIF,
	NF_IPCAM_TYPE_SET_ENABLE_VA=35,
	NF_IPCAM_TYPE_SET_RESET_VA,
	NF_IPCAM_TYPE_SET_VA_CONFIG,
	NF_IPCAM_TYPE_SET_VA_OPTION,
	NF_IPCAM_TYPE_SET_MIRROR,
	NF_IPCAM_TYPE_SET_ADJUST_D2N=40,
	NF_IPCAM_TYPE_SET_ADJUST_N2D,
	NF_IPCAM_TYPE_SET_FOCUS_COMP,
	NF_IPCAM_TYPE_SET_DC_IRIS_CAL,
	NF_IPCAM_TYPE_SET_ZOOM_STOP,
	NF_IPCAM_TYPE_SET_ROI=45,
	NF_IPCAM_TYPE_SET_SMART_MOTION,
	NF_IPCAM_TYPE_SET_CORRIDOR_MODE,
	NF_IPCAM_TYPE_SET_MOUNT,
	NF_IPCAM_TYPE_SET_DEWARP,
	NF_IPCAM_TYPE_GET_EPTZ_LAYOUT,
	NF_IPCAM_TYPE_MAX
} NF_IPCAM_SETUP_TYPE_E;

/** @enum __NF_IPCAM_SETUP_STATUS_E_
 *  @brief 카메라 Setup의 현재 상태.
 */
typedef enum __NF_IPCAM_SETUP_STATUS_E_ {
	NF_IPCAM_STATUS_NORMAL,
	NF_IPCAM_STATUS_BEGIN,
	NF_IPCAM_STATUS_PENDING,
	NF_IPCAM_STATUS_FAILED_REQ,
	NF_IPCAM_STATUS_TIMEOUT,
	NF_IPCAM_STATUS_END_SUCCESS,
	NF_IPCAM_STATUS_MAX
} NF_IPCAM_SETUP_STATUS_E;

/** @struct _NFIPCamProgress
 *  @brief 카메라 Setup의 진행 상태 struct.
 */
typedef struct _NFIPCamProgress NFIPCamProgress;
struct _NFIPCamProgress
{
	gint type;		   //!< NF_IPCAM_SETUP_TYPE_E
	gint ch;           //!< 채널 번호
	gint stream;       //!< stream 번호(사용안함)
	gint status;	   //!< NF_IPCAM_SETUP_STATUS_E
	gint current;      //!<
	gint total;        //!<

	guint timeout;     //!<
	guint timeBegin;   //!<
	guint timeElapsed; //!<
	guint timeRemain;  //!<
};

/**
 * @brief 카메라 Setup시 진행 상태를 return받기 위한 callback함수.
 * @param progress 진행 상태 struct.
 * @param user_data user data.
 *
 * @see scm_req_ipcam_calibration, scm_req_ipcam_onepush
 */
typedef void (*NFIPCamSetupCallback)(NFIPCamProgress* progress, gpointer user_data);




/* IP Camera configuration APIs */

/*
 * Camera software reboot for the specified channel.
 * This is non-blocking function, returns immediately.
 * Though user callback is NULL, ipcam_manager still notify reboot_done.
 *
 * NFIPCamSetupCallback cb_fxn
 *    - User callback called when reboot done.
 */
int nf_ipcam_soft_reboot
(gint ch, NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);

/*
 * Camera factory default for the specified channel
 * This is non-blocking function, returns immediately.
 * Though user callback is NULL, ipcam_manager still notify factory_done.
 *
 * NFIPCamSetupCallback cb_fxn
 *    - User callback called when factory default done.
 */
int nf_ipcam_factory_default
(gint ch, NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);


/* Camera setup: video encoder configuration */
int nf_ipcam_set_vcodec
(gint ch, NFIPCamSetupVCodec* info,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
int nf_ipcam_set_fps
(gint ch, NF_IPCAM_FPS_E first, NF_IPCAM_FPS_E second,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
int nf_ipcam_set_bitrate
(gint ch, guint first, guint second,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);

/* Camera setup: audio configuration */
int nf_ipcam_set_acodec
(gint ch, NFIPCamSetupACodec* info,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
/* Camera setup: image configuration */
int nf_ipcam_set_image
(gint ch, NFIPCamSetupImage* info,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
/* Camera setup: exposure configuration - onvif */
int nf_ipcam_set_exposure_onvif
(gint ch, NFIPCamSetupExposure_onvif* info,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
/* Camera setup : image&exposure - onvif(db) */
int nf_ipcam_set_image_exp_onvif(gint ch, NFIPCamSetupImage_onvif* info, NFIPCamSetupExposure_onvif* info2,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
/* Camera setup: focus moving - onvif */
int nf_ipcam_set_focus_onvif
(gint ch, NFIPCamSetupFocus_onvif* info,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
int nf_ipcam_set_ptz_onvif
(gint ch, NFIPCamSetupPTZ_onvif* info,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
/* Camera setup: rotation - onvif */
int nf_ipcam_set_rotation_onvif(gint ch, gint mirror,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
/* Camera setup: video encoder configuration - onvif */
int nf_ipcam_set_vcodec_onvif
(gint ch, NFIPCamSetupVCodec* info,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);

/*
 * Get camera video encoder configuration
 * NFIPCamSetupVCodec* info
 *    - Must be allocated before used as a buffer for the infomation
 */
int nf_ipcam_get_vcodec
(gint stream, NFIPCamSetupVCodec* info, GError **error);
/*
 * Get camera audio encoder configuration
 * NFIPCamSetupACodec* info 
 *    - Must be allocated before used as a buffer for the infomation
 */
int nf_ipcam_get_acodec
(gint ch, NFIPCamSetupACodec* info, GError **error);
/*
 * Get camera image configuration
 * NFIPCamSetupImage* info
 *    - Must be allocated before used as a buffer for the infomation
 */
int nf_ipcam_get_image
(gint ch, NFIPCamSetupImage* info, GError **error);

/*
 * Get resolution infomation of the camera
 * guint* capable
 *    - Resolution capability
 * guint* current
 *    - Current resolution
 */
int nf_ipcam_get_resol
(gint ch, gint stream_num, uint64_t* capable, uint64_t* current, GError **error);

int nf_ipcam_get_ch_stream_ratio(gint ch, gint stream, gint *width_ratio, gint *height_ratio);

/* 
 * Get followings of the camera
 * guint* capable
 *    - FPS capability
 * guint* current
 *    - Current FPS
 */
int nf_ipcam_get_fps
(gint ch, gint stream_num, guint* capable, guint* current, GError **error);

/* Get camera chipset code (Hisilicon) */
int nf_ipcam_get_hisilicon_chipset_code(gint ch);

typedef struct _NFIPCamModelInfo NFIPCamModelInfo;
struct _NFIPCamModelInfo
{
	gint ch;
	guint8 mac[6];
	guint8 reserved[2];
	gchar name[64];
	gchar swver[128];
	gchar vendor[64];
};
/*
 * Get model info using NFIPCamModelInfo
 *    - MAC address
 *    - Model name
 *    - FW version
 *    - Vendor
 */
int nf_ipcam_get_model_info(gint ch, NFIPCamModelInfo* model_info, GError **error);

typedef struct _NFIPCamConfInfo NFIPCamConfInfo;
struct _NFIPCamConfInfo
{
	gint ch;
	gint configurable;

	gchar ipaddr[16];
	gchar username[64];
	gchar password[64];
	gint http_port;
	gint rtsp_port;
	guint protocol;			// ref. IPX_IPCAM_RX_METHOD_E
	gint video;
	gint audio_in;
	gint audio_out;
	gint alarm_in;
	gint alarm_out;
};
int nf_ipcam_get_config_info(gint ch, NFIPCamConfInfo* conf_info, GError **error);


/*******************      IP Camera Event Setup API      *******************/
/* Camera Alarm event configuration */
typedef struct _NFIPCamSetupAlarm NFIPCamSetupAlarm;
struct _NFIPCamSetupAlarm
{
	gint ch;
	gint in;
	gint in_type;
	gint out;
	gint out_type;
};
/* Camera setup: alarm configuration */
int nf_ipcam_set_alarm (gint ch, NFIPCamSetupAlarm* info,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
int nf_ipcam_set_alarm_in (gint ch, gint al_in, gint in_type,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
int nf_ipcam_set_alarm_out (gint ch, gint al_out, gint out_type,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
int nf_ipcam_get_alarm (gint ch, NFIPCamSetupAlarm* info, GError **error);
int nf_ipcam_set_relay (gint ch, gint onoff, 
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);

/* Camera Motion event configuration */
typedef struct _NFIPCamMotionProfile	NFIPCamMotionProfile;
struct _NFIPCamMotionProfile
{
	gint ch;
	gint sensitivity_min;
	gint sensitivity_max;
	gint block_width;
	gint block_height;
	gint min_block;
	gint num_blocks;
	gint area_method;
	gint rect_num;
	gint smart_motion_support;

	gboolean is_itx_cam;
	
    NFIPCamMotionSmartOption smart_motion_options[MAX_AI_MOTION];
    guint smart_motion_option_size;
    char db_str[256];
};
int nf_ipcam_get_motion_profile(gint ch, NFIPCamMotionProfile* info, GError **error);

/* Motion callback */
typedef struct _NFIPCamMotionRaw NFIPCamMotionRaw;
struct _NFIPCamMotionRaw
{
	gint ch;
	gint stream_num;
	gint width;
	gint height;
	guint timestamp;
	guint timestampl;
	guchar mraw[512];
};
/* Callback function type definition */
typedef void (*NFIPCamMotionCallback)(NFIPCamMotionRaw* motion, gpointer user_data);

int nf_ipcam_set_motion_callback(NFIPCamMotionCallback* cb_func,
			gpointer user_data, GError **error);

typedef void (*NFIPCamAlarmCallback)(guint ch_mask, gpointer user_data);

int nf_ipcam_set_alarm_callback(NFIPCamAlarmCallback* cb_func,
			gpointer user_data, GError **error);


/* Audio action type enum */
typedef enum __NF_IPCAM_AUDIO_ACTION_E_
{
	NF_IPCAM_SEND_AUDIO_START,
	NF_IPCAM_SEND_AUDIO_END,
	NF_IPCAM_SEND_AUDIO_DATA
} NF_IPCAM_AUDIO_ACTION_E;
/* Audio data */
typedef struct _NFIPCamAudioRaw NFIPCamAudioRaw;
struct _NFIPCamAudioRaw
{
	gint ch;
	gint type;			// ref. NF_IPCAM_AUDIO_ACTION_E
	GObject *buf;		// NULL if the type is START/END
};
int nf_ipcam_send_audio(gint ch, NFIPCamAudioRaw* audio, gint* rtn, gpointer user_data);


typedef enum __NF_IPCAM_DEVICE_E_ {
	NF_IPCAM_DEVICE_NONE,
	NF_IPCAM_DEVICE_NETWORK_CAMERA,
	NF_IPCAM_DEVICE_NETWORK_STORAGE,
	NF_IPCAM_DEVICE_EXTERN_HUB,
	NF_IPCAM_DEVICE_ROUTER,
	NF_IPCAM_DEVICE_UNKNOWN
} NF_IPCAM_DEVICE_E;

typedef struct _NFIPCamPortStatus NFIPCamPortStatus;
struct _NFIPCamPortStatus
{
	gboolean status;		// [0: Ok], [1: Fail]
	guint device_class;
	gchar vendor[64];
	gchar model[64];
	gchar detail[256];
};

int nf_ipcam_get_port_status(gint ch, NFIPCamPortStatus* port_status, GError **error);
int nf_ipcam_set_port_status(gint ch, NFIPCamPortStatus* port_status, GError **error);

int nf_ipcam_get_pnd_status(gint *status);
int nf_ipcam_is_all_ch_unplugged();

/** @struct _NFIPCamOption
 *  @brief UI에서 사용하는 'select'를 구현하기 위한 구조체.
 */
typedef struct _NFIPCamOption NFIPCamOption;
struct _NFIPCamOption
{
	guint64 category;				//!< 카테고리. @see _NF_IPCAM_IMAGE_E
	guint value;				//!< 해당 select의 값. @see _NF_IPCAM_IMAGE_MODES_E
	gint selected;				//!< 0: false, 1: true(현재 설정된 값)
	guint64 dependent_category;	//!< '상위' 항목.
	guint64 enable_category;		//!< Enable처리할 항목.
	guint64 disable_category;		//!< Disable처리할 항목.
	gchar caption[32];			//!< 표시할 문구.
};

/** @struct _NFIPCamValue
 *  @brief UI에서 사용하는 'range'를 구현하기 위한 구조체.
 */
typedef struct _NFIPCamValue NFIPCamValue;
struct _NFIPCamValue
{
	guint64 category;				//!< 카테고리. @see _NF_IPCAM_IMAGE_E
	guint value;				//!< 현재값.
	gint min;					//!< 최소값.
	gint max;					//!< 최대값.
	guint64 dependent_category;	//!< difference 값과 의존성 있는 카테고리.
	gint difference;		//!< dependent_category 와 차이 (dependent 카테고리와 5 또는 -5 를 유지하려면 , 5 또는 -5)
};

/** @struct _NFIPCamImageProfile
 *  @brief 카메라의 image설정 관련 capability struct.
 *  @deprecated ONVIF카메라 겸용 UI로 변경되며 2차 변경점부터 사용안함.
 */
typedef struct _NFIPCamImageProfile NFIPCamImageProfile;
struct _NFIPCamImageProfile
{
	guint supported;

#if 0
	NFIPCamValue brightness;
	NFIPCamValue contrast;
	NFIPCamValue color;
	NFIPCamValue tint;
#endif

	NFIPCamValue sharpness;

	gint mirror_cnt;
	NFIPCamOption mirror[NF_IPCAM_MIRROR_NR];
#if 0
	gint antiflicker_cnt;
	NFIPCamOption antiflicker[2];
#endif

	gint exposure_cnt;
	NFIPCamOption exposure[NF_IPCAM_IMAGE_EXP_MODE_NR];

	NFIPCamValue agc;

	NFIPCamValue eshutter;

	gint slowshutter_cnt;
	NFIPCamOption slowshutter[NF_IPCAM_IMAGE_SLSH_MODE_NR];

	gint maxagc_cnt;
	NFIPCamOption maxagc[NF_IPCAM_IMAGE_MAGC_MODE_NR];

	gint dc_iris_cnt;
	NFIPCamOption dc_iris[NF_IPCAM_IMAGE_IRIS_NR];

	gint blc_cnt;
	NFIPCamOption blc[NF_IPCAM_IMAGE_BLC_NR];

	gint wb_cnt;
	NFIPCamOption wb[NF_IPCAM_IMAGE_WB_MODE_NR];

	gint mwb_cnt;
	NFIPCamOption mwb[NF_IPCAM_IMAGE_MWB_MODE_NR];

	gint dnn_cnt;
	NFIPCamOption dnn[NF_IPCAM_IMAGE_DN_NR];	// day and night

	gint dnn_toggle_cnt;
	NFIPCamOption dnn_toggle[NF_IPCAM_IMAGE_TGTIME_NR];

	gint p_iris_cnt;
	NFIPCamOption p_iris[NF_IPCAM_IMAGE_IRIS_NR];
};

typedef struct _NFIPCamOnvifBookmarkProfile onvif_bookmark;
struct _NFIPCamOnvifBookmarkProfile
{
		guint bookmark_cnt;
			guint bookmark_preset_number[16];
};
int nf_ipcam_get_onvif_bookmark_presets(int ch, onvif_bookmark *bookmark); 

int nf_ipcam_get_image_profile(gint ch, NFIPCamImageProfile* prof);

typedef struct _NFIPCamOptionList NFIPCamOptionList;
struct _NFIPCamOptionList
{
	guint value;
	guint64 enable_category;
	guint64 disable_category;
	guint64 visible_category;
	guint64 invisible_category;
	gchar caption[32];
};

/** @struct _NFIPCamOption_onvif
 *  @brief 신규 image UI의 'select' 구조체.
 *  visible, invisible 기능이 추가됨.
 */
typedef struct _NFIPCamOption_onvif NFIPCamOption_onvif;
struct _NFIPCamOption_onvif
{
	guint64 category;
	guint value;
	gint selected;		// 0: false, 1: true
	guint64 dependent_category;
	guint64 enable_category;
	guint64 disable_category;
	guint64 visible_category;
	guint64 invisible_category;
	gchar caption[32];

	//guint cnt;
	//NFIPCamOptionList option[NF_IPCAM_MODE_ONVIF_NR_MAX];
};

struct _NFIPCamTime
{
	guint hour;
	guint min;
};

typedef struct _NFIPCamDuration NFIPCamDuration;
struct _NFIPCamDuration
{
	guint64 category;
	struct _NFIPCamTime start;
	struct _NFIPCamTime end;
};

/** @struct _NFIPCamImageProfile_onvif
 *  @brief 카메라의 image설정 관련 capability struct.
 */
typedef struct _NFIPCamImageProfile_onvif NFIPCamImageProfile_onvif;
struct _NFIPCamImageProfile_onvif
{
	guint64 supported_image;

	NFIPCamValue brightness;
	NFIPCamValue contrast;
	NFIPCamValue sharpness;
	NFIPCamValue color;

	NFIPCamValue tint;

	gint mirror_cnt;
	NFIPCamOption_onvif mirror[NF_IPCAM_MIRROR_NR];


	gint focus_cnt;
	NFIPCamOption_onvif focus[NF_IPCAM_FOCUS_MODE_ONVIF_NR];
	NFIPCamValue defaultspeed;
	NFIPCamValue nearlimit;
	NFIPCamValue farlimit;


	NFIPCamValue abposition;
	NFIPCamValue abspeed;
	NFIPCamValue redistance;
	NFIPCamValue respeed;
	NFIPCamValue cospeed;

	gint wb_cnt;
	NFIPCamOption_onvif wb[NF_IPCAM_WB_MODE_ONVIF_NR];
	NFIPCamValue crgain;
	NFIPCamValue cbgain;

	gint mwb_cnt;
	NFIPCamOption_onvif mwb[NF_IPCAM_IMAGE_MWB_MODE_NR];

	NFIPCamValue blclevel;

	gint focus_limit_cnt;
	NFIPCamOption_onvif focus_limit[NF_IPCAM_FOCUS_LIMIT_NR];

	gint stabilizer_cnt;
	NFIPCamOption_onvif stabilizer[NF_IPCAM_STABILIZER_NR];

	gint ir_correction_cnt;
	NFIPCamOption_onvif ir_correction[NF_IPCAM_IR_CORRECTION_NR];

};

/** @struct _NFIPCamExposureProfile_onvif
 *  @brief 카메라의 exposure설정 관련 capability struct.
 */
typedef struct _NFIPCamExposureProfile_onvif NFIPCamExposureProfile_onvif;
struct _NFIPCamExposureProfile_onvif
{
	guint64 supported_exposure;

	gint mode_cnt;
	NFIPCamOption_onvif mode[NF_IPCAM_EXPOSURE_MODE_ONVIF_NR];

	gint priority_cnt;
	NFIPCamOption_onvif priority[NF_IPCAM_PRIORITY_MODE_ONVIF_NR];

	NFIPCamValue minetime;
	NFIPCamValue maxetime;
	NFIPCamValue etime;
	NFIPCamValue mingain;
	NFIPCamValue maxgain;
	NFIPCamValue gain;
	NFIPCamValue miniris;
	NFIPCamValue maxiris;
	NFIPCamValue iris;
	NFIPCamValue bottom;
	NFIPCamValue top;
	NFIPCamValue right;
	NFIPCamValue left;

	gint slowshutter_cnt;
	NFIPCamOption_onvif slowshutter[NF_IPCAM_IMAGE_SLSH_MODE_NR];

	gint maxagc_cnt;
	NFIPCamOption_onvif maxagc[NF_IPCAM_IMAGE_MAGC_MODE_NR];

	gint dc_iris_cnt;
	NFIPCamOption_onvif dc_iris[NF_IPCAM_IMAGE_IRIS_NR];

	gint dc_iris_motion_cnt;
	NFIPCamOption_onvif dc_iris_motion[NF_IPCAM_IMAGE_IRIS_NR];

	gint blc_cnt;
	NFIPCamOption_onvif blc[NF_IPCAM_WDR_MODE_ONVIF_NR];
	NFIPCamValue blclevel;

	gint antiflicker_cnt;
	NFIPCamOption_onvif antiflicker[NF_IPCAM_ANTI_FLICKER_MODE_NR];
	gint antiflicker_motion_cnt;
	NFIPCamOption_onvif antiflicker_motion[NF_IPCAM_ANTI_FLICKER_MODE_NR];
	gint antiflicker_motion_off_cnt;
	NFIPCamOption_onvif antiflicker_motion_off[NF_IPCAM_ANTI_FLICKER_MODE_NR];
	gint antiflicker_auto_off_cnt;
	NFIPCamOption_onvif antiflicker_auto_off[NF_IPCAM_ANTI_FLICKER_MODE_NR];

	gint max_shutter_50_cnt;
	NFIPCamOption_onvif max_shutter_50[NF_IPCAM_MAX_SHUTTER_MODE_PAL_NR];
	gint max_shutter_60_cnt;
	NFIPCamOption_onvif max_shutter_60[NF_IPCAM_MAX_SHUTTER_MODE_NTSC_NR];
	gint max_shutter_off_cnt;
	NFIPCamOption_onvif max_shutter_off[NF_IPCAM_MAX_SHUTTER_MODE_NTSC_NR];
	gint max_shutter_motion_off_cnt;
	NFIPCamOption_onvif max_shutter_motion_off[NF_IPCAM_MAX_SHUTTER_MODE_NTSC_NR];
	gint max_shutter_auto_off_off_cnt;
	NFIPCamOption_onvif max_shutter_auto_off_off[NF_IPCAM_MAX_SHUTTER_MODE_NTSC_NR];
	gint max_shutter_motion_off_on_cnt;
	NFIPCamOption_onvif max_shutter_motion_off_on[NF_IPCAM_MAX_SHUTTER_MODE_NTSC_NR];
	gint max_shutter_auto_off_on_tv_cnt;
	NFIPCamOption_onvif max_shutter_auto_off_on_tv[NF_IPCAM_MAX_SHUTTER_MODE_NTSC_NR];
	gint max_shutter_auto_off_on_cnt;
	NFIPCamOption_onvif max_shutter_auto_off_on[NF_IPCAM_MAX_SHUTTER_MODE_NTSC_NR];

	gint wdr_cnt;
	NFIPCamOption_onvif wdr[NF_IPCAM_WDR_MODE_ONVIF_NR];
	NFIPCamValue wdrlevel;

	gint dnr_cnt;
	NFIPCamOption_onvif dnr[NF_IPCAM_DNR_MODE_NR];

	gint ircut_cnt;
	NFIPCamOption_onvif ircut[NF_IPCAM_IRCUT_MODE_ONVIF_NR];

	gint ircutm_cnt;
	NFIPCamOption_onvif ircutm[NF_IPCAM_IRCUT_MODE_ONVIF_NR];

	gint dnn_toggle_cnt;
	NFIPCamOption_onvif dnn_toggle[NF_IPCAM_IMAGE_TGTIME_NR];

	gint adaptive_ir_cnt;
	NFIPCamOption_onvif adaptive_ir[NF_IPCAM_ADAPTIVE_IR_NR];

	NFIPCamValue dnn_sense_dton;	// Day to Night Sensitivity
	NFIPCamValue dnn_sense_ntod;	// Night to Day Sensitivity

	gint defog_cnt;
	NFIPCamOption_onvif defog[NF_IPCAM_DEFOG_NR];

	gint hlc_cnt;
	NFIPCamOption_onvif hlc[NF_IPCAM_HLC_NR];

    //colorvu
    gint supported_colorvu;
    NFIPCamOption_onvif colorvu_ctrl;
	NFIPCamValue colorvu_level;

	NFIPCamDuration dnn_schedule; 		// Day & Night Schedule

	/* Table
	 |+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++|
	 | Exposure Mode | I-ris | WDR | Anti-Flicker | Analog-Format | Base Shutter Value |
	 |+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++| */
	uint64_t base_shutter_speed_table[15][6];

	gint base_shutter_100_cnt;
	NFIPCamOption_onvif base_shutter_100[NF_IPCAM_BASE_SHUTTER_MODE_NTSC_NR];

	gint base_shutter_120_cnt;
	NFIPCamOption_onvif base_shutter_120[NF_IPCAM_BASE_SHUTTER_MODE_NTSC_NR];

	gint base_shutter_100_300_cnt;
	NFIPCamOption_onvif base_shutter_100_300[NF_IPCAM_BASE_SHUTTER_MODE_NTSC_NR];

	gint base_shutter_100_5000_cnt;
	NFIPCamOption_onvif base_shutter_100_5000[NF_IPCAM_BASE_SHUTTER_MODE_NTSC_NR];

	gint base_shutter_120_360_cnt;
	NFIPCamOption_onvif base_shutter_120_360[NF_IPCAM_BASE_SHUTTER_MODE_NTSC_NR];

	gint base_shutter_120_5000_cnt;
	NFIPCamOption_onvif base_shutter_120_5000[NF_IPCAM_BASE_SHUTTER_MODE_NTSC_NR];

	gint base_shutter_120_262_cnt;
	NFIPCamOption_onvif base_shutter_120_262[NF_IPCAM_BASE_SHUTTER_MODE_NTSC_NR];

	gint base_shutter_30_262_cnt;
	NFIPCamOption_onvif base_shutter_30_262[NF_IPCAM_BASE_SHUTTER_MODE_NTSC_NR];

	gint base_shutter_25_100_cnt;
	NFIPCamOption_onvif base_shutter_25_100[NF_IPCAM_BASE_SHUTTER_MODE_NTSC_NR];

	gint base_shutter_25_300_cnt;
	NFIPCamOption_onvif base_shutter_25_300[NF_IPCAM_BASE_SHUTTER_MODE_NTSC_NR];

	gint base_shutter_25_5000_cnt;
	NFIPCamOption_onvif base_shutter_25_5000[NF_IPCAM_BASE_SHUTTER_MODE_NTSC_NR];

	gint base_shutter_30_120_cnt;
	NFIPCamOption_onvif base_shutter_30_120[NF_IPCAM_BASE_SHUTTER_MODE_NTSC_NR];

	gint base_shutter_30_360_cnt;
	NFIPCamOption_onvif base_shutter_30_360[NF_IPCAM_BASE_SHUTTER_MODE_NTSC_NR];

	gint base_shutter_30_5000_cnt;
	NFIPCamOption_onvif base_shutter_30_5000[NF_IPCAM_BASE_SHUTTER_MODE_NTSC_NR];
};

int nf_ipcam_get_image_profile_onvif(gint , NFIPCamImageProfile_onvif* );
int nf_ipcam_get_exposure_profile_onvif(gint , NFIPCamExposureProfile_onvif* );
int nf_ipcam_is_onvif_support(int );

int nf_ipcam_sync_ai_motion(int ch);
int nf_ipcam_sync_image(int ch);
int nf_ipcam_sync_focus_comp(int ch);
int nf_ipcam_sync_mirror(int ch);
int nf_ipcam_sync_cam_db(int ch);

/* This enum entries may be added */
typedef enum __NF_IPCAM_STATUS_E_ {
	NF_IPCAM_STATUS_OK,
	NF_IPCAM_STATUS_WARN_FW_VERSION,
	NF_IPCAM_STATUS_WARN_MODEL,
	NF_IPCAM_STATUS_WARN_SDKVER,
	NF_IPCAM_STATUS_ERROR
} NF_IPCAM_STATUS_E;
typedef struct _NFIPCamStatusInfo NFIPCamStatusInfo;
struct _NFIPCamStatusInfo
{
	gint ch;
	NF_IPCAM_STATUS_E status;
	gchar description[256];
	gchar recommendation[256];
};


int nf_ipcam_get_iris_supported(gint ch, gboolean *canIris);
int nf_ipcam_get_ptz_support(gint ch, guint func, gboolean *support);

static int roundi(double number)
{
    return (number >= 0) ? (int)(number + 0.5) : (int)(number - 0.5);
}


static double round2(double number, unsigned short precision)
{
	double ret;
	double modifi = 0.5;

	if (number < 0) modifi = -0.5;

	ret = number;
	int pw = 1, i;
	for(i = 0; i < precision; i++) pw = pw * 10;


	ret *= pw;
	ret =(int)(ret + modifi);
	ret /= pw;

	return ret;
}

/** @struct _NFIPCamBpsTable
 *  @brief 카메라의 bitrate table.
 */
typedef struct _NFIPCamBpsTable
{
	guint org_video_bps[NF_IPCAM_RES_MAX][NF_IPCAM_FPS_MAX][NF_IPCAM_QUALITY_MAX];
	guint audio_bps;
	guint bitctrl[3];

	guint sum_video_bps[NF_IPCAM_RES_MAX][NF_IPCAM_FPS_MAX][NF_IPCAM_QUALITY_MAX];	// 1st+2nd
} NFIPCamBpsTable;

int nf_ipcam_get_bps_table(gint ch, NFIPCamBpsTable *table);

/** @enum __NF_IPCAM_FW_STATE
 *  @brief 카메라 업데이트 진행 상태.
 */
typedef enum __NF_IPCAM_FW_STATE
{
	NF_IPCAM_FW_NOT_TARGET = -1,	//!< NO TARGET
	NF_IPCAM_FW_PRE = 0,			//!< PREPARE FOR UPGRADE
	NF_IPCAM_FW_CHK_VER,			//!< FIND AN UPGRADEABLE CAMERA
	NF_IPCAM_FW_FWMODE_REBOOT,		//!< UPDATE MODE REQUIRED (Ti camera)
	NF_IPCAM_FW_SET_FWMODE,			//!< READY
	NF_IPCAM_FW_UPLOAD,				//!< UPLOAD FILE
	NF_IPCAM_FW_WRITE,				//!< WRITING
	NF_IPCAM_FW_FINAL_REBOOT,		//!< REBOOT CAMERA
	NF_IPCAM_FW_UP_COMPLETE = 10	//!< OK
} NF_IPCAM_FW_UPGRADE_STATE;

/** @enum __NF_IPCAM_FW_ERR
 *  @brief 카메라 업데이트 에러코드.
 */
typedef enum __NF_IPCAM_FW_ERR
{
	NF_IPCAM_FW_ERR_OK = 0,     	//!< 정상
	NF_IPCAM_FW_ERR_BINARY_SIZE,	//!< 펌웨어 크기 오류
	NF_IPCAM_FW_ERR_HIGHER_VER, 	//!< 높은 버전 카메라
	NF_IPCAM_FW_ERR_MODEL_CD,   	//!< 모델코드 틀림
	NF_IPCAM_FW_ERR_ONVIF,      	//!< ONVIF 카메라
	NF_IPCAM_FW_ERR_OLD_SW_VER,		//!< IDIS only
	NF_IPCAM_FW_ERR_RETURN_ERROR,	//!< RETURN 에러
	NF_IPCAM_FW_ERR_DISCONNECT,		//!< 연결끊김
	NF_IPCAM_FW_ERR_INVALID_FILE,	//!< 잘못된 파일
	NF_IPCAM_FW_ERR_READY,			//!< READY ERROR
	NF_IPCAM_FW_ERR_UPLOAD,			//!< UPLOAD ERROR
	NF_IPCAM_FW_ERR_WRITE, 			//!< WRITING ERROR
	NF_IPCAM_FW_ERR_GENERAL = 99 	//!< 기타
} NF_IPCAM_FW_UPGRADE_ERR;

/** @enum __NFIPCamDCIrisCal
 *  @brief DC IRIS CALIBRATION 구조체
 */
typedef struct __NFIPCamDCIrisCal
{
	char* iris_type;
	int ch;
	int status;

} NFIPCamDCIrisCalState;

/** @struct _NFIPCamUpgradeState
 *  @brief 카메라 업데이트 진행상태 struct.
 */
typedef struct _NFIPCamUpgradeState
{
	guint state;

	gint is_error;	// 0 ok 1 err
	guint error_no;

	guint cur_progress;
} NFIPCamUpgradeState;


/* ===== ADD Fisheye Camera Define ===== */


/** @enum _NF_IPCAM_FISHEYE_E
 *  @brief FISHEYE 카메라 설정 옵션 
*/
#define NF_IPCAM_FISHEYE_MOUNT		SHIFT_64_00
#define NF_IPCAM_FISHEYE_DEWARP		SHIFT_64_01
#define NF_IPCAM_FISHEYE_EPTZ		SHIFT_64_02


/** @enum NF_IPCAM_CAM_TYPES_E
  * @brief 카메라 종류 옵션
  */
typedef enum _NF_IPCAM_CAM_TYPES_E
{
	NF_IPCAM_CAM_TYPE_NORMAL = 0,
	NF_IPCAM_CAM_TYPE_FISHEYE,
	NF_IPCAM_CAM_TYPE_NR
} NF_IPCAM_CAM_TYPES_E;


/** @struct _NFIPCamTypeProfile
  * @brief 카메라의 종류 관련 struct.
  */
typedef struct _NFIPCamTypeProfile NFIPCamTypeProfile;
struct _NFIPCamTypeProfile 
{
	NF_IPCAM_CAM_TYPES_E cam_type;
};


/** @enum NF_IPCAM_MOUNT_TYPES_E
  * @brief 카메라 Mount 옵션
  */
typedef enum _NF_IPCAM_MOUNT_TYPES_E
{
	NF_IPCAM_MOUNT_WALL		= 1<<0,
	NF_IPCAM_MOUNT_CELLING	= 1<<1,
	NF_IPCAM_MOUNT_TABLE	= 1<<2,
	NF_IPCAM_MOUNT_NR		= 3 
} NF_IPCAM_MOUNT_TYPES_E;


/** @enum NF_IPCAM_DEWARP_MODES_E
  * @brief 카메라 Dewarp옵션
  */
typedef enum _NF_IPCAM_DEWARP_MODES_E
{
	// Sunell Fisheye Dewarp Modes
	NF_IPCAM_DEWARP_IP_FISHEYE			= 1<<0, // Sunell Fisheye Mode
	NF_IPCAM_DEWARP_IP_S_PANORAMA		= 1<<1, // Sunell Single Panorama Mode
	NF_IPCAM_DEWARP_IP_D_PANORAMA		= 1<<2, // Sunell Double Panorama Mode
	NF_IPCAM_DEWARP_IP_4PTZ				= 1<<3, // Sunell 4PTZ Mode
	NF_IPCAM_DEWARP_IP_FISHEYE_3PTZ 	= 1<<4, // Sunell 1Fisheye + 3PTZ Mode
	NF_IPCAM_DEWARP_IP_FISHEYE_5PTZ 	= 1<<5, // Sunell 1Fisheye + 5PTZ Mode
	NF_IPCAM_DEWARP_IP_FISHEYE_7PTZ 	= 1<<6, // Sunell 1Fisheye + 7PTZ Mode
	NF_IPCAM_DEWARP_NR					= 7
} NF_IPCAM_DEWARP_MODES_E;


/** @struct _NFIPCamFisheyeProfile
  * @brief 카메라의 Fisheye 설정 관련 capability struct.
  */
typedef struct _NFIPCamFisheyeProfile NFIPCamFisheyeProfile;
struct _NFIPCamFisheyeProfile
{
	guint64 fisheye_supported;

	gint mount_cnt;
	NFIPCamOption_onvif mount[NF_IPCAM_MOUNT_NR];

	gint dewarp_cnt;
	NFIPCamOption_onvif dewarp[NF_IPCAM_DEWARP_NR];
};


/** @def MAX_EPTZ_AREA
  * @brief 카메라 fisheye 분할 화면 영역의 최대 개수
  */
#define MAX_EPTZ_AREA (10)


/** @enum NF_IPCAM_EPTZ_AREA_TYPES_E
  * @brief 카메라 EPTZ 분할영역의 종류
  */
typedef enum _NF_IPCAM_EPTZ_AREA_TYPES_E 
{
	NF_IPCAM_EPTZ_AREA_NONE	= 0,
	NF_IPCAM_EPTZ_AREA_BASE,
	NF_IPCAM_EPTZ_AREA_PTZ
} NF_IPCAM_EPTZ_AREA_TYPES_E;


/** @struct _EPTZ_AREA
  * @brief 카메라의 EPTZ 분할영역 정보 struct.
  */
typedef struct _EPTZ_AREA
{
	gint area_type;		// NF_IPCAM_PTZ_AREA_TYPES_E
	gint area_no;		// start 0 ( ePTZAreaId )
	gfloat start_lt_x;	// 0.00 ~ 1.00
	gfloat start_lt_y;	// 0.00 ~ 1.00
	gfloat height; 		// 0.00 ~ 1.00
	gfloat width; 		// 0.00 ~ 1.00
} EPTZ_AREA;


/** @struct _NFIPCamEPTZLayout
  * @brief 카메라의 EPTZ 분할영역 Layout struct.
  */
typedef struct _NFIPCamEPTZLayout NFIPCamEPTZLayout;
struct _NFIPCamEPTZLayout
{
	NF_IPCAM_MOUNT_TYPES_E mount;
	NF_IPCAM_DEWARP_MODES_E dewarp;

	gint area_cnt;	// 2개 이상일때 분활화면 있음
 	EPTZ_AREA eptz_area[MAX_EPTZ_AREA];
};

/* ===== ADD Fisheye Camera Define END ===== */


gboolean nf_ipcam_fw_capability_chk(gchar* file_path, guint* out_ch_mask);

gboolean nf_ipcam_fw_upgrade(guint ch_mask, gchar* file_path, gboolean is_nonblocking);

void nf_ipcam_get_upgrade_state(gint ch, NFIPCamUpgradeState *state);

int _nf_ipcam_set_upgrade_state(int ch, int state, int error, int err_no, int progress);
void nf_ipcam_cancel_upgrade_by_ui(void);
int nf_ipcam_is_upgrade_canceled(void);

// written by SKSHIN
void nf_ipcam_ip_changed(void);
int nf_ipcam_poe_reboot(gint ch, NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
int nf_ipcam_get_af_mode(guint *mode_mask);
int nf_ipcam_get_supported_func(gint ch, guint *func, GError **error);
int nf_ipcam_set_color(gint ch, NFIPCamSetupColor* info, NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
int nf_ipcam_set_rotation(gint ch, gint rotate,	NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
int nf_ipcam_get_image_supported_func(gint ch, guint *func, GError **error);
int nf_ipcam_set_lens_default(gint ch,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
int nf_ipcam_set_oneshot(gint ch,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);
int nf_ipcam_set_ntpal(gint ch, guint mode,
		NFIPCamSetupCallback cb_fxn, gpointer user_data, GError **error);

int nf_ipcam_get_af_capability(gint ch, NFIPCamAFCapa* afcapa_info, GError **error);

void nf_ipcam_set_mraw_ch(gint ch);
gint nf_ipcam_get_mraw_ch(void);
int nf_ipcam_rate_down(gint ch);
int nf_ipcam_rate_recover(gint ch);
int nf_ipcam_put_recorded_fcnt(gint* cnt_array);
unsigned int nf_ipcam_get_supported_dlva_ch_mask();

// choissi

gboolean nf_ipcam_direct_config_start( gint ch );
gboolean nf_ipcam_direct_config_stop( );

typedef struct _NFIPCamCamConnURLs NFIPCamCamConnURLs;
struct _NFIPCamCamConnURLs 
{
	int is_openmode;    // 1 : openmode, 0 : cctv
	int nat_required;   // direct config 활성화 필요 유무. CCTV모드에서 Direct config가 활성화되지 않아서 카메라로 접근이 불가능할때만 1로 설정됨

	unsigned int url_ch_mask;
	char url[NUM_ACTIVE_CH][256];
};
int nf_ipcam_get_camera_connection_urls(NFIPCamCamConnURLs *urls);

typedef struct _NFIPCamDirectConfigInfo NFIPCamDirectConfigInfo;
struct _NFIPCamDirectConfigInfo 
{
	int running_state; //1 : running, 0 : stopped

	unsigned int url_ch_mask;
	char url[NUM_ACTIVE_CH][256];
};

int nf_ipcam_direct_config_start_all(int sec);
int nf_ipcam_direct_config_stop_all();
int nf_ipcam_get_direct_config_status(NFIPCamDirectConfigInfo *info);

int nf_ipcam_install_mode_on(void);
int nf_ipcam_install_done(void);

gboolean nf_ipcam_hub_get_macaddr(unsigned char *p_hub_macaddr);
gboolean nf_ipcam_hub_get_fwver(unsigned char *p_hub_fwver);

gint nf_ipcam_is_support_va(gint ch);
gint nf_ipcam_list_channels_va(gchar* buf);

int nf_ipcam_get_encoder_capability(gint ch, NFIPCamEncoderCap* info);
int nf_ipcam_get_max_fps_information(gint ch, char resolution, unsigned int *fps);
unsigned int nf_ipcam_get_pnd_osd_status(gint ch);
void nf_ipcam_opmode_change(void);

typedef struct _NFIPCamLicenseKeyInfo NFIPCamLicenseKeyInfo;
struct _NFIPCamLicenseKeyInfo 
{
	gchar key[64];
	guint acquired_date;
	guint expired_date;

	char name[64];
	unsigned int param1;
	unsigned int param2;
};

#define IPX_LICENSE_KEY_MAX (16)

typedef struct _NFIPCamLicenseKeyList NFIPCamLicenseKeyList;
struct _NFIPCamLicenseKeyList {

	NFIPCamLicenseKeyInfo key_data[IPX_LICENSE_KEY_MAX];
	guint count;
};

#if CAM_ZIG_MODE
typedef struct _NFIPCamMFInfo NFIPCamMFInfo;
struct _NFIPCamMFInfo
{
	guint ipaddr;
	guchar macaddr[8];
	gchar name[64];
	gchar swver[64];
	gchar timeinfo[64];
	gint current;
};

gboolean nf_ipcam_set_time_info(gint ch);
gboolean nf_ipcam_get_mf_info(gint ch, NFIPCamMFInfo* info);
gboolean nf_ipcam_scan_start(void);
gboolean nf_ipcam_works_done(void);

void nf_ipcam_zig_zoom_wide(void);
void nf_ipcam_zig_zoom_tele(void);
void nf_ipcam_zig_focus_near(void);
void nf_ipcam_zig_focus_far(void);
void nf_ipcam_zig_iris_open(void);
void nf_ipcam_zig_iris_close(void);
void nf_ipcam_zig_origin(void);
void nf_ipcam_zig_onepush(void);
void nf_ipcam_zig_up(gint);
void nf_ipcam_zig_down(gint);
void nf_ipcam_zig_left(gint, gint);
void nf_ipcam_zig_right(gint, gint);

#endif

GTimeVal nf_ipcam_get_poe_off_time(gint ch);
void nf_ipcam_set_poe_off_time(gint ch);
void nf_ipcam_init_poe_off_time(void);

void nf_ipcam_write_maps(void);
extern void nf_ipcam_boost_priority(void);

extern int nf_ipcam_is_vendor_vicon(void);
int nf_ipcam_is_hisilicon_camera(int ch);

extern void nf_ipcam_get_sysproc_uuid(char* rbuf);
extern void nf_ipcam_get_default_login_info(char *p_id, char *p_pw);

void nf_ipcam_zmq_server_start();
void nf_ipcam_zmq_server_stop();
int nf_ipcam_get_channel_from_macaddr(char *p_str);
int nf_ipcam_get_channel_from_ipaddr(char *ipaddr);
int nf_ipcam_change_ipcamres_to_size(const uint64_t camres, unsigned int *width, unsigned int *height);
#endif	// __NF_API_IPCAM_H__
