#ifndef _NF_LOGEVTDEF_H_
#define _NF_LOGEVTDEF_H_

// just test code below 
#define	IDVA_ET_INTRUSION_DETECTION	0x00000000
#define IDVA_ET_ILLEGAL_PARKING 	0x00000000
#define IDVA_ET_LPR					0x00000000

/*
 * Log/Event Categories: Just to classify log/event, not used in real implementation.
 */
typedef enum {
	SYSTEM_LOGEVT,
	LOGON_LOGEVT,
	SETUP_LOGEVT,
	EVENT_LOGEVT,
	RECORD_LOGEVT,
	POS_LOGEVT,
	IPCAM_LOGEVT
} log_evt_category_e;

/*
 * Log/Event Types.
 */
typedef enum {
	/* Types for SYSTEM_LOGEVT category. */
/* 00 */	LT_SYSTEM_STARTED,
/* 01 */	LT_SYSTEM_SHUTDOWN,
/* 02 */	LT_ABNORMAL_SHUTDOWN_DETECTED,
/* 03 */	LT_SYSTEM_RECOVERED,
/* 04 */	LT_SYSTEM_TIME_CHANGED,
/* 05 */	LT_SYSTEM_FW_UPGRADE,
/* 06 */	LT_SYSTEM_FORMAT,
/* 07 */	LT_SYSTEM_SYSLOG,
/* -- */	/* Types for LOGON_LOGEVT category. */
/* 08 */	LT_LOCAL_LOG_ON,
/* 09 */	LT_LOCAL_LOG_OFF,
/* 10 */	LT_REMOTE_LOG_ON,
/* 11 */	LT_REMOTE_LOG_OFF,
/* -- */	/* Types for SETUP_LOGEVT category. */
/* 12 */	LT_RECORD_SETUP_CHANGED,
/* 13 */	LT_SYSTEM_SETUP_CHANGED,
/* -- */	/* Types for EVENT_LOGEVT category. */
/* 14 */	LT_SENSOR_INPUT,
/* 15 */	LT_MOTION_DETECTION,	
/* 16 */	LT_VIDEO_IN,		
/* 17 */	LT_VIDEO_LOSS,
/* 18 */	LT_TAMPER,
/* 19 */	LT_SMART_WARNING,	

///* 20 */	LT_HDD_OVER_TEMP,
/* 20 */	LT_DISK_EVENT,		

/* 21 */	LT_HDD_FULL,
/* 22 */	LT_HDD_OW,
/* -- */	/* Types for RECORD_LOGEVT category. */
/* 23 */	LT_RECORD_STARTED,
/* 24 */	LT_RECORD_STOPPED,
/* -- */	/* Types for SYSTEM_LOGEVT category. 2009-05-26 오전 1:18:45 */	
/* 25 */	LT_SYSTEM_EVENT,
/* 26 */	LT_SYSTEM_DEBUG,
/* 27 */	LT_SYSTEM_POS,
/* 28 */	LT_NETWORK_EVENT,
/* 29 */	LT_IPCAM,
/* 30 */	LT_VCA,
/* 31 */	LT_DVA,
/* -- */	/* Must not exceed 31 */
/* 32 */	LT_NR
} log_evt_type_e;


// please erase under three line & this line after erasing HDD over temperture
#define LT_HDD_OVER_TEMP 20
#define LT_MASK_HDD_OVER_TEMP 0x00100000
#define	LOG_P1_MASKOFS_HDD_OVER_TEMP				( LOG_P1_MASKOFS_SMART_WARNING + LOG_P1T_MASKSIZE_NA )	



// !!! must check nf_api_eventlog.c  _eventlog_str array
typedef enum _log_evt_type_mask_e {
	LT_MASK_SYSTEM_STARTED					= 0x00000001,
	LT_MASK_SYSTEM_SHUTDOWN					= 0x00000002,
	LT_MASK_ABNORMAL_SHUTDOWN_DETECTED		= 0x00000004, 	
	LT_MASK_SYSTEM_RECOVERED				= 0x00000008, 
	LT_MASK_SYSTEM_TIME_CHANGED				= 0x00000010, 
	LT_MASK_SYSTEM_FW_UPGRADE				= 0x00000020, 
	LT_MASK_SYSTEM_FORMAT					= 0x00000040, 
	LT_MASK_SYSTEM_CHECKDISK				= 0x00000080,  
	LT_MASK_LOCAL_LOG_ON					= 0x00000100, 
	LT_MASK_LOCAL_LOG_OFF					= 0x00000200, 
	LT_MASK_REMOTE_LOG_ON					= 0x00000400, 
	LT_MASK_REMOTE_LOG_OFF					= 0x00000800, 
	LT_MASK_RECORD_SETUP_CHANGED			= 0x00001000, 
	LT_MASK_SYSTEM_SETUP_CHANGED		    = 0x00002000, 
	LT_MASK_SENSOR_INPUT					= 0x00004000, 
	LT_MASK_MOTION_DETECTION				= 0x00008000,  
	LT_MASK_VIDEO_IN		                = 0x00010000,   
	LT_MASK_VIDEO_LOSS						= 0x00020000,  
	LT_MASK_TAMPER							= 0x00040000,  
	LT_MASK_SMART_WARNING	                = 0x00080000,  
	
//	LT_MASK_HDD_OVER_TEMP					= 0x00100000,  
	LT_MASK_DISK_EVENT						= 0x00100000,  

	LT_MASK_HDD_FULL		                = 0x00200000,  
	LT_MASK_HDD_OW							= 0x00400000,  
	LT_MASK_RECORD_STARTED					= 0x00800000,
	LT_MASK_RECORD_STOPPED					= 0x01000000,
	LT_MASK_SYSTEM_EVENT					= 0x02000000,	// 2009-05-26 오전 1:20:11
	LT_MASK_SYSTEM_DEBUG					= 0x04000000,
	LT_MASK_SYSTEM_POS						= 0x08000000,
	LT_MASK_NETWORK_EVENT					= 0x10000000,
	LT_MASK_IPCAM							= 0x20000000,
	LT_MASK_VCA								= 0x40000000,
	LT_MASK_DVA								= 0x80000000
}log_evt_type_mask_e;

#define	MAX_LOG_TYPES	32

/*
 * Parameter1 for each type.
 */

/* Parameter1 types. */
typedef enum {
	LOG_P1T_NA,		/* Parameter1 is not used. */
	LOG_P1T_WHO,	/* Parameter1 is used to indicate user id: string index in log's text section. */
	LOG_P1T_CHAN,	/* Parameter1 is used to indicate its channel number. */
//	LOG_P1T_EVTN	/* Parameter1 is used to indicate its event number. */
} log_evt_param1_type;

/* Parameter2 values for FW_UPGRADE type. */
enum {
	LP2_FW_UPGRADE_NORMAL,
	LP2_FW_UPGRADE_START,
	LP2_FW_UPGRADE_SUCCESS,
	LP2_FW_UPGRADE_FAIL
};

/* Parameter2 values for FW_UPGRADE type. */
enum {
	LP2_RBOOT_UNKNOWN,
	LP2_RBOOT_POORCOMM,
	LP2_RBOOT_DISKERR,
	LP2_RBOOT_RECORDERR,
	LP2_RBOOT_RECOVERYERR,
};

/* Parameter2 values for SYSLOG type. */
enum {
	LP2_SYS_DISK_CHECK,
	LP2_SYS_CAM_RECONNECT_TIMECHANGE,
	LP2_SYS_CAM_RECONNECT_FWUP,
	LP2_SYS_CAM_RECONNECT_DBLOAD,
	LP2_SYS_CAM_RECONNECT_FACTORY,
	LP2_SYS_CAM_RECONNECT_IPCHANGE,
	LP2_SYS_CAM_RECONNECT_INSTALLMODE,
	LP2_SYS_PANIC_RECORD_START,
	LP2_SYS_PANIC_RECORD_STOP,
	LP2_SYS_PTZ_CTRL_START,
	LP2_SYS_PTZ_CTRL_STOP,
	LP2_SYS_ADMIN_SESSION_LOCK,
	LP2_SYS_ADMIN_SESSION_UNLOCK,
	LP2_SYS_STORAGE_PLUG,
	LP2_SYS_STORAGE_UNPLUG,
	LP2_SYS_TIMECHANGE_INFO,
	LP2_SYS_UPGRADE_INFO,
	LP2_SYS_BACKUPVERIFY_INFO,
	LP2_SYS_ALLOW_LIST_ADD,
	LP2_SYS_ALLOW_LIST_DEL,
	LP2_SYS_DENY_LIST_ADD,
	LP2_SYS_DENY_LIST_DEL,
	LP2_SYS_SYSTEM_RESTART,
};

/* Parameter1 values are specific to log types. */

/*
 * Parameter2 for each type.
 */
/* Parameter2 values for LOCAL_LOG_ON type. */
enum {
	LP2_LOCAL_LOG_ON_LIVE_DISPLAY,
	LP2_LOCAL_LOG_ON_PLAY_BACK,
	LP2_LOCAL_LOG_ON_ARCHIVING,
	LP2_LOCAL_LOG_ON_SYSTEM_SETUP,
	LP2_LOCAL_LOG_ON_RECORD_SETUP,
	LP2_LOCAL_LOG_ON_NR
};

/* Parameter2 values for LOCAL_LOG_OFF type. */
enum {
	LP2_LOCAL_LOG_OFF_LIVE_DISPLAY,
	LP2_LOCAL_LOG_OFF_PLAY_BACK,
	LP2_LOCAL_LOG_OFF_ARCHIVING,
	LP2_LOCAL_LOG_OFF_SYSTEM_SETUP,
	LP2_LOCAL_LOG_OFF_RECORD_SETUP,
	LP2_LOCAL_LOG_OFF_NR
};

/* Parameter2 values for REMOTE_LOG_ON type */
enum {
	LP2_REMOTE_LOG_ON_LIVE_DISPLAY,
	LP2_REMOTE_LOG_ON_PLAY_BACK,
	LP2_REMOTE_LOG_ON_ARCHIVING,
	LP2_REMOTE_LOG_ON_SYSTEM_SETUP,
	LP2_REMOTE_LOG_ON_RECORD_SETUP,
	LP2_REMOTE_LOG_ON_NR
};

/* Parameter2 values for REMOTE_LOG_OFF type */
enum {
	LP2_REMOTE_LOG_OFF_LIVE_DISPLAY,
	LP2_REMOTE_LOG_OFF_PLAY_BACK,
	LP2_REMOTE_LOG_OFF_ARCHIVING,
	LP2_REMOTE_LOG_OFF_SYSTEM_SETUP,
	LP2_REMOTE_LOG_OFF_RECORD_SETUP,
	LP2_REMOTE_LOG_OFF_NR
};

/* Parameter2 values for RECORD_SETUP_CHANGED type. */
enum {
	LP2_RECORD_SETUP_CHANGED_MODE,
	LP2_RECORD_SETUP_CHANGED_SIMPLE_PARAM,		// not used
	LP2_RECORD_SETUP_CHANGED_SIMPLE_SCHED,		// not used
	LP2_RECORD_SETUP_CHANGED_INTENSIVE_PARAM,	// not used
	LP2_RECORD_SETUP_CHANGED_INTENSIVE_SCHED,	// not used
	LP2_RECORD_SETUP_CHANGED_SWITCHING_PARAM,	// not used
	LP2_RECORD_SETUP_CHANGED_SWITCHING_SCHED,	// not used
	LP2_RECORD_SETUP_CHANGED_PANIC_PARAM,	

	LP2_RECORD_SETUP_CHANGED_REC_OP,			// not used
	LP2_RECORD_SETUP_CHANGED_SIMPLE_REC,		// not used
	LP2_RECORD_SETUP_CHANGED_AVD_REC_DAY_PARAM,	// not used
	LP2_RECORD_SETUP_CHANGED_AVD_REC_DAY_SCHED,	// not used
	LP2_RECORD_SETUP_CHANGED_AVD_REC_WEEK_PARAM,// not used
    LP2_RECORD_SETUP_CHANGED_AVD_REC_WEEK_SCHED,// not used

	LP2_RECORD_SETUP_CHANGED_CONT_PARAM,		// not used
	LP2_RECORD_SETUP_CHANGED_CONT_SCHED,		// not used
	LP2_RECORD_SETUP_CHANGED_ALARM_PARAM,
	LP2_RECORD_SETUP_CHANGED_ALARM_SCHED,
	LP2_RECORD_SETUP_CHANGED_CONTMOT_PARAM,	
	LP2_RECORD_SETUP_CHANGED_CONTMOT_SCHED,
	LP2_RECORD_SETUP_CHANGED_MOTION_PARAM,		// not used
	LP2_RECORD_SETUP_CHANGED_MOTION_SCHED,		// not used

	LP2_RECORD_SETUP_CHANGED_DUAL_PARAM,		// OTM
	LP2_RECORD_SETUP_CHANGED_DUAL_SCHED,		// not used

	LP2_RECORD_SETUP_CHANGED_NR
};

/* Parameter2 values for SYSTEM_SETUP_CHANGED type. */
enum {
	LP2_SYSTEM_SETUP_CHANGED_CAMERA_TITLE,
	LP2_SYSTEM_SETUP_CHANGED_CAMERA_COLOR,
	LP2_SYSTEM_SETUP_CHANGED_CAMERA_PTZ,
	LP2_SYSTEM_SETUP_CHANGED_CAMERA_OSD,
	LP2_SYSTEM_SETUP_CHANGED_EVENT_SENSOR,
	LP2_SYSTEM_SETUP_CHANGED_EVENT_VLOSS,	
	LP2_SYSTEM_SETUP_CHANGED_EVENT_MOTION,		
	LP2_SYSTEM_SETUP_CHANGED_EVENT_STORAGE,
	LP2_SYSTEM_SETUP_CHANGED_EVENT,					// not used
	LP2_SYSTEM_SETUP_CHANGED_ACT_RELAY,
	LP2_SYSTEM_SETUP_CHANGED_ACT_EMAIL,
	LP2_SYSTEM_SETUP_CHANGED_ACT_REMOTE,			// not used
	LP2_SYSTEM_SETUP_CHANGED_ACT_VPOP,				// not used
	LP2_SYSTEM_SETUP_CHANGED_ACT_BUZZ,
	LP2_SYSTEM_SETUP_CHANGED_DISP_TEMP,				// not used
	LP2_SYSTEM_SETUP_CHANGED_DISP_MAIN_SEQ,
	LP2_SYSTEM_SETUP_CHANGED_DISP_SPOT1_SEQ,
	LP2_SYSTEM_SETUP_CHANGED_DISP_SPOT2_SEQ,
	LP2_SYSTEM_SETUP_CHANGED_DISP_SPOT3_SEQ,
	LP2_SYSTEM_SETUP_CHANGED_DISP_SPOT4_SEQ,
	LP2_SYSTEM_SETUP_CHANGED_AUDIO,
	LP2_SYSTEM_SETUP_CHANGED_USER_ID,
	LP2_SYSTEM_SETUP_CHANGED_USER_GRP,
	LP2_SYSTEM_SETUP_CHANGED_NET_PROTO,				// not used 
	LP2_SYSTEM_SETUP_CHANGED_NET_EMAIL,
	LP2_SYSTEM_SETUP_CHANGED_SYSTEM_INFO,
	LP2_SYSTEM_SETUP_CHANGED_SYSTEM_DATE,
	LP2_SYSTEM_SETUP_CHANGED_STORAGE_OP,
	
	LP2_SYSTEM_SETUP_CHANGED_CAMERA_COVERT,			// 2009-05-26 오전 1:24:34 
	LP2_SYSTEM_SETUP_CHANGED_CAMERA_MOTION_SENSOR,
	LP2_SYSTEM_SETUP_CHANGED_USER_MANAGEMENT,		// not used 
	LP2_SYSTEM_SETUP_CHANGED_SYSTEM_MANAGEMENT,
	LP2_SYSTEM_SETUP_CHANGED_CAMERA_AUDIO_MAPPING,
	LP2_SYSTEM_SETUP_CHANGED_DISPLAY_OSD,
	LP2_SYSTEM_SETUP_CHANGED_DISPLAY_MONITOR,
	LP2_SYSTEM_SETUP_CHANGED_AUDIO_BUZZER,
	LP2_SYSTEM_SETUP_CHANGED_CONTROL_DEVICE,
	LP2_SYSTEM_SETUP_CHANGED_AUTO_LOGOUT,
	LP2_SYSTEM_SETUP_CHANGED_NETWORK_IP,
	LP2_SYSTEM_SETUP_CHANGED_NETWORK_DDNS,

	LP2_SYSTEM_SETUP_CHANGED_CAM_IMAGE,				//2011-06-30
	LP2_SYSTEM_SETUP_CHANGED_DIS_SEQ,
	LP2_SYSTEM_SETUP_CHANGED_SYS_TXTIN,
	LP2_SYSTEM_SETUP_CHANGED_STORAGE_SMART,
	LP2_SYSTEM_SETUP_CHANGED_ACT_SYSTEM,
	LP2_SYSTEM_SETUP_CHANGED_ACT_TXTIN,
	LP2_SYSTEM_SETUP_CHANGED_ACT_NOTIFICATION,
	LP2_SYSTEM_SETUP_CHANGED_ALARM_OUT,
	LP2_SYSTEM_SETUP_CHANGED_LIVELAYOUT,
	LP2_SYSTEM_SETUP_CHANGED_TAMPER,
	LP2_SYSTEM_SETUP_CHANGED_PRIVACY_MASK,
	LP2_SYSTEM_SETUP_CHANGED_CAMERA_VCA,
	LP2_SYSTEM_SETUP_CHANGED_EVENT_VCA,
	LP2_SYSTEM_SETUP_CHANGED_EMAIL_SSL_ON,
	LP2_SYSTEM_SETUP_CHANGED_EMAIL_SSL_OFF,
	
	LP2_SYSTEM_SETUP_CHANGED_CABLE_TEST,
	LP2_SYSTEM_SETUP_CHANGED_PASSWD_REISSUE,
	LP2_SYSTEM_SETUP_CHANGED_LOOP_OUT,
	LP2_SYSTEM_SETUP_CHANGED_ANALOG_TYPE,
	LP2_SYSTEM_SETUP_CHANGED_BUZZER_OFF,
	LP2_SYSTEM_SETUP_CHANGED_USER_ADD,
	LP2_SYSTEM_SETUP_CHANGED_USER_DEL,

	LP2_SYSTEM_SETUP_CHANGED_NR
};

/* Parameter2 values for SENSOR_INPUT type. */
enum {
	LP2_SENSOR_INPUT_OFF,
	LP2_SENSOR_INPUT_ON,
	LP2_SENSOR_INPUT_NR
};

/* Parameter2 values for MOTION_DETECTION type. */
enum {
	LP2_MOTION_DETECTION_OFF,
	LP2_MOTION_DETECTION_ON,
	LP2_MOTION_DETECTION_NR
};

/* Parameter2 values for VIDEO_LOSS type. */
enum {
	LP2_VIDEO_LOSS_OFF,
	LP2_VIDEO_LOSS_ON,
	LP2_VIDEO_LOSS_NR
};

/* Parameter2 values for TAMPER type. */
enum {
	LP2_TAMPER_REDIRECTION,
	LP2_TAMPER_BLOCKAGE,
	LP2_TAMPER_DEFOCUSING,
	LP2_TAMPER_NR
};

/* Parameter2 values for SMART_EVENT type */
enum {
	LP2_SMART_WARNING_INTERNAL,
	LP2_SMART_WARNING_EXTERNAL,
	LP2_SMART_WARNING_NR
};

#if 0			//2011-06-30 changed to DISK_EVENT.
/* Parameter2 values for HDD_OVER_TEMP */
enum {
	LP2_HDD_OVER_TEMP_INTERMAL,
	LP2_HDD_OVER_TEMP_EXTERNAL,
	LP2_HDD_OVER_TEMP_NR
};
#else
/* Parameter2 values for DISK_EVENT  */			//2011-06-30
enum {
	LP2_DISK_EVENT_NO_DISK,
	LP2_DISK_EVENT_ADD,
	LP2_DISK_EVENT_REMOVE,
	LP2_DISK_EVENT_IO_ERROR,
	LP2_DISK_EVENT_UNC_DETECTED,
	LP2_DISK_EVENT_UNC_RECOVERED,
	LP2_DISK_EVENT_DISK_EXHAUSTED,
	LP2_DISK_EVENT_SET_RTL,
	LP2_DISK_EVENT_SET_OVERWRITE,
	LP2_DISK_EVENT_SET_WRITEONCE,
	LP2_DISK_EVENT_NR
};
#endif

/* Parameter2 values for HDD_FULL */
enum {
	LP2_HDD_FULL_INTERMAL,
	LP2_HDD_FULL_EXTERNAL,
	LP2_HDD_FULL_NR
};

/* Parameter2 values for HDD_OW */
enum {
	LP2_HDD_OW_INTERMAL,
	LP2_HDD_OW_EXTERNAL,
	LP2_HDD_OW_NR
};

/* Parameter2 values for RECORD_STARTED type. */
enum {
	LP2_RECORD_STARTED_TIMER,	// CONTINUOUS
	LP2_RECORD_STARTED_SENSOR,
	LP2_RECORD_STARTED_MOTION,
	LP2_RECORD_STARTED_USER_EVENT,			// not used
	LP2_RECORD_STARTED_PANIC,
	LP2_RECORD_STARTED_NR
};

/* Parameter2 values for RECORD_STOPPED type. */
enum {
	LP2_RECORD_STOPPED_TIMER,	// CONTINUOUS
	LP2_RECORD_STOPPED_SENSOR,
	LP2_RECORD_STOPPED_MOTION,
	LP2_RECORD_STOPPED_USER_EVENT,			// not used
	LP2_RECORD_STOPPED_PANIC,
	LP2_RECORD_STOPPED_NR
};

/* Parameter2 values for LT_SYSTEM_EVENT type. */
enum {	
	LP2_SYSTEM_EVENT_EMAIL_SENT,
	LP2_SYSTEM_EVENT_ARCHIVE_START,
	LP2_SYSTEM_EVENT_ARCHIVE_END,
	LP2_SYSTEM_EVENT_FACTORY_DEFAULT,
	LP2_SYSTEM_EVENT_SYSTEM_DATA_SAVE,
	LP2_SYSTEM_EVENT_SYSTEM_DATA_LOAD,

	LP2_SYSTEM_EVENT_NO_VIDEO,					//2011-06-30
	LP2_SYSTEM_EVENT_CPU_FAN_FAIL,
	LP2_SYSTEM_EVENT_CPU_FAN_CURRENT,
	LP2_SYSTEM_EVENT_SYS_FAN_FAIL,
	LP2_SYSTEM_EVENT_SYS_FAN_CURRENT,
	LP2_SYSTEM_EVENT_CPU_TEMP_FAIL,
	LP2_SYSTEM_EVENT_CPU_TEMP_CURRENT,
	LP2_SYSTEM_EVENT_SYS_TEMP_FAIL,
	LP2_SYSTEM_EVENT_SYS_TEMP_CURRENT,
	LP2_SYSTEM_EVENT_RTC_BATTERY_FAIL,
	LP2_SYSTEM_EVENT_AUTO_TIME_SYNC_FAIL,
	LP2_SYSTEM_EVENT_AUTO_TIME_SYNC_OK,
	LP2_SYSTEM_EVENT_LOCAL_LOGIN_FAIL,
	LP2_SYSTEM_EVENT_LOCAL_AUTO_LOGOUT,
	LP2_SYSTEM_EVENT_TIMEZONE_CHANGED,
	LP2_SYSTEM_EVENT_LANGUAGE_CHANGED,
	LP2_SYSTEM_EVENT_DATA_RESERVED,
	LP2_SYSTEM_EVENT_RESERVED_DATA_REMOVED,
	LP2_SYSTEM_EVENT_POE_FAIL,
	LP2_SYSTEM_EVENT_PRIVACY_FRAME,
	LP2_SYSTEM_EVENT_ERASED_RANGE,		// 2012-12-28 오후 2:00:52 choissi	
	LP2_SYSTEM_EVENT_ABNORMAL_REBOOT,		// not used
	LP2_SYSTEM_EVENT_REMOTE_MNG_START,
	LP2_SYSTEM_EVENT_REMOTE_MNG_STOP,
	LP2_SYSTEM_EVENT_SYSTEM_DIAGNOSIS,
	LP2_SYSTEM_EVENT_REMOTE_MNG_KEY,
	LP2_SYSTEM_EVENT_CABLE_TEST,
	LP2_SYSTEM_EVENT_CABLE_TEST_WARN,
	LP2_SYSTEM_EVENT_AUTH_CODE_ISSUED,
	LP2_SYSTEM_EVENT_POE_WATT,
	LP2_SYSTEM_EVENT_POE_WATT_TOTAL,
	LP2_SYSTEM_EVENT_ARM,
	LP2_SYSTEM_EVENT_DISARM,
	LP2_SYSTEM_EVENT_LOGIN_LOCK,
	LP2_SYSTEM_EVENT_SYSTEM_DIAGNOSIS_MAN,
	LP2_SYSTEM_EVENT_SYSTEM_DIAGNOSIS_AUTO,
	LP2_SYSTEM_EVENT_SYSTEM_DIAGNOSIS_SVR,
	LP2_SYSTEM_EVENT_LOGIN_LOCK_WITH_ID,
	LP2_SYSTEM_EVENT_SYSTEM_INTRUSION_DETECTION,
	LP2_SYSTEM_EVENT_SYSTEM_ILLEGAL_PARKING,
	LP2_SYSTEM_EVENT_SYSTEM_LPR,
	LP2_SYSTEM_EVENT_AUTO_PHONE_NUMBER_SYNC,
	LP2_SYSTEM_EVENT_S1VM_FIRE,
	LP2_SYSTEM_EVENT_S1VM_EMERGENCY,
	LP2_SYSTEM_EVENT_S1VM_INTRUSION_ERROR,
	LP2_SYSTEM_EVENT_NR
};

/* Parameter2 values for LT_SYSTEM_DEBUG type. */
enum {
	LP2_SYSTEM_DEBUG_ERROR_LOG,
	LP2_SYSTEM_DEBUG_STRING,

	LP2_SYSTEM_DEBUG_EMERG,						//2011-06-30
	LP2_SYSTEM_DEBUG_ALERT,
	LP2_SYSTEM_DEBUG_CRIT,
	LP2_SYSTEM_DEBUG_ERR,
	LP2_SYSTEM_DEBUG_WARNING,
	LP2_SYSTEM_DEBUG_NOTICE,
	LP2_SYSTEM_DEBUG_INFO,
	LP2_SYSTEM_DEBUG_DEBUG,
	
	LP2_SYSTEM_DEBUG_BOOTING_FAIL,
	LP2_SYSTEM_DEBUG_HDD_REMOVED_BY_USER,
	LP2_SYSTEM_DEBUG_SYSBD_IMPORT,
	LP2_SYSTEM_DEBUG_SYSBD_EXPORT,
	LP2_SYSTEM_DEBUG_DATA_RESERVED,
	LP2_SYSTEM_DEBUG_RESERVED_DATA_REMOVED,
	LP2_SYSTEM_DEBUG_CONNECT_USER,
	LP2_SYSTEM_DEBUG_DISCONNECT_USER,
	LP2_SYSTEM_DEBUG_FW_UPGRADE_PING,
	LP2_SYSTEM_DEBUG_FW_UPGRADE_PONG,
	LP2_SYSTEM_DEBUG_WATCHDOG,
	LP2_SYSTEM_DEBUG_IFS_HOLD_SYSTEM,
	LP2_SYSTEM_DEBUG_UI_HOLD_SYSTEM,
	LP2_SYSTEM_DEBUG_UI_HOLD_SYSTEM_BACKTRACE,
	LP2_SYSTEM_DEBUG_SYSTEM_TIME_CHANGED,
	LP2_SYSTEM_DEBUG_SMART_CHECK,
	LP2_SYSTEM_DEBUG_HOTKEY,
	LP2_SYSTEM_DEBUG_NR

};

/* Parameter2 values for LT_SYSTEM_POS type. */			//2011-06-30
enum {
	LP2_SYSTEM_POS_NR
};

/* Parameter2 values for LT_NETWORK_EVENT type. */		//2011-06-30
enum {
	LP2_NETWORK_WAN_PORT_STATUS_ON,
	LP2_NETWORK_WAN_PORT_STATUS_OFF,
	LP2_NETWORK_LAN_PORT_STATUS_ON,
	LP2_NETWORK_LAN_PORT_STATUS_OFF,
	LP2_NETWORK_SWITCH_LINK,
	LP2_NETWORK_SWITCH_UNLINK,
	LP2_NETWORK_SWITCH_TIMEOUT,
	LP2_NETWORK_SWITCH_UNKNOWN_DEVICE,
	LP2_NETWORK_IP_CONFILICT_DETECTED,
	LP2_NETWORK_IP_CHANGED,
	LP2_NETWORK_DHCP_OK,
	LP2_NETWORK_DHCP_IPCHANGED,
	LP2_NETWORK_DHCP_FAIL,
	LP2_NETWORK_NETWORK_ATTACK_DETECTED,
	LP2_NETWORK_BAD_DNS,
	LP2_NETWORK_BAD_GW,
	LP2_NETWORK_DDNS_FAIL,
	LP2_NETWORK_WAN_FAIL,
	LP2_NETWORK_EMAIL_SEND_FAIL,
	LP2_NETWORK_TIME_SYNC_FAIL,
	LP2_NETWORK_LOGIN_FAIL,
	LP2_NETWORK_IPCAM_IP_CONFILICT_DETECTED,			// 2015-05-20 오후 4:19:45
	LP2_NETWORK_EVENT_SIP_GOOD,
	LP2_NETWORK_EVENT_SIP_ERROR,
	LP2_NETWORK_EVENT_AIBOX_CONNECTED,
	LP2_NETWORK_EVENT_AIBOX_DISCONNECTED,
	LP2_NETWORK_NR
};

/* Parameter2 values for LT_IPCAM type. */				//2011-06-30
enum {
	LP2_IPCAM_DEVICE_READY,
	LP2_IPCAM_DEVICE_OUT,
	LP2_IPCAM_DEVICE_RESET,
	LP2_IPCAM_UNKNOWN_DEVICE,
	LP2_IPCAM_CONNECTION_FAIL,
	LP2_IPCAM_LOGIN_FAIL,
	LP2_IPCAM_CONFIGURAION_FAIL,
	LP2_IPCAM_UNSUPPORT_MODEL,
	LP2_IPCAM_SOCK_ERROR,
	LP2_IPCAM_RINGFULL_ERROR,
	LP2_IPCAM_MAGIC_ERROR,
	LP2_IPCAM_MEM_FAIL,
	LP2_IPCAM_CMEM_FAIL,
	LP2_IPCAM_SYSTIME_ERROR,
	LP2_IPCAM_TIMESTAMP_ERROR,
	LP2_IPCAM_PACKET_LOSS,
	LP2_IPCAM_FRAME_LOSS,
	LP2_IPCAM_NR
};


/* Parameter2 is not used for other log/event types. */


#define	MAX_LOG_STRLEN		22		/* In single log entry */
#define	MAX_LOG_ESTRLEN		255		/* Expanded Log string */

/** ********************************************************************* **
 ** typedefs
 ** ********************************************************************* **/

/** ********************************************************************* **
 ** globals
 ** ********************************************************************* **/

/** ********************************************************************* **
 ** locals
 ** ********************************************************************* **/

#define	LOG_P1T_MASKSIZE_NA		0		/* LOG_P1T_NA */
#define	LOG_P1T_MASKSIZE_WHO	32		/* LOG_P1T_WHO: include NULL */
#define	LOG_P1T_MASKSIZE_CHAN	4		/* LOG_P1T_CHAN: 32bits - bitwise 32 channels. */
//#define	LOG_P1T_MASKSIZE_EVTN	8		/* LOG_P1T_EVTN: 64bits - bitwise 64 events. */

#define	LOG_P1_MASKOFS_SYSTEM_STARTED				0
#define	LOG_P1_MASKOFS_SYSTEM_SHUTDOWN				( LOG_P1_MASKOFS_SYSTEM_STARTED + LOG_P1T_MASKSIZE_NA )
#define	LOG_P1_MASKOFS_ABNORMAL_SHUTDOWN_DETECTED	( LOG_P1_MASKOFS_SYSTEM_SHUTDOWN + LOG_P1T_MASKSIZE_NA )
#define	LOG_P1_MASKOFS_SYSTEM_RECOVERED				( LOG_P1_MASKOFS_ABNORMAL_SHUTDOWN_DETECTED + LOG_P1T_MASKSIZE_NA )
#define	LOG_P1_MASKOFS_TIME_CHANGED					( LOG_P1_MASKOFS_SYSTEM_RECOVERED + LOG_P1T_MASKSIZE_NA )
#define	LOG_P1_MASKOFS_FW_UPGRADE					( LOG_P1_MASKOFS_TIME_CHANGED + LOG_P1T_MASKSIZE_WHO )
#define	LOG_P1_MASKOFS_FORMAT						( LOG_P1_MASKOFS_FW_UPGRADE + LOG_P1T_MASKSIZE_WHO )
#define	LOG_P1_MASKOFS_CHECKDISK					( LOG_P1_MASKOFS_FORMAT + LOG_P1T_MASKSIZE_WHO )
#define	LOG_P1_MASKOFS_LOCAL_LOG_ON					( LOG_P1_MASKOFS_CHECKDISK + LOG_P1T_MASKSIZE_WHO )
#define	LOG_P1_MASKOFS_LOCAL_LOG_OFF				( LOG_P1_MASKOFS_LOCAL_LOG_ON + LOG_P1T_MASKSIZE_WHO )
#define	LOG_P1_MASKOFS_REMOTE_LOG_ON				( LOG_P1_MASKOFS_LOCAL_LOG_OFF + LOG_P1T_MASKSIZE_WHO )
#define	LOG_P1_MASKOFS_REMOTE_LOG_OFF				( LOG_P1_MASKOFS_REMOTE_LOG_ON + LOG_P1T_MASKSIZE_WHO )
#define	LOG_P1_MASKOFS_RECORD_SETUP_CHANGED			( LOG_P1_MASKOFS_REMOTE_LOG_OFF + LOG_P1T_MASKSIZE_WHO )
#define	LOG_P1_MASKOFS_SYSTEM_SETUP_CHANGED			( LOG_P1_MASKOFS_RECORD_SETUP_CHANGED + LOG_P1T_MASKSIZE_WHO )
#define	LOG_P1_MASKOFS_SENSOR_INPUT					( LOG_P1_MASKOFS_SYSTEM_SETUP_CHANGED + LOG_P1T_MASKSIZE_WHO )
#define	LOG_P1_MASKOFS_MOTION_DETECTION				( LOG_P1_MASKOFS_SENSOR_INPUT + LOG_P1T_MASKSIZE_CHAN )
#define	LOG_P1_MASKOFS_VIDEO_IN						( LOG_P1_MASKOFS_MOTION_DETECTION + LOG_P1T_MASKSIZE_CHAN )
#define	LOG_P1_MASKOFS_VIDEO_LOSS					( LOG_P1_MASKOFS_VIDEO_IN + LOG_P1T_MASKSIZE_CHAN )
#define	LOG_P1_MASKOFS_TAMPER						( LOG_P1_MASKOFS_VIDEO_LOSS + LOG_P1T_MASKSIZE_CHAN )
#define	LOG_P1_MASKOFS_SMART_WARNING				( LOG_P1_MASKOFS_TAMPER + LOG_P1T_MASKSIZE_CHAN )
#define	LOG_P1_MASKOFS_DISK_EVENT					( LOG_P1_MASKOFS_SMART_WARNING + LOG_P1T_MASKSIZE_NA )				///smart ????? na?
#define	LOG_P1_MASKOFS_HDD_FULL						( LOG_P1_MASKOFS_DISK_EVENT + LOG_P1T_MASKSIZE_NA )
#define	LOG_P1_MASKOFS_HDD_OW						( LOG_P1_MASKOFS_HDD_FULL + LOG_P1T_MASKSIZE_NA )
#define	LOG_P1_MASKOFS_RECORD_STARTED				( LOG_P1_MASKOFS_HDD_OW + LOG_P1T_MASKSIZE_NA )
#define	LOG_P1_MASKOFS_RECORD_STOPPED				( LOG_P1_MASKOFS_RECORD_STARTED + LOG_P1T_MASKSIZE_CHAN )
#define	LOG_P1_MASKOFS_SYSTEM_EVENT					( LOG_P1_MASKOFS_RECORD_STOPPED + LOG_P1T_MASKSIZE_CHAN )
#define	LOG_P1_MASKOFS_SYSTEM_DEBUG					( LOG_P1_MASKOFS_SYSTEM_EVENT + LOG_P1T_MASKSIZE_NA ) 
#define	LOG_P1_MASKOFS_SYSTEM_POS					( LOG_P1_MASKOFS_SYSTEM_DEBUG + LOG_P1T_MASKSIZE_NA ) 
#define	LOG_P1_MASKOFS_NETWORK_EVENT				( LOG_P1_MASKOFS_SYSTEM_POS + LOG_P1T_MASKSIZE_CHAN ) 	
#define	LOG_P1_MASKOFS_IPCAM						( LOG_P1_MASKOFS_NETWORK_EVENT + LOG_P1T_MASKSIZE_NA )	
#define	LOG_P1_MASKOFS_VCA							( LOG_P1_MASKOFS_IPCAM + LOG_P1T_MASKSIZE_CHAN )
#define	LOG_P1_MASKOFS_DVA							( LOG_P1_MASKOFS_VCA + LOG_P1T_MASKSIZE_CHAN )
#define	LOG_P1_MASK_SIZE							( LOG_P1_MASKOFS_DVA + LOG_P1T_MASKSIZE_CHAN )


/** ********************************************************************* **
 ** function protoypes
 ** ********************************************************************* **/
 
#endif	/* _NF_LOGEVTDEF_H_ */

