/* nf_session.h generated by valac 0.24.0, the Vala compiler, do not modify */


#ifndef __INCLUDE_NF_SESSION_H__
#define __INCLUDE_NF_SESSION_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define TYPE_NF_SESSION (nf_session_get_type ())
#define NF_SESSION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_NF_SESSION, NfSession))
#define NF_SESSION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_NF_SESSION, NfSessionClass))
#define IS_NF_SESSION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_NF_SESSION))
#define IS_NF_SESSION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_NF_SESSION))
#define NF_SESSION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_NF_SESSION, NfSessionClass))

typedef struct _NfSession NfSession;
typedef struct _NfSessionClass NfSessionClass;
typedef struct _NfSessionPrivate NfSessionPrivate;

#define TYPE_NF_SESSION_MANAGER (nf_session_manager_get_type ())
#define NF_SESSION_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_NF_SESSION_MANAGER, NfSessionManager))
#define NF_SESSION_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_NF_SESSION_MANAGER, NfSessionManagerClass))
#define IS_NF_SESSION_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_NF_SESSION_MANAGER))
#define IS_NF_SESSION_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_NF_SESSION_MANAGER))
#define NF_SESSION_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_NF_SESSION_MANAGER, NfSessionManagerClass))

typedef struct _NfSessionManager NfSessionManager;
typedef struct _NfSessionManagerClass NfSessionManagerClass;
typedef struct _NfSessionManagerPrivate NfSessionManagerPrivate;

struct _NfSession {
	GObject parent_instance;
	NfSessionPrivate * priv;
};

struct _NfSessionClass {
	GObjectClass parent_class;
};

struct _NfSessionManager {
	GObject parent_instance;
	NfSessionManagerPrivate * priv;
};

struct _NfSessionManagerClass {
	GObjectClass parent_class;
};


GType nf_session_get_type (void) G_GNUC_CONST;
NfSession* nf_session_new (const gchar* _usrid, guint _remote_port, glong _maxage);
NfSession* nf_session_construct (GType object_type, const gchar* _usrid, guint _remote_port, glong _maxage);
gboolean nf_session_isExpired (NfSession* self);
void nf_session_refreshExpire (NfSession* self);
void nf_session_refreshExpireSetUserTime (NfSession* self, glong sec);
gchar* nf_session_dump (NfSession* self);
const gchar* nf_session_get_uniqid (NfSession* self);
void nf_session_set_uniqid (NfSession* self, const gchar* value);
const gchar* nf_session_get_usrid (NfSession* self);
void nf_session_set_usrid (NfSession* self, const gchar* value);
guint nf_session_get_remote_port (NfSession* self);
void nf_session_set_remote_port (NfSession* self, guint value);
glong nf_session_get_expire (NfSession* self);
void nf_session_set_expire (NfSession* self, glong value);
glong nf_session_get_maxage (NfSession* self);
void nf_session_set_maxage (NfSession* self, glong value);
GType nf_session_manager_get_type (void) G_GNUC_CONST;
NfSessionManager* nf_session_manager_getInstance (void);
guint nf_session_manager_addSession (NfSessionManager* self, NfSession* nfsession);
void nf_session_manager_removeSession (NfSessionManager* self, NfSession* session);
NfSession* nf_session_manager_findSession (NfSessionManager* self, const gchar* sessionId);
NfSession* nf_session_manager_findSessionByIdx (NfSessionManager* self, gint index);
gchar* nf_session_manager_dump (NfSessionManager* self);


G_END_DECLS

#endif
