#ifndef __NF_UTIL_WPA_H__
#define __NF_UTIL_WPA_H__

typedef enum _NF_WPA_PROTOCOL {
	NF_WPA_EAP_TLS = 0,
	NF_WPA_EAP_MD5,
	NF_WPA_EAP_TTLS,
	NF_WPA_EAP_PEAP,
	NF_WPA_EAP_MAX
} NF_WPA_PROTOCOL;

typedef enum _NF_WPA_INNER_AUTH{
	NF_WPA_INNER_AUTH_CHAP = 0,
	NF_WPA_INNER_AUTH_EAP_MSCHAPV2,
	NF_WPA_INNER_AUTH_MD5,
	NF_WPA_INNER_AUTH_MSCHAP,
	NF_WPA_INNER_AUTH_MSCHAPV2,
	NF_WPA_INNER_AUTH_PAP,
	NF_WPA_INNER_AUTH_MAX
} NF_WPA_INNER_AUTH;

gboolean nf_wpa_start(void);

#endif
