#if 0
  #define WEB_NUM_VIDEO_CH 1

  #define WEB_NUM_SENSOR_LO16 0
  #define WEB_NUM_SENSOR_HI16 1
  #define WEB_NUM_SENSOR (WEB_NUM_SENSOR_LO16 + WEB_NUM_SENSOR_HI16)

  #define WEB_NUM_ALARM_LO16 0
  #define WEB_NUM_ALARM_HI16 1
  #define WEB_NUM_ALARM (WEB_NUM_ALARM_LO16 + WEB_NUM_ALARM_HI16)

  #define WEB_NUM_SENSOR_DVR    WEB_NUM_SENSOR_HI16
  #define WEB_NUM_SENSOR_CAM  WEB_NUM_SENSOR_LO16

  #define WEB_NUM_ALARM_DVR     WEB_NUM_ALARM_HI16
  #define WEB_NUM_ALARM_CAM   WEB_NUM_ALARM_LO16

  #define DVR_TYPE              DVR
  #define MOTIONTYPE            2
#endif
