/* nf_session.c generated by valac 0.24.0, the Vala compiler
 * generated from nf_session.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <stdio.h>


#define TYPE_NF_SESSION (nf_session_get_type ())
#define NF_SESSION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_NF_SESSION, NfSession))
#define NF_SESSION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_NF_SESSION, NfSessionClass))
#define IS_NF_SESSION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_NF_SESSION))
#define IS_NF_SESSION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_NF_SESSION))
#define NF_SESSION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_NF_SESSION, NfSessionClass))

typedef struct _NfSession NfSession;
typedef struct _NfSessionClass NfSessionClass;
typedef struct _NfSessionPrivate NfSessionPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_NF_SESSION_MANAGER (nf_session_manager_get_type ())
#define NF_SESSION_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_NF_SESSION_MANAGER, NfSessionManager))
#define NF_SESSION_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_NF_SESSION_MANAGER, NfSessionManagerClass))
#define IS_NF_SESSION_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_NF_SESSION_MANAGER))
#define IS_NF_SESSION_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_NF_SESSION_MANAGER))
#define NF_SESSION_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_NF_SESSION_MANAGER, NfSessionManagerClass))

typedef struct _NfSessionManager NfSessionManager;
typedef struct _NfSessionManagerClass NfSessionManagerClass;
typedef struct _NfSessionManagerPrivate NfSessionManagerPrivate;
#define _g_mutex_free0(var) ((var == NULL) ? NULL : (var = (g_mutex_free (var), NULL)))
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _NfSession {
	GObject parent_instance;
	NfSessionPrivate * priv;
};

struct _NfSessionClass {
	GObjectClass parent_class;
};

struct _NfSessionPrivate {
	gchar* dumpstr;
	gchar* _uniqid;
	gchar* _usrid;
	guint _remote_port;
	glong _expire;
	glong _maxage;
};

struct _NfSessionManager {
	GObject parent_instance;
	NfSessionManagerPrivate * priv;
};

struct _NfSessionManagerClass {
	GObjectClass parent_class;
};

struct _NfSessionManagerPrivate {
	GMutex* mutex;
	gboolean use_session_file;
	gchar* dumpstr;
	GList* sessionList;
};


static gpointer nf_session_parent_class = NULL;
static gpointer nf_session_manager_parent_class = NULL;
static NfSessionManager* nf_session_manager_instance;
static NfSessionManager* nf_session_manager_instance = NULL;

GType nf_session_get_type (void) G_GNUC_CONST;
#define NF_SESSION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_NF_SESSION, NfSessionPrivate))
enum  {
	NF_SESSION_DUMMY_PROPERTY,
	NF_SESSION_UNIQID,
	NF_SESSION_USRID,
	NF_SESSION_REMOTE_PORT,
	NF_SESSION_EXPIRE,
	NF_SESSION_MAXAGE
};
NfSession* nf_session_new (const gchar* _usrid, guint _remote_port, glong _maxage);
NfSession* nf_session_construct (GType object_type, const gchar* _usrid, guint _remote_port, glong _maxage);
static gchar* _nf_session_getuniqid (NfSession* self, guint remote_port);
void nf_session_set_uniqid (NfSession* self, const gchar* value);
void nf_session_set_remote_port (NfSession* self, guint value);
void nf_session_set_expire (NfSession* self, glong value);
void nf_session_set_maxage (NfSession* self, glong value);
void nf_session_set_usrid (NfSession* self, const gchar* value);
gboolean nf_session_isExpired (NfSession* self);
glong nf_session_get_expire (NfSession* self);
void nf_session_refreshExpire (NfSession* self);
void nf_session_refreshExpireSetUserTime (NfSession* self, glong sec);
glong nf_session_get_maxage (NfSession* self);
const gchar* nf_session_dump (NfSession* self);
const gchar* nf_session_get_usrid (NfSession* self);
guint nf_session_get_remote_port (NfSession* self);
const gchar* nf_session_get_uniqid (NfSession* self);
static void nf_session_finalize (GObject* obj);
static void _vala_nf_session_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_nf_session_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
#define SESSION_MAX 20
#define SESSION_FILE_PATH "/tmp/session"
GType nf_session_manager_get_type (void) G_GNUC_CONST;
#define NF_SESSION_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_NF_SESSION_MANAGER, NfSessionManagerPrivate))
enum  {
	NF_SESSION_MANAGER_DUMMY_PROPERTY
};
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
static NfSessionManager* nf_session_manager_new (void);
static NfSessionManager* nf_session_manager_construct (GType object_type);
NfSessionManager* nf_session_manager_getInstance (void);
guint nf_session_manager_addSession (NfSessionManager* self, NfSession* nfsession);
NfSession* nf_session_manager_findSession (NfSessionManager* self, const gchar* sessionId);
void nf_session_manager_removeSession (NfSessionManager* self, NfSession* session);
static gint __lambda3_ (NfSession* a, NfSession* b);
static gint ___lambda3__gcompare_func (gconstpointer a, gconstpointer b);
NfSession* nf_session_manager_findSessionByIdx (NfSessionManager* self, gint index);
const gchar* nf_session_manager_dump (NfSessionManager* self);
static void nf_session_manager_finalize (GObject* obj);


NfSession* nf_session_construct (GType object_type, const gchar* _usrid, guint _remote_port, glong _maxage) {
	NfSession * self = NULL;
	const gchar* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	GTimeVal tv = {0};
	guint _tmp2_ = 0U;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	guint _tmp5_ = 0U;
	glong _tmp6_ = 0L;
	GTimeVal _tmp7_ = {0};
	glong _tmp8_ = 0L;
	glong _tmp9_ = 0L;
	glong _tmp10_ = 0L;
	const gchar* _tmp11_ = NULL;
	g_return_val_if_fail (_usrid != NULL, NULL);
	_tmp0_ = _usrid;
	g_return_val_if_fail (_tmp0_ != NULL, NULL);
	_tmp1_ = _remote_port;
	g_return_val_if_fail (_tmp1_ <= ((guint) 65536), NULL);
	self = (NfSession*) g_object_new (object_type, NULL);
	g_get_current_time (&tv);
	_tmp2_ = _remote_port;
	_tmp3_ = _nf_session_getuniqid (self, _tmp2_);
	_tmp4_ = _tmp3_;
	nf_session_set_uniqid (self, _tmp4_);
	_g_free0 (_tmp4_);
	_tmp5_ = _remote_port;
	nf_session_set_remote_port (self, _tmp5_);
	_tmp6_ = _maxage;
	if (_tmp6_ == ((glong) 0)) {
		_maxage = (glong) 3600;
	}
	_tmp7_ = tv;
	_tmp8_ = _tmp7_.tv_sec;
	_tmp9_ = _maxage;
	nf_session_set_expire (self, _tmp8_ + _tmp9_);
	_tmp10_ = _maxage;
	nf_session_set_maxage (self, _tmp10_);
	_tmp11_ = _usrid;
	nf_session_set_usrid (self, _tmp11_);
	return self;
}


NfSession* nf_session_new (const gchar* _usrid, guint _remote_port, glong _maxage) {
	return nf_session_construct (TYPE_NF_SESSION, _usrid, _remote_port, _maxage);
}


static gchar* _nf_session_getuniqid (NfSession* self, guint remote_port) {
	gchar* result = NULL;
	guint _tmp0_ = 0U;
	GTimeVal tv = {0};
	gchar* uniqid = NULL;
	GTimeVal _tmp1_ = {0};
	glong _tmp2_ = 0L;
	GTimeVal _tmp3_ = {0};
	glong _tmp4_ = 0L;
	pid_t _tmp5_ = 0;
	guint _tmp6_ = 0U;
	gchar* _tmp7_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = remote_port;
	g_return_val_if_fail (_tmp0_ <= ((guint) 65536), NULL);
	g_get_current_time (&tv);
	_tmp1_ = tv;
	_tmp2_ = _tmp1_.tv_usec;
	_tmp3_ = tv;
	_tmp4_ = _tmp3_.tv_sec;
	_tmp5_ = getpid ();
	_tmp6_ = remote_port;
	_tmp7_ = g_strdup_printf ("%05x%05x%04x%04x", (guint) _tmp2_, (guint) _tmp4_, (guint) _tmp5_, _tmp6_ % 0x10000);
	uniqid = _tmp7_;
	result = uniqid;
	return result;
}


gboolean nf_session_isExpired (NfSession* self) {
	gboolean result = FALSE;
	GTimeVal tv = {0};
	glong _tmp0_ = 0L;
	glong _tmp1_ = 0L;
	GTimeVal _tmp2_ = {0};
	glong _tmp3_ = 0L;
	g_return_val_if_fail (self != NULL, FALSE);
	g_get_current_time (&tv);
	_tmp0_ = nf_session_get_expire (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = tv;
	_tmp3_ = _tmp2_.tv_sec;
	if (_tmp1_ < _tmp3_) {
		result = TRUE;
		return result;
	}
	result = FALSE;
	return result;
}


void nf_session_refreshExpire (NfSession* self) {
	GTimeVal tv = {0};
	GTimeVal _tmp0_ = {0};
	glong _tmp1_ = 0L;
	glong _tmp2_ = 0L;
	glong _tmp3_ = 0L;
	g_return_if_fail (self != NULL);
	g_get_current_time (&tv);
	_tmp0_ = tv;
	_tmp1_ = _tmp0_.tv_sec;
	_tmp2_ = nf_session_get_maxage (self);
	_tmp3_ = _tmp2_;
	nf_session_set_expire (self, _tmp1_ + _tmp3_);
}

void nf_session_refreshExpireSetUserTime (NfSession* self, glong sec) {
	GTimeVal tv = {0};
	GTimeVal _tmp0_ = {0};
	glong _tmp1_ = 0L;
	glong _tmp2_ = 0L;
	glong _tmp3_ = 0L;
	g_return_if_fail (self != NULL);
	g_get_current_time (&tv);
	_tmp0_ = tv;
	_tmp1_ = _tmp0_.tv_sec;
	_tmp2_ = nf_session_get_maxage (self);
	_tmp3_ = _tmp2_;

	nf_session_set_expire (self, _tmp1_ + _tmp3_ + sec);
}

const gchar* nf_session_dump (NfSession* self) {
	const gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	guint _tmp2_ = 0U;
	guint _tmp3_ = 0U;
	const gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	glong _tmp6_ = 0L;
	glong _tmp7_ = 0L;
	gchar* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = nf_session_get_usrid (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = nf_session_get_remote_port (self);
	_tmp3_ = _tmp2_;
	_tmp4_ = nf_session_get_uniqid (self);
	_tmp5_ = _tmp4_;
	_tmp6_ = nf_session_get_expire (self);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_strdup_printf ("[NfSession Dump] usrid=%s port=%u uniqid=%s expire=%ld\n", _tmp1_, _tmp3_, _tmp5_, _tmp7_);
	_g_free0 (self->priv->dumpstr);
	self->priv->dumpstr = _tmp8_;
	_tmp9_ = self->priv->dumpstr;
	result = _tmp9_;
	return result;
}


const gchar* nf_session_get_uniqid (NfSession* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_uniqid;
	result = _tmp0_;
	return result;
}


void nf_session_set_uniqid (NfSession* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_uniqid);
	self->priv->_uniqid = _tmp1_;
	g_object_notify ((GObject *) self, "uniqid");
}


const gchar* nf_session_get_usrid (NfSession* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_usrid;
	result = _tmp0_;
	return result;
}


void nf_session_set_usrid (NfSession* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_usrid);
	self->priv->_usrid = _tmp1_;
	g_object_notify ((GObject *) self, "usrid");
}


guint nf_session_get_remote_port (NfSession* self) {
	guint result;
	guint _tmp0_ = 0U;
	g_return_val_if_fail (self != NULL, 0U);
	_tmp0_ = self->priv->_remote_port;
	result = _tmp0_;
	return result;
}


void nf_session_set_remote_port (NfSession* self, guint value) {
	guint _tmp0_ = 0U;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_remote_port = _tmp0_;
	g_object_notify ((GObject *) self, "remote-port");
}


glong nf_session_get_expire (NfSession* self) {
	glong result;
	glong _tmp0_ = 0L;
	g_return_val_if_fail (self != NULL, 0L);
	_tmp0_ = self->priv->_expire;
	result = _tmp0_;
	return result;
}


void nf_session_set_expire (NfSession* self, glong value) {
	glong _tmp0_ = 0L;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_expire = _tmp0_;
	g_object_notify ((GObject *) self, "expire");
}


glong nf_session_get_maxage (NfSession* self) {
	glong result;
	glong _tmp0_ = 0L;
	g_return_val_if_fail (self != NULL, 0L);
	_tmp0_ = self->priv->_maxage;
	result = _tmp0_;
	return result;
}


void nf_session_set_maxage (NfSession* self, glong value) {
	glong _tmp0_ = 0L;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_maxage = _tmp0_;
	g_object_notify ((GObject *) self, "maxage");
}


static void nf_session_class_init (NfSessionClass * klass) {
	nf_session_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (NfSessionPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_nf_session_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_nf_session_set_property;
	G_OBJECT_CLASS (klass)->finalize = nf_session_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), NF_SESSION_UNIQID, g_param_spec_string ("uniqid", "uniqid", "uniqid", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), NF_SESSION_USRID, g_param_spec_string ("usrid", "usrid", "usrid", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), NF_SESSION_REMOTE_PORT, g_param_spec_uint ("remote-port", "remote-port", "remote-port", 0, G_MAXUINT, 0U, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), NF_SESSION_EXPIRE, g_param_spec_long ("expire", "expire", "expire", G_MINLONG, G_MAXLONG, 0L, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), NF_SESSION_MAXAGE, g_param_spec_long ("maxage", "maxage", "maxage", G_MINLONG, G_MAXLONG, 0L, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void nf_session_instance_init (NfSession * self) {
	self->priv = NF_SESSION_GET_PRIVATE (self);
}


static void nf_session_finalize (GObject* obj) {
	NfSession * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_NF_SESSION, NfSession);

        g_print("------------------ %s -----------------\n", __func__);
	_g_free0 (self->priv->dumpstr);
	_g_free0 (self->priv->_uniqid);
	_g_free0 (self->priv->_usrid);
	G_OBJECT_CLASS (nf_session_parent_class)->finalize (obj);
}


GType nf_session_get_type (void) {
	static volatile gsize nf_session_type_id__volatile = 0;
	if (g_once_init_enter (&nf_session_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (NfSessionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) nf_session_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NfSession), 0, (GInstanceInitFunc) nf_session_instance_init, NULL };
		GType nf_session_type_id;
		nf_session_type_id = g_type_register_static (G_TYPE_OBJECT, "NfSession", &g_define_type_info, 0);
		g_once_init_leave (&nf_session_type_id__volatile, nf_session_type_id);
	}
	return nf_session_type_id__volatile;
}


static void _vala_nf_session_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	NfSession * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_NF_SESSION, NfSession);
	switch (property_id) {
		case NF_SESSION_UNIQID:
		g_value_set_string (value, nf_session_get_uniqid (self));
		break;
		case NF_SESSION_USRID:
		g_value_set_string (value, nf_session_get_usrid (self));
		break;
		case NF_SESSION_REMOTE_PORT:
		g_value_set_uint (value, nf_session_get_remote_port (self));
		break;
		case NF_SESSION_EXPIRE:
		g_value_set_long (value, nf_session_get_expire (self));
		break;
		case NF_SESSION_MAXAGE:
		g_value_set_long (value, nf_session_get_maxage (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_nf_session_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	NfSession * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_NF_SESSION, NfSession);
	switch (property_id) {
		case NF_SESSION_UNIQID:
		nf_session_set_uniqid (self, g_value_get_string (value));
		break;
		case NF_SESSION_USRID:
		nf_session_set_usrid (self, g_value_get_string (value));
		break;
		case NF_SESSION_REMOTE_PORT:
		nf_session_set_remote_port (self, g_value_get_uint (value));
		break;
		case NF_SESSION_EXPIRE:
		nf_session_set_expire (self, g_value_get_long (value));
		break;
		case NF_SESSION_MAXAGE:
		nf_session_set_maxage (self, g_value_get_long (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _g_object_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}


static void _g_list_free__g_object_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
	g_list_free (self);
}


static NfSessionManager* nf_session_manager_construct (GType object_type) {
	NfSessionManager * self = NULL;
	self = (NfSessionManager*) g_object_new (object_type, NULL);
	__g_list_free__g_object_unref0_0 (self->priv->sessionList);
	self->priv->sessionList = NULL;
	return self;
}


static NfSessionManager* nf_session_manager_new (void) {
	return nf_session_manager_construct (TYPE_NF_SESSION_MANAGER);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


NfSessionManager* nf_session_manager_getInstance (void) {
	NfSessionManager* result = NULL;
	NfSessionManager* _tmp0_ = NULL;
	NfSessionManager* _tmp2_ = NULL;
	NfSessionManager* _tmp3_ = NULL;
	_tmp0_ = nf_session_manager_instance;
	if (_tmp0_ == NULL) {
		NfSessionManager* _tmp1_ = NULL;
		_tmp1_ = nf_session_manager_new ();
		_g_object_unref0 (nf_session_manager_instance);
		nf_session_manager_instance = _tmp1_;
	}
	_tmp2_ = nf_session_manager_instance;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


guint nf_session_manager_addSession (NfSessionManager* self, NfSession* nfsession) {
	guint result = 0U;
	NfSession* _tmp0_ = NULL;
	NfSession* sess = NULL;
	NfSession* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	NfSession* _tmp4_ = NULL;
	GMutex* _tmp5_ = NULL;
	NfSession* _tmp6_ = NULL;
	GList* _tmp15_ = NULL;
	guint _tmp16_ = 0U;
	NfSession* _tmp21_ = NULL;
	NfSession* _tmp22_ = NULL;
	GMutex* _tmp23_ = NULL;
	gboolean _tmp24_ = FALSE;
	GList* _tmp25_ = NULL;
	guint _tmp26_ = 0U;
	g_return_val_if_fail (self != NULL, 0U);
	g_return_val_if_fail (nfsession != NULL, 0U);
	_tmp0_ = nfsession;
	g_return_val_if_fail (_tmp0_ != NULL, 0U);
	_tmp1_ = nfsession;
	_tmp2_ = nf_session_get_uniqid (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = nf_session_manager_findSession (self, _tmp3_);
	sess = _tmp4_;
	_tmp5_ = self->priv->mutex;
	g_mutex_lock (_tmp5_);
	_tmp6_ = sess;
	if (_tmp6_ != NULL) {
		FILE* _tmp7_ = NULL;
		NfSession* _tmp8_ = NULL;
		const gchar* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
		NfSession* _tmp11_ = NULL;
		GMutex* _tmp12_ = NULL;
		GList* _tmp13_ = NULL;
		guint _tmp14_ = 0U;
		_tmp7_ = stderr;
		_tmp8_ = sess;
		_tmp9_ = nf_session_get_uniqid (_tmp8_);
		_tmp10_ = _tmp9_;
		fprintf (_tmp7_, "Session %s is exists, not appended\n", _tmp10_);
		_tmp11_ = nfsession;
		g_object_unref ((GObject*) _tmp11_);
		_tmp12_ = self->priv->mutex;
		g_mutex_unlock (_tmp12_);
		_tmp13_ = self->priv->sessionList;
		_tmp14_ = g_list_length (_tmp13_);
		result = _tmp14_;
		return result;
	}
	_tmp15_ = self->priv->sessionList;
	_tmp16_ = g_list_length (_tmp15_);
	if (_tmp16_ >= ((guint) SESSION_MAX)) {
		NfSession* sess0 = NULL;
		GList* _tmp17_ = NULL;
		gconstpointer _tmp18_ = NULL;
		NfSession* _tmp19_ = NULL;
		NfSession* _tmp20_ = NULL;
		_tmp17_ = self->priv->sessionList;
		_tmp18_ = g_list_nth_data (_tmp17_, (guint) 0);
		sess0 = (NfSession*) _tmp18_;
		_tmp19_ = sess0;
		self->priv->sessionList = g_list_remove (self->priv->sessionList, _tmp19_);
		_tmp20_ = sess0;
		g_object_unref ((GObject*) _tmp20_);
	}
	_tmp21_ = nfsession;
	_tmp22_ = _g_object_ref0 (_tmp21_);
	self->priv->sessionList = g_list_append (self->priv->sessionList, _tmp22_);
	_tmp23_ = self->priv->mutex;
	g_mutex_unlock (_tmp23_);
	_tmp24_ = self->priv->use_session_file;
	if (_tmp24_) {
	}
	_tmp25_ = self->priv->sessionList;
	_tmp26_ = g_list_length (_tmp25_);
	result = _tmp26_;
	return result;
}


void nf_session_manager_removeSession (NfSessionManager* self, NfSession* session) {
	NfSession* _tmp0_ = NULL;
	GMutex* _tmp1_ = NULL;
	NfSession* _tmp2_ = NULL;
	NfSession* _tmp3_ = NULL;
	GMutex* _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = session;
	g_return_if_fail (_tmp0_ != NULL);
	_tmp1_ = self->priv->mutex;
	g_mutex_lock (_tmp1_);
	_tmp2_ = session;
	self->priv->sessionList = g_list_remove (self->priv->sessionList, _tmp2_);
	_tmp3_ = session;
	g_object_unref ((GObject*) _tmp3_);
	_tmp4_ = self->priv->mutex;
	g_mutex_unlock (_tmp4_);
}


static gint __lambda3_ (NfSession* a, NfSession* b) {
	gint result = 0;
	GCompareFunc _tmp0_ = NULL;
	NfSession* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	NfSession* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	g_return_val_if_fail (a != NULL, 0);
	g_return_val_if_fail (b != NULL, 0);
	_tmp0_ = g_strcmp0;
	_tmp1_ = a;
	_tmp2_ = nf_session_get_uniqid (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = b;
	_tmp5_ = nf_session_get_uniqid (_tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = _tmp0_ (_tmp3_, _tmp6_);
	result = _tmp7_;
	return result;
}


static gint ___lambda3__gcompare_func (gconstpointer a, gconstpointer b) {
	gint result;
	result = __lambda3_ ((NfSession*) a, (NfSession*) b);
	return result;
}


NfSession* nf_session_manager_findSession (NfSessionManager* self, const gchar* sessionId) {
	NfSession* result = NULL;
	GCompareFunc sessionCmpById = NULL;
	NfSession* findSessId = NULL;
	NfSession* _tmp0_ = NULL;
	NfSession* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	GMutex* _tmp3_ = NULL;
	GList* session_elem = NULL;
	GList* _tmp4_ = NULL;
	NfSession* _tmp5_ = NULL;
	GCompareFunc _tmp6_ = NULL;
	GList* _tmp7_ = NULL;
	GList* _tmp8_ = NULL;
	GList* _tmp10_ = NULL;
	gconstpointer _tmp11_ = NULL;
	gboolean _tmp12_ = FALSE;
	GMutex* _tmp20_ = NULL;
	GList* _tmp21_ = NULL;
	gconstpointer _tmp22_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (sessionId != NULL, NULL);
	sessionCmpById = ___lambda3__gcompare_func;
	_tmp0_ = nf_session_new ("", (guint) 0, (glong) 0);
	findSessId = _tmp0_;
	_tmp1_ = findSessId;
	_tmp2_ = sessionId;
	nf_session_set_uniqid (_tmp1_, _tmp2_);
	_tmp3_ = self->priv->mutex;
	g_mutex_lock (_tmp3_);
	_tmp4_ = self->priv->sessionList;
	_tmp5_ = findSessId;
	_tmp6_ = sessionCmpById;
	_tmp7_ = g_list_find_custom (_tmp4_, _tmp5_, _tmp6_);
	session_elem = _tmp7_;
	_tmp8_ = session_elem;
	if (_tmp8_ == NULL) {
		GMutex* _tmp9_ = NULL;
		_tmp9_ = self->priv->mutex;
		g_mutex_unlock (_tmp9_);
		result = NULL;
		_g_object_unref0 (findSessId);
		return result;
	}
	_tmp10_ = session_elem;
	_tmp11_ = _tmp10_->data;
	_tmp12_ = nf_session_isExpired ((NfSession*) _tmp11_);
	if (_tmp12_) {
		FILE* _tmp13_ = NULL;
		GList* _tmp14_ = NULL;
		gconstpointer _tmp15_ = NULL;
		const gchar* _tmp16_ = NULL;
		GMutex* _tmp17_ = NULL;
		GList* _tmp18_ = NULL;
		gconstpointer _tmp19_ = NULL;
		_tmp13_ = stdout;
		_tmp14_ = session_elem;
		_tmp15_ = _tmp14_->data;
		_tmp16_ = nf_session_dump ((NfSession*) _tmp15_);
		fprintf (_tmp13_, "session: %s is expired\n", _tmp16_);
		_tmp17_ = self->priv->mutex;
		g_mutex_unlock (_tmp17_);
		_tmp18_ = session_elem;
		_tmp19_ = _tmp18_->data;
		nf_session_manager_removeSession (self, (NfSession*) _tmp19_);
		result = NULL;
		_g_object_unref0 (findSessId);
		return result;
	}
	_tmp20_ = self->priv->mutex;
	g_mutex_unlock (_tmp20_);
	_tmp21_ = session_elem;
	_tmp22_ = _tmp21_->data;
	result = (NfSession*) _tmp22_;
	_g_object_unref0 (findSessId);
	return result;
}


NfSession* nf_session_manager_findSessionByIdx (NfSessionManager* self, gint index) {
	NfSession* result = NULL;
	gint _tmp0_ = 0;
	GList* _tmp1_ = NULL;
	guint _tmp2_ = 0U;
	GList* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gconstpointer _tmp5_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = index;
	_tmp1_ = self->priv->sessionList;
	_tmp2_ = g_list_length (_tmp1_);
	g_return_val_if_fail (((guint) _tmp0_) < _tmp2_, NULL);
	_tmp3_ = self->priv->sessionList;
	_tmp4_ = index;
	_tmp5_ = g_list_nth_data (_tmp3_, (guint) _tmp4_);
	result = (NfSession*) _tmp5_;
	return result;
}


const gchar* nf_session_manager_dump (NfSessionManager* self) {
	const gchar* result = NULL;
	gint i = 0;
	GMutex* _tmp0_ = NULL;
	GTimeVal tv = {0};
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	GList* _tmp3_ = NULL;
	guint _tmp4_ = 0U;
	GTimeVal _tmp5_ = {0};
	glong _tmp6_ = 0L;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	GList* _tmp10_ = NULL;
	const gchar* _tmp34_ = NULL;
	gchar* _tmp35_ = NULL;
	GMutex* _tmp36_ = NULL;
	const gchar* _tmp37_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	i = 0;
	_tmp0_ = self->priv->mutex;
	g_mutex_lock (_tmp0_);
	g_get_current_time (&tv);
	_tmp1_ = g_strdup ("========= [User Session ========\n");
	_g_free0 (self->priv->dumpstr);
	self->priv->dumpstr = _tmp1_;
	_tmp2_ = self->priv->dumpstr;
	_tmp3_ = self->priv->sessionList;
	_tmp4_ = g_list_length (_tmp3_);
	_tmp5_ = tv;
	_tmp6_ = _tmp5_.tv_sec;
	_tmp7_ = g_strdup_printf ("List Len=%u Now=%ld\n", _tmp4_, _tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = g_strconcat (_tmp2_, _tmp8_, NULL);
	_g_free0 (self->priv->dumpstr);
	self->priv->dumpstr = _tmp9_;
	_g_free0 (_tmp8_);
	_tmp10_ = self->priv->sessionList;
	{
		GList* sess_collection = NULL;
		GList* sess_it = NULL;
		sess_collection = _tmp10_;
		for (sess_it = sess_collection; sess_it != NULL; sess_it = sess_it->next) {
			NfSession* _tmp11_ = NULL;
			NfSession* sess = NULL;
			_tmp11_ = _g_object_ref0 ((NfSession*) sess_it->data);
			sess = _tmp11_;
			{
				const gchar* _tmp12_ = NULL;
				gint _tmp13_ = 0;
				NfSession* _tmp14_ = NULL;
				GList* _tmp15_ = NULL;
				NfSession* _tmp16_ = NULL;
				const gchar* _tmp17_ = NULL;
				const gchar* _tmp18_ = NULL;
				NfSession* _tmp19_ = NULL;
				guint _tmp20_ = 0U;
				guint _tmp21_ = 0U;
				NfSession* _tmp22_ = NULL;
				const gchar* _tmp23_ = NULL;
				const gchar* _tmp24_ = NULL;
				NfSession* _tmp25_ = NULL;
				glong _tmp26_ = 0L;
				glong _tmp27_ = 0L;
				NfSession* _tmp28_ = NULL;
				glong _tmp29_ = 0L;
				glong _tmp30_ = 0L;
				gchar* _tmp31_ = NULL;
				gchar* _tmp32_ = NULL;
				gchar* _tmp33_ = NULL;
				_tmp12_ = self->priv->dumpstr;
				_tmp13_ = i;
				i = _tmp13_ + 1;
				_tmp14_ = sess;
				_tmp15_ = self->priv->sessionList;
				_tmp16_ = sess;
				_tmp17_ = nf_session_get_usrid (_tmp16_);
				_tmp18_ = _tmp17_;
				_tmp19_ = sess;
				_tmp20_ = nf_session_get_remote_port (_tmp19_);
				_tmp21_ = _tmp20_;
				_tmp22_ = sess;
				_tmp23_ = nf_session_get_uniqid (_tmp22_);
				_tmp24_ = _tmp23_;
				_tmp25_ = sess;
				_tmp26_ = nf_session_get_expire (_tmp25_);
				_tmp27_ = _tmp26_;
				_tmp28_ = sess;
				_tmp29_ = nf_session_get_maxage (_tmp28_);
				_tmp30_ = _tmp29_;
				_tmp31_ = g_strdup_printf ("[%d:%p:%p] usrid=%s, port=%u, uniqid=%s expire=%ld[+%ld]\n", _tmp13_, _tmp14_, _tmp15_, _tmp18_, _tmp21_, _tmp24_, _tmp27_, _tmp30_);
				_tmp32_ = _tmp31_;
				_tmp33_ = g_strconcat (_tmp12_, _tmp32_, NULL);
				_g_free0 (self->priv->dumpstr);
				self->priv->dumpstr = _tmp33_;
				_g_free0 (_tmp32_);
				_g_object_unref0 (sess);
			}
		}
	}
	_tmp34_ = self->priv->dumpstr;
	_tmp35_ = g_strconcat (_tmp34_, "========= User Session] ========\n", NULL);
	_g_free0 (self->priv->dumpstr);
	self->priv->dumpstr = _tmp35_;
	_tmp36_ = self->priv->mutex;
	g_mutex_unlock (_tmp36_);
	_tmp37_ = self->priv->dumpstr;
	result = _tmp37_;
	return result;
}


static void nf_session_manager_class_init (NfSessionManagerClass * klass) {
	nf_session_manager_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (NfSessionManagerPrivate));
	G_OBJECT_CLASS (klass)->finalize = nf_session_manager_finalize;
}


static void nf_session_manager_instance_init (NfSessionManager * self) {
	GMutex* _tmp0_ = NULL;
	self->priv = NF_SESSION_MANAGER_GET_PRIVATE (self);
	_tmp0_ = g_mutex_new ();
	self->priv->mutex = _tmp0_;
	self->priv->use_session_file = FALSE;
	self->priv->sessionList = NULL;
}


static void nf_session_manager_finalize (GObject* obj) {
	NfSessionManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_NF_SESSION_MANAGER, NfSessionManager);
	_g_mutex_free0 (self->priv->mutex);
	_g_free0 (self->priv->dumpstr);
	__g_list_free__g_object_unref0_0 (self->priv->sessionList);
	G_OBJECT_CLASS (nf_session_manager_parent_class)->finalize (obj);
}


GType nf_session_manager_get_type (void) {
	static volatile gsize nf_session_manager_type_id__volatile = 0;
	if (g_once_init_enter (&nf_session_manager_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (NfSessionManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) nf_session_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NfSessionManager), 0, (GInstanceInitFunc) nf_session_manager_instance_init, NULL };
		GType nf_session_manager_type_id;
		nf_session_manager_type_id = g_type_register_static (G_TYPE_OBJECT, "NfSessionManager", &g_define_type_info, 0);
		g_once_init_leave (&nf_session_manager_type_id__volatile, nf_session_manager_type_id);
	}
	return nf_session_manager_type_id__volatile;
}



